{
    "AUTO_no_out_bresv": "Lo client a pas mai de reservacions sortidas pel moment.",
    "PICKUP_ERROR": "Error de comunicacion amb lo servidor (temptativa de presa de liurason) :",
    "AUTO_no_in_bresv": "Lo client a pas restituit cap de ressorsas u\u00e8i :",
    "NO_SUCH_RETURNABLE_RESOURCE": "Pas cap de ressorsa tornabla d'aqueste mena.",
    "AUTO_ATTR_VALUE_return": "Retorn",
    "RETURNABLE_RESOURCE_ERROR": "Error a la rec\u00e8rca d\u2019una ressorsa tornabla :",
    "RETURN_NO_RESPONSE": "No response from server when attempting return.",
    "AUTO_ATTR_VALUE_pickup": "Prene en liurason",
    "AUTO_barcode_type": "Restituit amb lo c\u00f2de de barras seguent :",
    "AUTO_in_bresv": "Lo client a restituit aquelas ressorsas u\u00e8i",
    "RESERVATIONS_ERROR": "Error de comunicacion amb lo servidor (demanda de reservacions) :",
    "AUTO_patron": "Client",
    "COPY_ALERT": "${0}:\n${1}\n\nLo vol\u00e8tz tractar malgrat tot ?",
    "AUTO_resource": "Ressorsa",
    "RETURN_ERROR": "Error de comunicacion amb lo servidor (temptativa de restitucion) :",
    "AUTO_patron_barcode": "Entrar lo c\u00f2de de barras del client :",
    "AUTO_h1": "Presa en liurason de reservacions",
    "AUTO_ATTR_VALUE_go": "Validar",
    "AUTO_out_bresv": "Lo client a sortit aquelas reservacions :",
    "AUTO_ready_bresv": "Aquestas reservacions del client son pr\u00e8stas per \u00e8sser presas en liurason :",
    "RESERVATIONS_NO_RESPONSE": "No response from server when asking for reservations.",
    "AUTO_ATTR_VALUE_reset": "Escafar/ client nov\u00e8l",
    "RETURN_SUCCESS": "Restitucion capitada.",
    "PICKUP_NO_RESPONSE": "No response from server when attempting pickup.",
    "NOTICE_CHANGE_OF_PATRON": "Note that the resource scanned was out on reservation to a different\npatron than the last resource you scanned.  If this is not\nexpected, stop to examine outstanding reservations for your patron\nor on the resource.",
    "NO_PATRON_BARCODE": "Entratz lo c\u00f2de de barras d\u2019un client",
    "ADDRESS": "${0}\n${1}\n${2}, ${3} ${4}",
    "SELECT_SOMETHING": "Av\u00e8tz pas seleccionat cap de reservacion.",
    "AUTO_no_ready_bresv": "Lo client a pas cap de reservacions que son pr\u00e8stas per \u00e8sser presas en liurason pel moment.",
    "AUTO_return_h1": "Restitucion d\u2019articles reservats"
}