{
    "VIEW_MARC": "View MARC",
    "CONFIRM_DELETE_RESULT": "Deleted authority record # ${0}.",
    "TARGET_RECORD": "Cibla",
    "MENU_MERGE": "Marcar per fusion",
    "HIDE_MARC": "Hide MARC",
    "AUTHORITY_FIELDS": "Authority Fields (${0})",
    "MENU_EDIT": "Modificar",
    "CONFIRM_DELETE_TITLE": "Delete the authority record: \"${0}\"?",
    "CONFIRM_DELETE_PROMPT": "Confirm deletion of record # ${0}",
    "MASTER_RECORD": "Principal",
    "CANCEL": "Anullar",
    "NONE_LINK": "[None]",
    "SAVE_RESULT_SUCCESS": "Record was saved.",
    "MENU_DELETE": "Suprimir",
    "LINKED_BIBS": "Number of linked bibliographic records: ${0}",
    "ACTIONS": "Accions",
    "MERGE_RESULT_SUCCESS": "Record merge is complete.",
    "CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    "THESAURI": "Thesauri (${0})",
    "SAVE": "Enregistrar",
    "AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    "DELETE": "Suprimir"
}