{
    "SUCCESS_SAVING_PHYSICAL": "Cambios grabados a la Direcci\u00f3n F\u00edsica de ${0}",
    "CONFIRM_EXIT_CCS": "Hay cambios a los estados de una copia o m\u00e1s no grabados. Haca clic en Aceptar para grabar los cambios, o Cancelar para abandonarlos.",
    "SURVEY_SAVE_CHANGES": "Guardar Cambios",
    "ERROR_CREATING_CHILD_AOU": "Problema creando unidad organizacional hija.",
    "ERROR_CALLING_METHOD_PPL": "Problema llamando al crear un nuevo permiso",
    "TRANSLATION": "Traducci\u00f3n",
    "ERROR_FETCHING_ORGS": "Problema al obtener informaci\u00f3n de unidad organizacional",
    "SUCCESS_CREATING_STATUS": "Nuevo ${0} porcentaje de creado",
    "SUCCESS_SAVING_HOLDS": "Grabado cambios a la Direcci\u00f3n De Apartados para ${0}",
    "SUCCESS_SAVING_ILL": "Salvados los cambios de la dirrecion \"ILL\"",
    "CBHO_NO_LOAD": "No es posible cargar el ejemplar seleccionado",
    "STATUS_EDITING": "Ahora Editando ${0}",
    "SUCCESS_SAVING_DATA": "Datos guardados de ${0}",
    "SUCCESS_DELETED_PERM_MAP": "Asignaci\u00f3n de permisos borrada",
    "ERROR_SAVING_PERM_DATA": "Problema al salvar datos del permiso ${0}",
    "ERROR_FETCHING_HOLDS": "Problema de ir a busca la  Direcci\u00f3n de ${0}",
    "HOLDABLE": "Sostenible",
    "CBHO_FIELD_DISPLAY": "[${0}] ${1}",
    "STATUS_DELETED": "${0} eliminado",
    "ERROR_CALLING_METHOD_CCS": "Problema llamando al m\u00e9todo para crear el estado de una nueva copia",
    "SUCCESS_CREATING_CODE": "Nuevo ${0} ${1} creado",
    "ACQ_DISTRIB_FORMULA_NAME_PROMPT": "Ingrese el nombre de la nueva formula",
    "ERROR_SAVING_DATA": "Problema guardando los datos para ${0}",
    "LABEL_NEW_BRANCH": "Nueva Sucursal",
    "ERROR_FETCHING_HOURS": "Problema al obtener horas de operaci\u00f3n para ${0}",
    "LABEL_TRANSLATION": "Traducci\u00f3n",
    "ERROR_CREATING_PERMISSION": "Problema al crear un nuevo permiso",
    "LABEL_DESCRIPTION": "Descripci\u00f3n",
    "ERROR_SAVING_HOO": "Problema grabando la informaci\u00f3n de las Horas de Operaci\u00f3n para ${0}",
    "SUCCESS_NEW_PERM_MAP": "Nuevo permiso para crear mapa",
    "END_SURVEY": "Finalizar Encuesta Ahora",
    "CONFIRM_UNSAVED_CHANGES": "Existen cambios sin guardar en uno o mas tipos de organizaci\u00f3n. Click OK para guardar estos cambios, o Cancelar para abandonarlos.",
    "OPAC_VISIBLE": "Cat\u00e1logo En L\u00ednea De Acceso P\u00fablico Visible",
    "SURVEY_FOOT_LABEL": "Preguntas & Respuestas",
    "ERROR_DELETING": "Problema borrando ${0}",
    "ERROR_FETCHING_TYPES_AOUT": "Problema cargando los tipos de unidades de organizaci\u00f3n",
    "CONFIRM_DELETE": "Estas seguro que quieres eliminar ${0}?",
    "ERROR_ORPHANS": "No se puede borrar ${0}, ${1} subordinados todav\u00eda existen.",
    "LABEL_DEPTH": "Profundidad",
    "LABEL_NEW_TYPE": "Nuevo Tipo",
    "LABEL_VALUE": "Valor",
    "SUCCESS_CREATING_CHILD_AOU": "Nueva unidad de organizacion hija creada para ${0}",
    "LABEL_CODE": "C\u00f3digo",
    "CBHO_EDITING_EXISTING": "Est\u00e1 editando mejor retenci\u00f3n de pedidos #${0}: ${1}.",
    "CBHO_NEEDS_NAME": "Es necesario introducir un nombre para la mejor orden de retenci\u00f3n .",
    "ERROR_FETCHING_PHYSICAL": "Problema buscando La Direcci\u00f3n F\u00edsica para ${0}",
    "CONFIRM_EXIT_PPL": "Hay cambios a los permisos sin grabar. Haga clic en Aceptar para guardar estos cambios, o Cancelar para abandonarlos.",
    "ERROR_FETCHING_PERMS": "Problema al obtener permisos",
    "LABEL_NEW_GROUP": "Nuevo Grupo",
    "SUCCESS_SAVING_HOO": "Horas de Operaci\u00f3n actualizad para ${0}",
    "ERROR_SAVING_STATUS": "Problema salvando ${0}",
    "ERROR_SAVING_PHYSICAL": "Problema guardando la informaci\u00f3n de la Direcci\u00f3n F\u00edsica para ${0}",
    "CONFIRM_EXIT_AOU": "Hay cambios sin grabar a una o mas unidades de organizaci\u00f3n. Haga click en Aceptar para grabar estos cambios, o Cancelar para abandonarlos.",
    "ERROR_DELETING_PERM_MAPPING": "Problema borrando asignaci\u00f3n de permiso ${0}",
    "ERROR_SAVING_DATA_CAM": "Problema grabando datos para ${0} ${1}",
    "SUCCESS_SAVING_MAILING": "Salvar cambios de la dirrecion del correo ${0}",
    "ERROR_FETCHING_MAILING": "Problema al extraer la Direcci\u00f3n de Correo para ${0}",
    "ACQ_DISTRIB_FORMULA_NAME_CLONE": "${0} (Clon)",
    "ERROR_CREATING_CHILD_GROUP": "Problema creando el grupo hijo",
    "ERROR_DELETING_LAST_AOU": "No se puede borrar ${0}, necesita por lo menos una unidad de organizaci\u00f3n.",
    "ERROR_SAVING_HOLDS": "Problema grabando la informaci\u00f3n de Direcci\u00f3n De Apartados para ${0}",
    "NAME": "Nombre",
    "SUCCESS_CREATING_CHILD_AOUT": "Nuevo Tipo de Organizaci\u00f3n hijo creado para ${0}",
    "LABEL_GRANTABLE": "Puede hacerse",
    "ERROR_SAVING_ILL": "Problema grabando la informaci\u00f3n de la Direcci\u00f3n ILL para ${0}",
    "SURVEY_WARN_TEXT": "No se pueden modificar ni agregar preguntas en este momento. La fecha de inicio de la encuesta debe establecerse para el futuro para agregar nuevas preguntas o modificar las preguntas existentes.",
    "ERROR_FETCHING_GROUPS": "Problema buscando grupos",
    "SUCCESS_CREATING_PERMISSION": "Nuevo ${0} permiso creado",
    "SURVEY_ID": "Estudio de ID # ${0}",
    "COPY_ACTIVE": "Define copia activa",
    "ERROR_CREATING_PERM_MAP": "Problema al crear nuevo Mapa de Permisos",
    "SURVEY_DELETE_ANSWER": "Eliminar pregunta",
    "SURVEY_QUESTION": "Pregunta:",
    "CONFIRM_EXIT_CAM": "Hay cambios no grabados a uno o m\u00e1s ${0} c\u00f3digos. Haga clic en Aceptar para guardar los cambios, o Cancelar para abandonarlos.",
    "ERROR_DELETING_LAST_AOUT": "No se pudo borrar ${0}. Necesita un minimo de un tipo de organizaci\u00f3n.",
    "ERROR_FETCHING_ILL": "Problema al obtener Direcci\u00f3n ILL para ${0}",
    "ERROR_CREATING_CHILD_AOUT": "Problema creando una organizaci\u00f3n tipo ni\u00f1o",
    "ERROR_CALLING_METHOD_PGT": "Problema al llamar m\u00e9todo para crear Grupo hijo",
    "CONFIRM_EXIT_PGT": "Hay cambios a los mapas de permiso sin graber. Haca clic en Aceptar para grabar estos cambios, o Cancelar para abandonarlos.",
    "SURVEY_ANSWER": "Respuesta:",
    "ERROR_FETCHING_PERM_MAPS": "Problema al obtener mapa de permisos",
    "SURVEY_SAVE_ADD": "Grabar Pregunta Y Agregar Respuesta",
    "SUCCESS_SAVE": "Datos guardados de ${0}",
    "ERROR_CALLING_METHOD_PERM_MAP": "Problema llamando el m\u00e9todo para crear un nuevo mapa de permiso",
    "EVENT_DEF_LABEL": "Copy text \t ${0}: ${1}",
    "SURVEY_DELETE_QUESTION": "Borrar Preguntas Y Respuestas",
    "SUCCESS_SAVE_PERM": "Grabando cambios de permiso a ${0}",
    "SURVEY_ADD_ANSWER": "Agregar Respuesta",
    "ERROR_FETCHING_STATUSES": "Problema cargando estados",
    "ID": "Identificaci\u00f3n",
    "ERROR_CALLING_METHOD_CAM": "Problema al llamar al m\u00e9todo para crear nuevo ${0}",
    "CBHO_EDITING_NEW": "Esta editando una nueva orden de mejor retenci\u00f3n.",
    "ERROR_SAVING_MAILING": "Problema guardando la informaci\u00f3n de la Direcci\u00f3n Postal para ${0}",
    "IS_AVAILABLE": "Est\u00e1 Disponible",
    "ERROR_CALLING_METHOD_AOUT": "Problema llamando al m\u00e9todo para crear una organizaci\u00f3n tipo ni\u00f1o",
    "ERROR_CREATING_STATUS": "Problema creando un Estado nuevo",
    "SUCCESS_NEW_CHILD_GROUP": "Nuevo Grupo hijo creado para ${0}"
}