{
    "VIEW_MARC": "Voir le MARC",
    "CONFIRM_DELETE_RESULT": "Notice d\u2019autorit\u00e9 # ${0. supprim\u00e9e.",
    "TARGET_RECORD": "Cible",
    "MENU_MERGE": "Marquer pour fusion",
    "HIDE_MARC": "Cacher MARC",
    "AUTHORITY_FIELDS": "Authority Fields (${0})",
    "MENU_EDIT": "Modifier",
    "CONFIRM_DELETE_TITLE": "Supprimer la notice d\u2019autorit\u00e9 : \\\"${0}\\\"?",
    "CONFIRM_DELETE_PROMPT": "Confirmer la suppression de la notice # ${0}",
    "MASTER_RECORD": "Original",
    "CANCEL": "Annuler",
    "NONE_LINK": "[Aucun]",
    "SAVE_RESULT_SUCCESS": "Notice sauvegard\u00e9e.",
    "MENU_DELETE": "Supprimer",
    "LINKED_BIBS": "Nombre de fiches bibliographiques associ\u00e9es : ${0}",
    "ACTIONS": "Actions",
    "MERGE_RESULT_SUCCESS": "Fusion de la notice termin\u00e9e.",
    "CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    "THESAURI": "Thesauri (${0})",
    "SAVE": "Sauvegarder",
    "AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    "DELETE": "Supprimer"
}