{
    "MARC_EDITOR_TITLE": "ID de registro #${0}",
    "SELECT_MORE": "Haga clic aqu\u00ed para revisar todas las direcciones URL de sesi\u00f3n y / o seleccionar otras URLs para verificar",
    "CLONE_SESSION_NAME": "Copia de ${0}",
    "SESSION_NAME": "Sesi\u00f3n '${0}'",
    "CREATING": "Creando sesi\u00f3n ...",
    "MARC_EDITOR_LINK": "Haga clic para abrir el Editor de MARC para este registro",
    "EXTRACTING_URLS": "Extrayendo URLs ...",
    "INTERFACE_SETUP": "Estableciendo interfaz ...",
    "NOTHING_SELECTED": "No hay filas seleccionadas, as\u00ed que no se efectuar\u00e1 ninguna acci\u00f3n",
    "REREVIEW": "Abrir",
    "MARC_EDITOR_SAVE_RECORD": "Guardar Registro",
    "REDIRECTING": "Cargando pr\u00f3xima interfaz ...",
    "XPATH": "XPath",
    "SAVING_TAGS": "Guardando etiqueta/ Selectores del subcampo ...",
    "VERIFICATION_ATTEMPT_ID": "Verificaci\u00f3n intento ID: ${0}",
    "VERIFICATION_DIALOG": "Verificaci\u00f3n de URLs ...",
    "EDIT": "Editar",
    "VERIFY_ALL": "Haga clic en 'Aceptar' para verificar todas las URL que pertenecen a esta sesi\u00f3n y combinar todos los t\u00e9rminos de b\u00fasqueda. Haga clic en \"Cancelar\" si el seleccionado, direcciones URL visibles son los \u00fanicos que desea verificar.",
    "REVIEW_ATTEMPT": "Revisar esta intento de verificaci\u00f3n",
    "CLONE_SESSION": "Clonar",
    "CLONING": "Clonando sesi\u00f3n existente ...",
    "PERFORMING_SEARCH": "Realizando b\u00fasqueda ...",
    "NEED_UVUS": "Debe a\u00f1adir algunas combinaciones de etiquetas y subcampos."
}