{
    "and": "ET",
    "sort": "Sort Axis",
    "bib_level": "Niveau bibliographique",
    "less": "...Moins",
    "item_form": "Forme",
    "site": "Site",
    "filters": "Filtres",
    "notcontains": "Ne contient pas",
    "statuses": "Statuses",
    "before": "Publi\u00e9 avant",
    "new_facet": "Nouvelle facette",
    "lit_form": "Forme litt\u00e9raire",
    "faceted_searches": "Facettes",
    "contains": "Contient",
    "audience": "Public",
    "filter_default": "S\u00e9lectionnez un filtre",
    "metabib": "Metarecord Search",
    "basic": "Basic",
    "new_modifier": "New Modifier",
    "staff": "Staff Search",
    "classed_searches": "Classed Searches",
    "more": "Plus...",
    "available": "Disponible",
    "new_filter": "Nouveau filtre",
    "format": "Type and Form",
    "after": "Publi\u00e9 apr\u00e8s",
    "ascending": "Tri croissant",
    "descending": "Tri d\u00e9croissant",
    "modifier_default": "S\u00e9lectionnez un modificateur",
    "during": "In Publication",
    "exact": "Exactly Matches",
    "between": "Publi\u00e9s entre",
    "advanced": "Advanced",
    "modifiers": "Modificateurs",
    "perform_search": "D\u00e9marrer !",
    "remove": "Supprimer",
    "item_type": "Type",
    "depth": "Search Depth",
    "vr_format": "Videorecording Format",
    "or": "OU"
}