{
    "NO_PAYLOAD": "N\u00f3s n\u00e3o recebemos mais informa\u00e7\u00f5es do servidor sobre essa tentativa de captura.",
    "TITLE": "T\u00ed\u00adtulo",
    "PRINT": "<u>I</u>mprimir",
    "AUTO_resource_barcode": "Digite o c\u00f3digo de barras:",
    "DURATION": "Reservado de",
    "NEEDS_ROUTED_TO": "Esta item precisa ser encaminhado para",
    "PRINTED_BY": "Impresso por",
    "CAPTURE_TRANSIT_SOURCE": "De:",
    "CAPTURE_INFO": "Capturar Informa\u00e7\u00e3o",
    "AUTO_ATTR_VALUE_capture": "Capturar",
    "AUTHOR": "Autor",
    "CAPTURE_BRESV_BRSRC": "C\u00f3digo de barras de recursos:",
    "SLIP_DATE": "Data do comprovante",
    "RESERVATION_SHELF": "PRATELEIRA DE RESERVA",
    "UNKNOWN_PROBLEM": "Um problema desconhecido ocorreu durante a tentativa de captura.",
    "FAILURE": "Captura falhou",
    "CAPTURE_CAUSES_TRANSIT": "Este item est\u00e1 em tr\u00e2nsito!",
    "RESERVED": "Reservado para patrono",
    "SUCCESS": "Captura sucedida",
    "REQUEST": "Hora da solicita\u00e7\u00e3o",
    "AT": "em",
    "CAPTURE_BRESV_PICKUP_LIB": "Biblioteca de retirada",
    "CAPTURED_NOTHING": "N\u00e3o capturou nada.",
    "TRANSIT": "*** TRANSITO ***",
    "BARCODE": "C\u00f3digo de Barras",
    "AUTO_pickup_lib_selector": "Biblioteca de retirada",
    "CAPTURE_TRANSIT_DEST": "Para:",
    "PRINT_ACCESSKEY": "P",
    "CAPTURE_BRESV_DATES": "Tempo de reserva",
    "HERES_WHAT_WE_KNOW": "A informa\u00e7\u00e3o a seguir esta dispon\u00edvel sobre a falha de captura:",
    "AUTO_capture_heading": "Captar Recursos Reservados"
}