{
    "AUTO_no_out_bresv": "Patron has no more reservations out at this time.",
    "PICKUP_ERROR": "Erro na comunica\u00e7\u00e3o com o servidor(tentando pickup)",
    "AUTO_no_in_bresv": "Patron has not returned any resources today.",
    "NO_SUCH_RETURNABLE_RESOURCE": "N\u00e3o existe tal recurso de devolu\u00e7\u00e3o",
    "AUTO_ATTR_VALUE_return": "Retornar",
    "RETURNABLE_RESOURCE_ERROR": "Error looking up returnable resource:",
    "RETURN_NO_RESPONSE": "No response from server when attempting return.",
    "AUTO_ATTR_VALUE_pickup": "Retirar",
    "AUTO_barcode_type": "Return by barcode of",
    "AUTO_in_bresv": "Patron has returned these resources today:",
    "RESERVATIONS_ERROR": "Error communicating with server (asking for reservations):",
    "AUTO_patron": "Patron",
    "COPY_ALERT": "${0}:\n${1}\n\nDo you wish to process it anyway?",
    "AUTO_resource": "Recurso",
    "RETURN_ERROR": "Erro ao comunicar com o servidor(tentando retorno)",
    "AUTO_patron_barcode": "Enter patron barcode:",
    "AUTO_h1": "Reservations Pickup",
    "AUTO_ATTR_VALUE_go": "Go",
    "AUTO_out_bresv": "Patron currently has these reservations out:",
    "AUTO_ready_bresv": "O usu\u00e1rio possui essas reservas prontas para retirar:",
    "RESERVATIONS_NO_RESPONSE": "No response from server when asking for reservations.",
    "AUTO_ATTR_VALUE_reset": "Clear / New Patron",
    "RETURN_SUCCESS": "Return successful.",
    "PICKUP_NO_RESPONSE": "No response from server when attempting pickup.",
    "NOTICE_CHANGE_OF_PATRON": "Note that the resource scanned was out on reservation to a different\npatron than the last resource you scanned.  If this is not\nexpected, stop to examine outstanding reservations for your patron\nor on the resource.",
    "NO_PATRON_BARCODE": "Por favor, digite o c\u00f3digo de barra do cliente.",
    "ADDRESS": "${0}\n${1}\n${2}, ${3} ${4}",
    "SELECT_SOMETHING": "Voc\u00ea n\u00e3o selecionou nenhuma reserva.",
    "AUTO_no_ready_bresv": "Patron has no reservations ready for pickup at this time.",
    "AUTO_return_h1": "Reservations Return"
}