{
    "AUTO_ATTR_VALUE_button_cancel_existing": "Cancel selected",
    "AUTO_ATTR_VALUE_reserve_brsrc": "Reserva selecionada",
    "AUTO_ATTR_VALUE_next": "Pr\u00f3ximo",
    "HERE_ARE_EXISTING_BRESV": "Existing reservations for",
    "AUTO_email_notify": "Send email notification when resource is available for pickup.",
    "ON_FLY_ERROR": "Error attempting to make item a bookable resource:",
    "AUTO_ATTR_VALUE_button_edit_existing": "Edit selected",
    "AUTO_ending_at": "e",
    "AUTO_arbitrary_resource": "Enter the barcode of a cataloged, bookable resource:",
    "NO_BRT_RESULTS": "There are no bookable resource types registered.",
    "AUTO_ATTR_VALUE_reserve_brt": "Reserve Any",
    "AUTO_brt_noncat_only": "Show only non-cataloged bookable resource types",
    "OUTSTANDING_BRESV": "Outstanding reservations for patron",
    "INVALID_TS_RANGE": "You must choose a valid start and end time for the reservation.",
    "AUTO_or": "- Or -",
    "CREATE_BRESV_OK_MISSING_TARGET_WILL_CANCEL": "Since the requested resource could not be targeted, this\nreservation will now be canceled.",
    "ERROR_FETCHING_AOUS": "N\u00e3o foi poss\u00edvel recuperar as configura\u00e7\u00f5es da unidade organizacional.\nEste n\u00e3o \u00e9 um erro fatal, mas voc\u00ea pode entrar\nem contado administrador do sistema.",
    "NEED_EXACTLY_ONE_BRT_PASSED_IN": "N\u00e3o \u00e9 poss\u00edvel reservar m\u00faltiplos tipos de recursos de uma s\u00f3 vez",
    "CXL_BRESV_SUCCESS": "Criada(s) ${0} reserva(s)",
    "UNTARGETED": "None targeted",
    "CREATE_BRESV_SERVER_ERROR": "Erro do servidor ao tentar criar reserva: ",
    "ON_FLY_NO_RESPONSE": "No response from server attempting to make item a bookable resource.",
    "AUTO_patron_barcode": "Reservar para c\u00f3digo de barra do cliente.",
    "NO_EXISTING_BRESV": "Esse usu\u00e1rio n\u00e3o tem reservas existentes neste momento.",
    "GET_BRESV_LIST_ERR": "Erro ao recuperar lista de reservas: ",
    "AUTO_explain_bookable": "To reserve an item that is not yet registered as a bookable resource, find it in the catalog or under <em>Display Item</em>, and select <em>Make Item Bookable</em> or <em>Book Item Now</em> there.",
    "NO_TARG_DIV": "Could not find target div",
    "CREATE_BRESV_SERVER_NO_RESPONSE": "Nenhuma resposta do servidor depois de tentar criar reserva.",
    "AUTO_bresv_grid_type": "Type",
    "AUTO_choose_a_brt": "Choose a Bookable Resource Type",
    "NO_BRA_RESULTS": "Couldn't retrieve booking resource attributes.",
    "AUTO_i_need_this_resource": "Eu preciso desse recurso...",
    "AUTO_bresv_grid_end_time": "End time",
    "BRSRC_NOT_FOUND": "N\u00e3o foi poss\u00edvel localizar esse recurso.",
    "AUTO_starting_at": "Entre",
    "CXL_BRESV_FAILURE2": "Erro ao cancelar reservas:\n",
    "CREATE_BRESV_OK_MISSING_TARGET": "Created ${0} reservation(s), but ${1} of these could not target any resources.\n\nThis means that it won't be possible to fulfill some of these\nreservations until a suitable resource becomes available.",
    "CREATE_BRESV_OK": "Criada(s) ${0} reserva(s)",
    "CREATE_BRESV_LOCAL_ERROR": "Exce\u00e7\u00e3o ao tentar criar reserva: ",
    "GET_BRESV_LIST_NO_RESULT": "No results from server retrieving reservation list.",
    "BRSRC_RETRIVE_ERROR": "Erro ao recuperar recurso: ",
    "AUTO_bresv_grid_resource": "Recurso",
    "WHERES_THE_BARCODE": "Enter a patron's barcode to make a reservation.",
    "AUTO_pickup_lib_selector": "Choose the pickup library for this reservation:",
    "NO_USABLE_BRSRC": "N\u00e3o h\u00e1 recursos para reserva. Ajuste a hora de in\u00edcio de de t\u00e9rmino\nat\u00e9 que um recurso esteja dispon\u00edvel para reserva.",
    "CREATE_BRESV_OK_MISSING_TARGET_BLOCKED_BY_CIRC": "The desired reservation(s) are blocked by circulation(s) with the following due date(s):\n${0}",
    "CXL_BRESV_SELECT_SOMETHING": "Voc\u00ea n\u00e3o selecionou nenhuma reserva para cancelar.",
    "COULD_NOT_RETRIEVE_BRT_PASSED_IN": "Error retrieving booking resource type",
    "CXL_BRESV_FAILURE": "Error canceling reservations; server silent.",
    "ACTOR_CARD_NOT_FOUND": "C\u00f3digo de barra do cliente n\u00e3o encontrado. Por favor, tente novamente.",
    "SELECT_A_BRSRC_THEN": "You have clicked 'Reserve Selected', but nothing is selected!\n\nYou must select a resource from the large box above.\n\n***  If resources that you would select are highlighted in RED, ***\nthese items are not available during the requested time; if\npossible, choose another resource or change the reservation time.",
    "GET_PATRON_NO_RESULT": "No server response after attempting to look up patron by barcode.",
    "AUTO_with_these_attr": "Com esses atributos:",
    "ANY": "ANY",
    "AUTO_bresv_grid_start_time": "Start time"
}