{
    "SOURCE_SETUP_ALL_AVAIL_SOURCES": "Kaikki lainattavissa olevat l\u00e4hteet",
    "TEMPLATE_CONF_SELECT_CANCEL": "Valitse arvo tai peruuta:",
    "OPERATORS_ILIKE": "Sis\u00e4lt\u00e4\u00e4 osuvan alijonon (kirjainten koosta riippumatta)",
    "FILTERS_LABEL_NULL_BLANK": "On NULL tai tyhj\u00e4",
    "OPERATORS_LIKE": "Sis\u00e4lt\u00e4\u00e4 osuvan alijonon",
    "WIDGET_MONTHS": "Kuukausi/kuukaudet",
    "LINK_NULLABLE_RIGHT": "Emoelementti",
    "TFORMS_LABEL_AVERAGE": "Keskim\u00e4\u00e4rin",
    "TEMPLATE_CONF_CONFIRM_STATE": "Napsauta OK = TOSI tai Peruuta = EP\u00c4TOSI.",
    "OPERATORS_EQUALS": "Vastaa",
    "FILTERS_LABEL_BETWEEN": "V\u00e4lill\u00e4",
    "OPERATORS_IN_LIST": "Luettelossa",
    "TEMPLATE_CONF_NOT_IN": "Kentt\u00e4 ei vastaa arvoa luettelossa (pilkulla erotettu):",
    "OPERATORS_NOT_IN_LIST": "Ei luettelossa",
    "FILTERS_LABEL_NOT_IN": "Ei luettelossa",
    "FOLDERS_OUTPUT": "Tuloste",
    "FILTERS_LABEL_GT_TIME": "J\u00e4lkeen (p\u00e4iv\u00e4ys/aika)",
    "OPERATORS_IS_NULL": "On NULL",
    "TEMPLATE_CONF_CONFIRM_SAVE": "Nimi : ${0}\nKuvaus: ${1}\nTallennetaanko pohja?",
    "OPERATORS_IS_NOT_NULL": "Ei ole NULL",
    "TEMPLATE_CONF_CONFIRM_RESET": "Olet jo lis\u00e4nnyt kent\u00e4n [${0}]\n l\u00e4hteest\u00e4 [${1}]. Napsauta OK, jos\nhaluat tyhjent\u00e4\u00e4 kent\u00e4n.",
    "OPERATORS_GT_EQUAL": "Suurempi tai yht\u00e4 suuri kuin",
    "TRANSFORMS_MONTH_TRUNC": "Vuosi + kuukausi",
    "FILTERS_LABEL_NULL": "On NULL",
    "REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Sy\u00f6t\u00e4 raporttikansio",
    "OPERATORS_GT_TIME": "J\u00e4lkeen (p\u00e4iv\u00e4ys/aika)",
    "TRANSFORMS_YEAR_TRUNC": "Vuosi",
    "TRANSFORMS_UPPER": "Isot kirjaimet",
    "FOLDERS_REPORTS": "Raportit",
    "LINK_NULLABLE_LEFT": "Lapsi",
    "TRANSFORMS_COUNT_DISTINCT": "Laske erikseen",
    "FOLDER_WINDOW_COLNAME_SELECT": "Valitse",
    "TRANSFORMS_FIRST": "Ensimm\u00e4inen arvo",
    "TFORMS_LABEL_LOWER": "Pienet kirjaimet",
    "TFORMS_LABEL_COUNT": "Lukum\u00e4\u00e4r\u00e4",
    "TRANSFORMS_HOD": "P\u00e4iv\u00e4n tunti",
    "WIDGET_RELATIVE_DATE": "Suhteellinen p\u00e4iv\u00e4",
    "FILTERS_LABEL_LESS_THAN": "Pienempi kuin",
    "TEMPLATE_CONF_SUCCESS_SAVE": "Raporttipohja ${0} tallennettiin onnistuneesti.",
    "TFORMS_LABEL_MOY": "Vuoden kuukausi",
    "FILTERS_LABEL_EQ_ANY": "Vastaa mit\u00e4 tahansa",
    "TRANSFORMS_MAX": "Enint.",
    "TRANSFORMS_MIN": "V\u00e4h.",
    "TRANSFORMS_SUM": "Summa",
    "TRANSFORMS_FIRST_WORD": "Ensimm\u00e4inen yht\u00e4jaksoinen merkkijono ilman v\u00e4lily\u00f6ntej\u00e4",
    "TRANSFORMS_MONTHS_AGO": "Kuukautta sitten",
    "SOURCE_BROWSE_AGGREGATE": "Yhteenkokouma",
    "TFORMS_LABEL_DATE": "P\u00e4iv\u00e4ys",
    "WIDGET_YEARS": "Vuosi/vuodet",
    "FILTERS_LABEL_LT_TIME": "Ennen (p\u00e4iv\u00e4ys/aika)",
    "TRANSFORMS_COUNT": "Lukum\u00e4\u00e4r\u00e4",
    "WIDGET_REAL_DATE": "Todellinen p\u00e4iv\u00e4ys",
    "OPERATORS_LT_TIME": "Ennen (p\u00e4iv\u00e4ys/aika)",
    "TFORMS_LABEL_MAX": "Enint.",
    "REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Please change the report name",
    "TEMPLATE_CONF_FALSE": "Ep\u00e4tosi",
    "TEMPLATE_CONF_BARE": "Pelkk\u00e4",
    "TRANSFORMS_LAST": "Viimeisin arvo",
    "TFORMS_LABEL_MIN": "V\u00e4h.",
    "REPORT_EDITOR_REPORT_FOLDERS": "Raporttikansiot",
    "TEMPLATE_CONF_EQUALS": "Vastaa",
    "REPORT_EDITOR_OUTPUT_FOLDERS": "Tulostekansiot",
    "FILTERS_LABEL_NOT_BETWEEN": "Ei v\u00e4lill\u00e4",
    "TRANSFORMS_QOY": "Vuosinelj\u00e4nnes",
    "REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Sy\u00f6t\u00e4 tulostekansio",
    "FILTERS_LABEL_GREATER_THAN": "Suurempi kuin",
    "FILTERS_LABEL_NE_ANY": "Ei vastaa yht\u00e4\u00e4n",
    "SOURCE_BROWSE_NON_AGGREGATE": "Ei-yhteenkokouma",
    "OPERATORS_NE_ANY": "Ei vastaa yht\u00e4\u00e4n",
    "TRANSFORMS_AVERAGE": "Keskim\u00e4\u00e4rin",
    "FOLDERS_TEMPLATES": "Raporttipohjat",
    "TFORMS_LABEL_DAY_NAME": "P\u00e4iv\u00e4n nimi",
    "WIDGET_DAYS": "P\u00e4iv\u00e4(\u00e4)",
    "TRANSFORMS_ROUND": "Py\u00f6rist\u00e4",
    "FOLDERS_TEMPLATE": "Raporttipohja",
    "TRANSFORMS_HOUR_TRUNC": "Tunti",
    "TFORMS_LABEL_HOUR_TRUNC": "Tunti",
    "TRANSFORMS_MOY": "Vuoden kuukausi",
    "LINK_NULLABLE_NONE": "Ei yht\u00e4\u00e4n",
    "RPT_BUILDER_CONFIRM_SAVE": "Nimi : ${0}\nKuvaus: ${1}\nTallennetaanko pohja?",
    "TFORMS_LABEL_DOY": "Vuoden p\u00e4iv\u00e4",
    "TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Change the field hint to:",
    "TRANSFORMS_DATE": "P\u00e4iv\u00e4ys",
    "FOLDERS_REPORT": "Raportti",
    "TFORMS_LABEL_DOW": "Viikonp\u00e4iv\u00e4",
    "FILTERS_LABEL_LT_EQUAL": "Pienempi tai yht\u00e4 suuri kuin",
    "TFORMS_LABEL_INT": "J\u00e4t\u00e4 ylim\u00e4\u00e4r\u00e4iset desimaalit pois",
    "OPERATORS_GTE_TIME": "Ajankohtana tai j\u00e4lkeen (p\u00e4iv\u00e4ys/aika)",
    "TFORMS_LABEL_DOM": "Kuukauden p\u00e4iv\u00e4",
    "FOLDER_WINDOW_COLNAME_NONE": "Ei yht\u00e4\u00e4n",
    "REPORT_EDITOR_ENTER_NAME_ALERT": "Sy\u00f6t\u00e4 raportin nimi",
    "OPERATORS_LT_EQUAL": "Pienempi tai yht\u00e4 suuri kuin",
    "TFORMS_LABEL_MONTHS_AGO": "Kuukautta sitten",
    "TFORMS_LABEL_FIRST_WORD": "Ensimm\u00e4inen yht\u00e4jaksoinen merkkijono ilman v\u00e4lily\u00f6ntej\u00e4",
    "FOLDER_WINDOW_REPORT_OUTPUT": "Raportin tuloste: ${0}",
    "FILTERS_LABEL_GTE_TIME": "Ajankohtana tai j\u00e4lkeen (p\u00e4iv\u00e4ys/aika)",
    "TFORMS_LABEL_FIRST": "Ensimm\u00e4inen arvo",
    "TRANSFORMS_AGE": "Ik\u00e4",
    "FILTERS_LABEL_LIKE": "Sis\u00e4lt\u00e4\u00e4 osuvan alijonon",
    "TEMPLATE_CONF_TRUE": "Tosi",
    "SOURCE_SETUP_CONFIRM_EXIT": "Olet aloittanut raporttipohjan luomisen!\nUudet aloitusl\u00e4hteen valinta tuhoaa nykyisen raporttipohjan ja aloittaa alusta. OK?",
    "TRANSFORMS_QUARTERS_AGO": "Nelj\u00e4nnest\u00e4 sitten",
    "TFORMS_LABEL_MONTH_TRUNC": "Vuosi + kuukausi",
    "TEMPLATE_CONF_IN": "Kentt\u00e4 vastaa yht\u00e4 arvoa luettelosta (pilkuilla erotettu):",
    "FILTERS_LABEL_ILIKE": "Sis\u00e4lt\u00e4\u00e4 osuvan alijonon (kirjainten koosta riippumatta)",
    "FILTERS_LABEL_NOT_NULL": "Ei ole NULL",
    "TEMPLATE_CONF_NO_MATCH": "Kentt\u00e4 ei vastaa arvoa luettelossa (pilkulla erotettu):",
    "TFORMS_LABEL_UPPER": "Isot kirjaimet",
    "TRANSFORMS_SUBSTRING": "Alijono",
    "FILTERS_LABEL_GT_EQUAL": "Suurempi tai yht\u00e4 suuri kuin",
    "TEMPLATE_CONF_RAW_DATA": "Raakadata",
    "TFORMS_LABEL_HOD": "P\u00e4iv\u00e4n tunti",
    "FILTERS_LABEL_NOT_NULL_BLANK": "Ei ole NULL tai tyhj\u00e4",
    "TFORMS_LABEL_SUM": "Summa",
    "LINK_NULLABLE_DEFAULT": "Oletus",
    "FILTERS_LABEL_IN": "Luettelossa",
    "TFORMS_LABEL_AGE": "Ik\u00e4",
    "FOLDER_WINDOW_CHANGE_FOLDERS": "Muuta kansioita",
    "TRANSFORMS_LOWER": "Pienet kirjaimet",
    "TRANSFORMS_MONTH_NAME": "Kuukauden nimi",
    "TRANSFORMS_DOW": "Viikonp\u00e4iv\u00e4",
    "TEMPLATE_CONF_PROMPT_CHANGE": "Muuta sarakkeen otsikoksi: ${0}",
    "OPERATORS_NOT_BETWEEN": "Ei v\u00e4lill\u00e4",
    "TRANSFORMS_DOY": "Vuoden p\u00e4iv\u00e4",
    "REPORT_EDITOR_INVALID_DATE_ALERT": "virheellinen aloitusp\u00e4iv\u00e4 - VVVV-KK-PP",
    "TRANSFORMS_BARE": "Raakadata",
    "TRANSFORMS_DOM": "Kuukauden p\u00e4iv\u00e4",
    "TFORMS_LABEL_MONTH_NAME": "Kuukauden nimi'",
    "OPERATORS_EQ_ANY": "Vastaa mit\u00e4 tahansa",
    "TFORMS_LABEL_ROUND": "Py\u00f6rist\u00e4",
    "OPERATORS_GREATER_THAN": "Suurempi kuin",
    "SOURCE_SETUP_CORE_SOURCES": "Ydinl\u00e4hteet",
    "TFORMS_LABEL_LAST": "Viimeisin arvo",
    "FILTERS_LABEL_EQUALS": "Vastaa",
    "FOLDER_WINDOW_COLNAME_ALL": "Kaikki",
    "TFORMS_LABEL_RAW_DATA": "Raakadata",
    "TFORMS_LABEL_COUNT_DISTINCT": "Laske erikseen",
    "TFORMS_LABEL_FIRST5": "Ensimm\u00e4iset 5 merkki\u00e4 (postinumerosta)",
    "TEMPLATE_CONF_NOT_BETWEEN": "Kent\u00e4n arvo ei ole v\u00e4lill\u00e4 (pilkuilla erotettu):",
    "TRANSFORMS_INT": "J\u00e4t\u00e4 ylim\u00e4\u00e4r\u00e4iset desimaalit pois",
    "FILTERS_LABEL_LSE_TIME": "Ajankohtana tai ennen (p\u00e4iv\u00e4ys/aika)",
    "TRANSFORMS_DAY_NAME": "P\u00e4iv\u00e4n nimi",
    "FOLDER_WINDOW_SELECT_ITEM": "Valitse kohde luettelosta",
    "TRANSFORMS_FIRST5": "Ensimm\u00e4iset 5 merkki\u00e4 (postinumerosta)",
    "OPERATORS_LTE_TIME": "Ajankohtana tai ennen (p\u00e4iv\u00e4ys/aika)",
    "TEMPLATE_CONF_DEFAULT": "Arvo ${0}:",
    "TFORMS_LABEL_YEAR_TRUNC": "Vuosi",
    "TRANSFORMS_WOY": "Vuoden viikko",
    "TFORMS_LABEL_WOY": "Vuoden viikko",
    "TFORMS_LABEL_QUARTERS_AGO": "Nelj\u00e4nnest\u00e4 sitten",
    "TEMPLATE_CONF_BOOLEAN_VALUE": "Boolean-arvo",
    "OPERATORS_NOT_NULL_BLANK": "Ei ole NULL tai tyhj\u00e4",
    "OPERATORS_NULL_BLANK": "On NULL tai tyhj\u00e4",
    "TEMPLATE_CONF_BETWEEN": "Kent\u00e4n arvo on v\u00e4lill\u00e4 (pilkuilla erotettu):",
    "TFORMS_LABEL_QOY": "Vuosinelj\u00e4nnes",
    "WIDGET_QUARTERS": "Nelj\u00e4nnes/nelj\u00e4nnekset",
    "OPERATORS_LESS_THAN": "Pienempi kuin",
    "OPERATORS_BETWEEN": "V\u00e4lill\u00e4"
}