{
    "CHOOSE_FILTER_TO_LOAD": "Elegir conjuntos de filtros para cargar",
    "OPERATOR_NE": "no es",
    "OPERATOR_BETWEEN": "est\u00e1 entre",
    "OPERATOR_GTE": "es mayor que o igual a",
    "OPERATOR_LT": "Es menos que",
    "OPERATOR_IS_NULL": "es nulo",
    "LOAD_FILTERS": "Filtros de carga",
    "ADD_ROW": "A\u00f1adir fila",
    "EMPTY_LIST": "No se puede compilar busqueda de filtro.",
    "APPLY": "Aplicar",
    "OPERATOR_GT": "es mayor que",
    "OPERATOR_EQ": "es",
    "OPERATOR_IN": "est\u00e1 en el conjunto",
    "OPERATOR_NOT_IN": "no est\u00e1 en el conjunto",
    "OPERATOR_LTE": "es menos que o igual a",
    "EMPTY_CASE_COMPACT": "A\u00f1adir filas para filtrar resultados",
    "EMPTY_CASE": "A\u00f1adir filas para filtrar los resultados, o simplemente haga clic en aplicar para ver los resultados sin filtrar.",
    "OPERATOR_LIKE": "es como",
    "CANCEL": "Cancelar",
    "NAME_SAVED_FILTER_SET": "Introduzca un nombre para el conjunto de filtro guardado:",
    "OPERATOR_IS_NOT_NULL": "no es nulo",
    "OPERATOR_NOT_BETWEEN": "no est\u00e1 entre",
    "OPERATOR_NOT_LIKE": "no es como",
    "SAVE_FILTERS": "Guardar Filtros",
    "NEED_NAME": "Debe introducir un nombre para los filtros guardados",
    "DEFAULT_DIALOG_TITLE": "Filtrar los resultados"
}