{
    "and": "Y",
    "sort": "Ordenar Axis",
    "bib_level": "Nivel bibliogr\u00e1fico",
    "less": "...Menos",
    "item_form": "Forma",
    "site": "Sitio",
    "filters": "Filtros",
    "notcontains": "No contiene",
    "statuses": "Estatus",
    "before": "Publicado anteriormente",
    "new_facet": "Nueva Faceta",
    "lit_form": "Forma literaria",
    "faceted_searches": "Facetas",
    "contains": "Contiene",
    "audience": "Audiencia",
    "filter_default": "- Seleccione un filtro -",
    "metabib": "Metarecord Buscar",
    "basic": "B\u00e1sico",
    "new_modifier": "Nuevo Modificador",
    "staff": "B\u00fasqueda de personal",
    "classed_searches": "B\u00fasquedas clasificadas",
    "more": "M\u00e1s..",
    "available": "Disponible",
    "new_filter": "Nuevo filtro",
    "format": "Tipo y Forma",
    "after": "Publicado posteriormente",
    "ascending": "Ordenaci\u00f3n Ascendente",
    "descending": "Ordenaci\u00f3n Descendente",
    "modifier_default": "- Seleccionar un Modificador -",
    "during": "En publicaci\u00f3n",
    "exact": "Coincidencias exactas",
    "between": "Publicado entre",
    "advanced": "Avanzado",
    "modifiers": "Modificadores",
    "perform_search": "\u00a1Adelante!",
    "remove": "Eliminar",
    "item_type": "Tipo",
    "depth": "Profundidad de b\u00fasqueda",
    "vr_format": "Formato de Grabaci\u00f3n de video",
    "or": "O"
}