{
    "CHOOSE_FILTER_TO_LOAD": "Valitse ladattava suodatinjoukko",
    "OPERATOR_NE": "ei ole",
    "OPERATOR_BETWEEN": "on v\u00e4lill\u00e4",
    "OPERATOR_GTE": "on enemm\u00e4n tai yht\u00e4 paljon kuin",
    "OPERATOR_LT": "on v\u00e4hemm\u00e4n kuin",
    "OPERATOR_IS_NULL": "on m\u00e4\u00e4ritt\u00e4m\u00e4t\u00f6n",
    "LOAD_FILTERS": "Lataa suodatin",
    "ADD_ROW": "Lis\u00e4\u00e4 rivi",
    "EMPTY_LIST": "Suodattimen luonti ep\u00e4onnistui. Tyhj\u00e4 lista ei ole sallitty.",
    "APPLY": "Suodata",
    "OPERATOR_GT": "on enemm\u00e4n kuin",
    "OPERATOR_EQ": "on",
    "OPERATOR_IN": "kuuluu joukkoon",
    "OPERATOR_NOT_IN": "ei kuulu joukkoon",
    "OPERATOR_LTE": "on v\u00e4hemm\u00e4n tai yht\u00e4 paljon kuin",
    "EMPTY_CASE_COMPACT": "Lis\u00e4\u00e4 rivej\u00e4 suodatintuloksiin.",
    "EMPTY_CASE": "Lis\u00e4\u00e4 rivej\u00e4 suodatintuloksiin, tai valitse Suodata n\u00e4hd\u00e4ksesi kaikki tulokset.",
    "OPERATOR_LIKE": "on kuten",
    "CANCEL": "Peruuta",
    "NAME_SAVED_FILTER_SET": "Sy\u00f6t\u00e4 tallennetun suodattimen nimi:",
    "OPERATOR_IS_NOT_NULL": "ei ole m\u00e4\u00e4ritt\u00e4m\u00e4t\u00f6n",
    "OPERATOR_NOT_BETWEEN": "ei ole v\u00e4lill\u00e4",
    "OPERATOR_NOT_LIKE": "ei ole kuten",
    "SAVE_FILTERS": "Tallenna suodatin",
    "NEED_NAME": "Sinun t\u00e4ytyy antaa suodatinjoukolle nimi.",
    "DEFAULT_DIALOG_TITLE": "Suodantulokset"
}