{
    "and": "JA",
    "sort": "Lajitteluakseli",
    "bib_level": "Bibliografinen taso",
    "less": "...V\u00e4hemm\u00e4n",
    "item_form": "Muoto",
    "site": "Sivusto",
    "filters": "Suodattimet",
    "notcontains": "Ei sis\u00e4ll\u00e4",
    "statuses": "Statukset",
    "before": "Julkaistu ennen",
    "new_facet": "Uusi fasetti",
    "lit_form": "Kirjallisuudenlaji",
    "faceted_searches": "Fasetit",
    "contains": "Sis\u00e4lt\u00e4\u00e4",
    "audience": "Yleis\u00f6",
    "filter_default": "-- Valitse suodatin --",
    "metabib": "Haku metatietueesta",
    "basic": "Perus",
    "new_modifier": "Uusi m\u00e4\u00e4rite",
    "staff": "Virkailijahaku",
    "classed_searches": "Luokitetut haut",
    "more": "Lis\u00e4\u00e4...",
    "available": "Lainattavissa",
    "new_filter": "Uusi suodatin",
    "format": "Tyyppi ja muoto",
    "after": "Julkaistu j\u00e4lkeen",
    "ascending": "Nouseva lajittelu",
    "descending": "Laskeva lajittelu",
    "modifier_default": "-- Valitse m\u00e4\u00e4rite --",
    "during": "Julkaistu",
    "exact": "Vastaa t\u00e4ysin",
    "between": "Julkaistu v\u00e4lisen\u00e4 aikana",
    "advanced": "Edistynyt",
    "modifiers": "M\u00e4\u00e4ritteet",
    "perform_search": "Hae!",
    "remove": "Poista",
    "item_type": "Tyyppi",
    "depth": "Hakusyvyys",
    "vr_format": "Videotallenteen muoto",
    "or": "TAI"
}