{
    "NO_LID_TO_CLAIM": "Et ole valinnut yhdenk\u00e4\u00e4n tilausnimekkeen tietoja reklamointia varten.",
    "LI_BATCH_UPDATE": "Tilausnimekkeiden er\u00e4p\u00e4ivitys",
    "PO_ALREADY_ACTIVATED": "Aktivoitu",
    "VENDOR_SAYS_PREPAY_NOT_NEEDED": "Tietueiden mukaan valittu myyj\u00e4 ei v\u00e4ltt\u00e4m\u00e4tt\u00e4 vaadi ennakkomaksua.\nVaaditaanko ennakkomaksu siit\u00e4 huolimatta?",
    "INVOICE_COPY_COUNT_INFO": "T\u00e4ll\u00e4 laskulla olevista niteist\u00e4 vastaanotettu: ${0} / ${1}.",
    "DELETE_LI_COPIES_CONFIRM": "Taulukosta poistetaan viimeiset ${0} kappaletta. Jatketaanko?",
    "CHANGE_CLAIM_POLICY": "Muuta reklamaatiok\u00e4yt\u00e4nt\u00f6j\u00e4",
    "ALERT_UNSELECTED": "Sinun on valittava varoituskoodi.",
    "NUM_CLAIMS_EXISTING": "Reklamoidut (yhteens\u00e4 ${0})",
    "FINALIZE_PO": "Finalize this blanket PO?\nThis will disencumber all blanket charges and mark the PO as received",
    "DFA_TIP": "<strong>K\u00e4ytt\u00f6\u00f6nottaja</strong>: ${0}<br /><strong>Aika</strong>: ${1}",
    "CREATE_PO_INVALID": "Tilauksessa on oltava tilaaja ja toimittaja.",
    "INVOICE_NUMBER": "Lasku #${0}",
    "ACTIVATE_VQBR_PROCESSED": "Vandelay Records Processed: ${0}",
    "PO_CANCEL_CONFIRM": "Haluatko VARMASTI perua t\u00e4m\u00e4n tilauksen?",
    "ACQ_SEARCH_CLASS_ABBR_acqinv": "I",
    "FUND_LIST_ROLLOVER_SUMMARY": "Varojen karttuminen ja aiemmin k\u00e4ytt\u00e4m\u00e4tt\u00f6mien varojen yhteenveto tilivuodelle ${0}",
    "NO_LI_TO_CLAIM": "Et ole valinnut yht\u00e4\u00e4n nimikett\u00e4 reklamointia varten.",
    "INVOICE_CONFIRM_ENTRY_DETACH": "Poistetaanko laskulta $${0} veloitus niteest\u00e4 '${1}, ${2} [${3}]?",
    "PO_FUND_WARNING_CONFIRM": "Oletko varma? Huomasitko varoituksen: Sidottu summa ylitt\u00e4\u00e4 saldon?",
    "NOT_RECVD": "Ei vastaanotettu",
    "UNRECEIVE_LID": "Haluatko varmasti merkit\u00e4 t\u00e4m\u00e4n kopion EI-vastaanotetuksi?",
    "INVOICE_IDENT_COLLIDE": "Jollain toisella laskulla on sama toimittaja ja laskutunnus.",
    "INVOICE_ITEM_DETAILS": "${0} <br/> ${1} <br/> ${2}. <br/> Arvioitu hinta: $${3}. <br/> Nimikkeen ID: ${4} <br/> Tilaus: ${5} <br/> Tilausp\u00e4iv\u00e4: ${6}",
    "PO_ACTIVATING": "Activating purchase order...",
    "PO_CHECKING": "[Hetkinen...]",
    "YES": "Kyll\u00e4",
    "INVOICE_EXTRA_COPIES": "Yrit\u00e4t luoda laskua <b>${0}</b> useammasta kappaleesta kuin alkuper\u00e4isess\u00e4 tilauksessa. <br/><br/>Jos haluat lis\u00e4t\u00e4 n\u00e4m\u00e4 nimekkeet alkuper\u00e4iseen tilaukseen, valitse tili ja sen j\u00e4lkeen 'Lis\u00e4\u00e4 uusia nimekkeit\u00e4' alla. <br/>Kun olet tallentanut laskun, voit muokata ja tuoda uudet kappaleet nimikkeiden tietosivulta.",
    "ADD_LI_TO_PO_BAD_LI_STATE": "Valittu nimeke ei ole sellaisessa tilassa, ett\u00e4 sen voisi lis\u00e4t\u00e4 tilaukseen",
    "CANCEL_REASON": "Perumissyy",
    "ACTIVATE_BIBS_PROCESSED": "Bib Records Merged/Imported: ${0}",
    "RECVD": "Vastaanotettu",
    "EXPORT_SHORT_LIST": "Kaikilla valituilla niteill\u00e4 ei ollut m\u00e4\u00e4ritett\u00e4 '${0}'.\nValitse OK, jos haluat tallentaa arvot, jotka l\u00f6ydettiin.",
    "LOAD_TERMS_FIRST": "Et voi hakea tietueita, ennen kuin olet ladannut CSV-tiedoston,\njoka sis\u00e4lt\u00e4\u00e4 bibliografiset tunnukset ensimm\u00e4isess\u00e4 sarakkeessa.",
    "PRINT": "Tulosta",
    "ACTIVATE_LID_PROCESSED": "ACQ Copies Processed: ${0}",
    "PO_NAME_OPTIONAL": "${0} (optional)",
    "JUST_NOW": "Juuri nyt",
    "LI_CREATING_ASSETS": "Creating bib, call number, and copy records...",
    "ACQ_SEARCH_CLASS_ABBR_acqlid": "LID",
    "ACQ_SEARCH_CLASS_ABBR_acqlia": "LIA",
    "PO_WARNING_NO_BLOCK_ACTIVATION": "Kyll\u00e4; sidottu summa ${0} (${1}) ylitt\u00e4isi varoitusrajan.",
    "CONFIRM_FUNDS_AT_STOP": "Yhden tai useamman tilin saldo on alle pys\u00e4ytysrajan.\nEt ehk\u00e4 pysty aktivoimaan n\u00e4it\u00e4 tilauksia.\nJatketaanko?",
    "LID_CANCEL_CONFIRM": "Haluatko VARMASTI perua t\u00e4m\u00e4n niteen?",
    "CONFIRM_LI_ALERT": "Nimikkeelle \"${0}\" on asetettu huomautus:\n\n${1}\n${2}\n${3}\nValitse OK, jos haluat huomioida t\u00e4m\u00e4n varoituksen.",
    "CONFIRM_FUNDS_AT_WARNING": "Yhden tai useamman valitun tilin saldo on alle varoitusrajan.\nJatketaanko?",
    "VENDOR_PUBLIC": "MYYJ\u00c4 JULKINEN",
    "INVOICE_CONFIRM_ITEM_DELETE": "Poistetaanko t\u00e4m\u00e4 $${0} '${1}' veloitus laskulta?",
    "DUPE_PO_NAME_MSG": "This name is already in use by another PO",
    "ROLLBACK_PO_RECEIVE_CONFIRM": "Kaikkien t\u00e4m\u00e4n tilauksen niteiden vastaanotto perutaan.\n\nJatketaanko?",
    "UR_FILTER_USER": "Sy\u00f6t\u00e4 asiakastunnus (tai j\u00e4t\u00e4 tyhj\u00e4ksi, jos et halua k\u00e4ytt\u00e4\u00e4 suodatinta):",
    "FUND_LIST_ROLLOVER_SUMMARY_ROLLOVER_AMOUNT": "<b>$${1}</b> k\u00e4ytt\u00e4m\u00e4t\u00f6nt\u00e4 rahaa siirretty tilivuodelle ${0} valittuihin toimipisteisiin",
    "EXPORT_SAVE_DIALOG_TITLE": "Tallenna kenttien arvot tiedostoon",
    "PO_STOP_BLOCKS_ACTIVATION": "Ei; sidottu summa ${0} (${1}) ylitt\u00e4isi pys\u00e4ytysrajan.",
    "UR_FILTER_LINEITEM": "Sy\u00f6t\u00e4 nimikkeen tunnus (tai j\u00e4t\u00e4 tyhj\u00e4ksi, jos et halua k\u00e4ytt\u00e4\u00e4 suodatinta):",
    "UR_CANCEL_CONFIRM": "Haluatko VARMASTI perua t\u00e4m\u00e4n hankintatoiveen?",
    "PREPAYMENT_REQUIRED_REMINDER": "T\u00e4m\u00e4 tilaus edellytt\u00e4\u00e4 ennakkomaksua. Haluatko varmasti aktivoida sen?",
    "SELECT_SEARCH_FIELD": "Valitse hakukentt\u00e4",
    "LIBRARY_INITIATED": "Kirjaston aloitteesta",
    "CONFIRM_DELETE_MAPPING": "Haluatko varmasti poistaa t\u00e4m\u00e4n avainsanan t\u00e4st\u00e4 tilist\u00e4?",
    "COULD_NOT_CREATE_MAPPING": "Tilin merkitseminen avainsanalla ep\u00e4onnistui.",
    "EXPORT_EMPTY_LIST": "M\u00e4\u00e4ritteen '${0}' arvoja ei l\u00f6ytynyt.",
    "DFA_NOT_ALL": "Kaikkia jakelukaavojen sovelluksia ei voitu tallentaa.",
    "INVOICE_ITEM_PO_DETAILS": "<b>${0}</b><br/><a href='${1}/acq/po/view/${2}'>PO #${3} ${4}</a><br/>Yhteenlaskettu kustannusarvio: $${5}",
    "ONE_LI_ATTR_SEARCH_AT_A_TIME": "Et voi sy\u00f6tt\u00e4\u00e4 ominaisuushakua ja etsi\u00e4 samanaikaisesti ladattua termitiedostoa.",
    "ITS_YOU": "Sin\u00e4",
    "OUT_OF_COPIES": "Olet ottanut jakelukaavat k\u00e4ytt\u00f6\u00f6n kaikille niteille.",
    "NO_PO_RESULTS": "Ei tuloksia",
    "ACTIVATE_DEBITS_ACCRUED_PROCESSED": "Debits Encumbered: ${0}",
    "NO": "Ei",
    "NEW_INVOICE": "Uusi lasku",
    "UNRECEIVE_LI": "Haluatko varmasti merkit\u00e4 t\u00e4m\u00e4n nimikkeen EI-vastaanotetuksi?",
    "APPLY": "Hyv\u00e4ksy",
    "UNNAMED": "Nime\u00e4m\u00e4t\u00f6n",
    "INVOICE_ITEM_PO_LABEL": "<b>${0}</b><br/><a href='${1}/acq/po/view/${2}'>PO #${3} ${4}</a><br/>Yhteenlaskettu kustannusarvio: $${5}",
    "PO_ACTIVATED_ON": "Aktivoitu ${0}",
    "LI_ATTR_SEARCH_TOO_LARGE": "Tiedosto on liian suuri t\u00e4lle toiminnolle.",
    "LI_ATTR_SEARCH_CHOOSE_FILE": "Valitse tiedosto hakuehdoilla",
    "NO_LI_GENERAL": "Et ole valinnut yht\u00e4\u00e4n (sopivaa) tilausnimekett\u00e4.",
    "ACTIVATE_COPIES_PROCESSED": "Real Copies Processed: ${0}",
    "ROLLBACK_LI_RECEIVE_CONFIRM": "Kaikkien t\u00e4m\u00e4n tilauksen nimekkeiden vastaanotto perutaan.\n\nJatketaanko?",
    "NO_LI_TO_UPDATE": "Et ole valinnut yht\u00e4\u00e4n tilausnimekett\u00e4 p\u00e4ivityst\u00e4 varten.",
    "EXPLAIN_DFA_MGMT": "Poistetaanko t\u00e4m\u00e4n jakelukaavan k\u00e4yt\u00f6n tietue?",
    "FUND_NOT_YET_LOADED": "Tili\u00e4 ei viel\u00e4 ole ladattu. Yrit\u00e4 tulla my\u00f6hemmin takaisin t\u00e4h\u00e4n n\u00e4ytt\u00f6\u00f6n.",
    "NO_FIND_INVOICE": "Laskua ei l\u00f6ydy.\nHuomaa, ett\u00e4 Laskun #-kentt\u00e4 erottelee isot ja pienet kirjaimet.",
    "PO_COULD_ACTIVATE": "Kyll\u00e4.",
    "DEL_LI_FROM_PO": "Nide on jo tilattu! Jos poistat sen nyt, sill\u00e4 ei ole mit\u00e4\u00e4n vaikutusta myyj\u00e4lle l\u00e4hteneeseen tilaukseen. Jos poistat niteen, j\u00e4rjestelm\u00e4\u00e4n tallentuvat tilauksen tiedot eiv\u00e4t v\u00e4ltt\u00e4m\u00e4tt\u00e4 vastaa todellisuutta. Haluatko varmasti tehd\u00e4 t\u00e4m\u00e4n?",
    "XUL_RECORD_DETAIL_PAGE": "Tietueen tiedot",
    "INVOICES": "Laskut",
    "PO_HEADING_ERROR": "Virtuaalisen yhdistetyn tilauksen luomisessa ilmeni odottamaton ongelma",
    "VENDOR_SAYS_PREPAY_NEEDED": "Tietueiden mukaan valittu myyj\u00e4 vaatii ennakkomaksun.\nJatketaanko t\u00e4t\u00e4 tilausta ilman vaadittua ennakkomaksua siit\u00e4 huolimatta?",
    "INVOICE_CONFIRM_PRORATE": "Jaetaanko maksut suhteellisesti?\n\nMy\u00f6hemm\u00e4t muutokset laskuun, jotka vaikuttaisivat suhteellisesti jaettuihin osuuksiin, tulee ratkaista manuaalisesti.",
    "CANCELED": "Peruttu",
    "LINEITEM_SUMMARY": "<div class='acq-lineitem-summary'><a href='${19}?focus_li=${10}&source=${22}'>${0}</a>, by ${1} (${2})</div>\n<div class='acq-lineitem-summary-extra'>\n${3} Ordered, ${4} Received, ${7} Invoiced, ${8} Claimed, ${9} Cancelled, ${23} Delayed</div>\n<div class='acq-lineitem-summary-extra'>Estimated $${6}, Encumbered $${16}, Paid $${17}</div>\n<div class='acq-lineitem-summary-extra'>\n# ${10} <a style='padding-right: 10px;' class='hidden${20}'  href='${11}/acq/po/view/${12}?focus_li=${10}&source=${22}'>&#x2318; ${13} ${18}</a>\n<a style='padding-right: 10px;' class='hidden${21}' href='${11}/acq/picklist/view/${14}?focus_li=${10}&source=${22}'>&#x2756; ${15}</a></div>",
    "DUPE_PO_NAME_LINK": "View PO",
    "CONFIRM_SPLIT_PO": "Haluatko varmasti jakaa kaikki t\u00e4ss\u00e4 tilauksessa\nolevat nimekkeet erillisiksi tilauksiksi?",
    "RESET_FORMULAE": "Nollaa kaavat",
    "COULD_NOT_DELETE_MAPPING": "Avainsanan poistaminen tilist\u00e4 ep\u00e4onnistui.",
    "FUND_XFER_CONFIRM": "Haluatko varmasti suorittaa t\u00e4m\u00e4n siirron?",
    "ACQ_SEARCH_CLASS_ABBR_jub": "LI",
    "ACTIVATE_LI_PROCESSED": "Lineitems Processed: ${0}",
    "LI_CANCEL_CONFIRM": "Haluatko VARMASTI perua t\u00e4m\u00e4n nimikkeen?",
    "FUND_LIST_ROLLOVER_SUMMARY_FUNDS": "${1} varoja karttunut valituista toimipisteist\u00e4 tilivuonna ${0}",
    "SELECT_AN_LI_ATTRIBUTE": "Sinun on valittava LI-m\u00e4\u00e4rite.",
    "CREATE_PO_ASSETS_CONFIRM": "T\u00e4m\u00e4 luo kirjastoj\u00e4rjestelm\u00e4\u00e4n bibliografisen tietueen sek\u00e4 hyllypaikka- ja nidetietueen t\u00e4lle tilaukselle.\n\nJatketaanko?",
    "FUND_XFER_SAME_SOURCE_AND_DEST": "Siirto ei onnistu. L\u00e4hde- ja kohdetili on sama.",
    "ADD_LI_TO_PO_BAD_PO_STATE": "Valittu tilaus on jo aktivoitu",
    "COPIES_TO_RECEIVE": "Vastaanotettavien niteiden lukum\u00e4\u00e4r\u00e4: ",
    "NO_RESULTS": "Ei tuloksia.",
    "CANCEL": "Peruuta",
    "LI_EXISTING_COPIES": "There are ${0} existing copies for this bibliographic record at this location",
    "LI_FORMAT_ERROR": "Muotoiltujen nimiketietojen hakemisessa ilmeni odottamaton virhe.",
    "ACQ_SEARCH_CLASS_ABBR_acqpo": "PO",
    "ACQ_SEARCH_CLASS_ABBR_acqpl": "SL"
}