{
    "SUCCESS_SAVING_PHYSICAL": "Muutokset kohteen ${0} fyysiseen osoitteeseen tallennettu",
    "CONFIRM_EXIT_CCS": "Yhden tai useamman niteen tilaan on tehty tallentamattomia muutoksia. Tallenna muutokset valitsemalla OK tai hylk\u00e4\u00e4 ne valitsemalla Peruuta.",
    "SURVEY_SAVE_CHANGES": "Tallenna muutokset",
    "ERROR_CREATING_CHILD_AOU": "Alaorganisaatioyksik\u00f6n luominen ep\u00e4onnistui",
    "ERROR_CALLING_METHOD_PPL": "Uuden oikeuden luomismenetelm\u00e4n kutsu ep\u00e4onnistui",
    "TRANSLATION": "K\u00e4\u00e4nn\u00f6s",
    "ERROR_FETCHING_ORGS": "Organisaatioyksik\u00f6n tietojen haku ep\u00e4onnistui",
    "SUCCESS_CREATING_STATUS": "Uusi status luotu kohteelle ${0}",
    "SUCCESS_SAVING_HOLDS": "Kohteen ${0} varausosoitteen muutokset tallennettu",
    "SUCCESS_SAVING_ILL": "Kohteen ${0} ILL-osoitteen muutokset tallennettu",
    "CBHO_NO_LOAD": "Valitun kohteen lataus ep\u00e4onnistui.",
    "STATUS_EDITING": "Muokataan nyt kohdetta ${0}",
    "SUCCESS_SAVING_DATA": "Muutokset tallennettu kohteeseen ${0}",
    "SUCCESS_DELETED_PERM_MAP": "Oikeuksien kartoitus tuhottu",
    "ERROR_SAVING_PERM_DATA": "Oikeustietojen tallennus kohteelle ${0} ep\u00e4onnistui",
    "ERROR_FETCHING_HOLDS": "Varausosoitteen haku kohteelle ${0} ep\u00e4onnistui",
    "HOLDABLE": "Varattavissa",
    "CBHO_FIELD_DISPLAY": "[${0}] ${1}",
    "STATUS_DELETED": "${0} tuhottu",
    "ERROR_CALLING_METHOD_CCS": "Uuden nidestatuksen luomismenetelm\u00e4n kutsu ep\u00e4onnistui",
    "SUCCESS_CREATING_CODE": "Uusi ${0} ${1} luotu",
    "ACQ_DISTRIB_FORMULA_NAME_PROMPT": "Sy\u00f6t\u00e4 uuden kaavan nimi",
    "ERROR_SAVING_DATA": "Kohteen ${0} tietojen tallennus ep\u00e4onnistui",
    "LABEL_NEW_BRANCH": "Uusi sivukirjasto",
    "ERROR_FETCHING_HOURS": "Kohteen ${0} aukioloaikojen haku ep\u00e4onnistui",
    "LABEL_TRANSLATION": "K\u00e4\u00e4nn\u00f6s",
    "ERROR_CREATING_PERMISSION": "Uuden oikeuden luominen ep\u00e4onnistui",
    "LABEL_DESCRIPTION": "Kuvaus",
    "ERROR_SAVING_HOO": "Kohteen ${0} aukioloaikatietojen tallennus ep\u00e4onnistui",
    "SUCCESS_NEW_PERM_MAP": "Uusi oikeuskartta luotu",
    "END_SURVEY": "Lopeta kysely nyt",
    "CONFIRM_UNSAVED_CHANGES": "Yhteen tai useampaan organisaatiotyyppiin on tehty tallentamattomia muutoksia. Tallenna muutokset valitsemalla OK tai hylk\u00e4\u00e4 ne valitsemalla Peruuta.",
    "OPAC_VISIBLE": "OPAC n\u00e4kyviss\u00e4",
    "SURVEY_FOOT_LABEL": "Kysymykset ja vastaukset",
    "ERROR_DELETING": "Kohteen ${0} poistaminen ep\u00e4onnistui",
    "ERROR_FETCHING_TYPES_AOUT": "Organisaatioyksikk\u00f6tyyppien haku ep\u00e4onnistui",
    "CONFIRM_DELETE": "Haluatko varmasti tuhota kohteen ${0}?",
    "ERROR_ORPHANS": "Kohteen ${0} tuhoaminen ei onnistu, sill\u00e4 on viel\u00e4 ${1} kohdetta alaisuudessaan.",
    "LABEL_DEPTH": "Syvyys",
    "LABEL_NEW_TYPE": "Uusi tyyppi",
    "LABEL_VALUE": "Arvo",
    "SUCCESS_CREATING_CHILD_AOU": "Uusi alaorganisaatioyksikk\u00f6 luotu kohteelle ${0}",
    "LABEL_CODE": "Koodi",
    "CBHO_EDITING_EXISTING": "Muokkaat paras-varaus -j\u00e4rjestyst\u00e4 #${0}: ${1}.",
    "CBHO_NEEDS_NAME": "Sy\u00f6t\u00e4 nimi t\u00e4lle j\u00e4rjestykselle.",
    "ERROR_FETCHING_PHYSICAL": "Fyysisen osoitteen haku kohteelle ${0} ep\u00e4onnistui",
    "CONFIRM_EXIT_PPL": "Oikeuksiin on tehty tallentamattomia muutoksia. Tallenna muutokset valitsemalla OK tai hylk\u00e4\u00e4 ne valitsemalla Peruuta.",
    "ERROR_FETCHING_PERMS": "Oikeuksien haku ep\u00e4onnistui",
    "LABEL_NEW_GROUP": "Uusi ryhm\u00e4",
    "SUCCESS_SAVING_HOO": "Aukioloajat p\u00e4ivitetty kohteelle ${0}",
    "ERROR_SAVING_STATUS": "Kohteen ${0} tallennus ei onnistunut",
    "ERROR_SAVING_PHYSICAL": "Kohteen ${0} fyysisten osoitetietojen tallennus ep\u00e4onnistui",
    "CONFIRM_EXIT_AOU": "Yhteen tai useampaan yksikk\u00f6\u00f6n on tehty tallentamattomia muutoksia. Tallenna muutokset valitsemalla OK tai hylk\u00e4\u00e4 ne valitsemalla Peruuta.",
    "ERROR_DELETING_PERM_MAPPING": "Oikeuskartoituksen ${0} poisto ep\u00e4onnistui",
    "ERROR_SAVING_DATA_CAM": "Kohteen ${0} ${1} tietojen tallennus ep\u00e4onnistui",
    "SUCCESS_SAVING_MAILING": "Kohteen ${0} postiosoitteeseen tehdyt muutokset tallennettu.",
    "ERROR_FETCHING_MAILING": "Postiosoitteen haku kohteelle ${0} ep\u00e4onnistui",
    "ACQ_DISTRIB_FORMULA_NAME_CLONE": "${0} (klooni)",
    "ERROR_CREATING_CHILD_GROUP": "Alaryhm\u00e4n luominen ep\u00e4onnistui",
    "ERROR_DELETING_LAST_AOU": "${0} tuhoaminen ei onnistu, tarvitset v\u00e4hint\u00e4\u00e4n yhden organisaatioyksik\u00f6n.",
    "ERROR_SAVING_HOLDS": "Varausosoitteen tietojen tallennus kohteelle ${0} ep\u00e4onnistui",
    "NAME": "Nimi",
    "SUCCESS_CREATING_CHILD_AOUT": "Uusi alaorganisaatiotyyppi luotu kohteelle ${0}",
    "LABEL_GRANTABLE": "My\u00f6nnett\u00e4viss\u00e4",
    "ERROR_SAVING_ILL": "ILL-osoitetietojen tallennus kohteelle ${0} ep\u00e4onnistui",
    "SURVEY_WARN_TEXT": "No questions can be modified or added at this time. The survey Start Date must be set for the future to add new questions or modify existing questions.",
    "ERROR_FETCHING_GROUPS": "Ryhmien haku ep\u00e4onnistui",
    "SUCCESS_CREATING_PERMISSION": "Uusi ${0} oikeus luotu",
    "SURVEY_ID": "Kyselyn ID # ${0}",
    "COPY_ACTIVE": "Aktivoi niteen",
    "ERROR_CREATING_PERM_MAP": "Uuden oikeuskartan luominen ep\u00e4onnistui",
    "SURVEY_DELETE_ANSWER": "Tuhoa vastaus",
    "SURVEY_QUESTION": "Kysymys:",
    "CONFIRM_EXIT_CAM": "Yhteen tai useampaan ${0} koodiin on tehty tallentamattomia muutoksia. Tallenna muutokset valitsemalla OK tai hylk\u00e4\u00e4 ne valitsemalla Peruuta.",
    "ERROR_DELETING_LAST_AOUT": "Kohteen ${0} tuhoaminen ei onnistui. Tarvitset v\u00e4hint\u00e4\u00e4n yhden organisaatiotyypin.",
    "ERROR_FETCHING_ILL": "ILL-osoitteen haku kohteelle ${0} ep\u00e4onnistui",
    "ERROR_CREATING_CHILD_AOUT": "Alaorganisaatiotyypin luominen ep\u00e4onnistui",
    "ERROR_CALLING_METHOD_PGT": "Alaryhm\u00e4n luomismenetelm\u00e4n kutsu ep\u00e4onnistui",
    "CONFIRM_EXIT_PGT": "Muokattuihin oikeuskarttoihin on tehty tallentamattomia muutoksia. Tallenna muutokset valitsemalla OK tai hylk\u00e4\u00e4 ne valitsemalla Peruuuta.",
    "SURVEY_ANSWER": "Vastaus:",
    "ERROR_FETCHING_PERM_MAPS": "Oikeuskarttojen haku ep\u00e4onnistui",
    "SURVEY_SAVE_ADD": "Tallenna kysymys ja lis\u00e4\u00e4 vastaus",
    "SUCCESS_SAVE": "Muutokset tallennettu kohteeseen ${0}",
    "ERROR_CALLING_METHOD_PERM_MAP": "Uuden oikeuskartan luomismenetelm\u00e4n kutsu ep\u00e4onnistui",
    "EVENT_DEF_LABEL": "${0}: ${1}",
    "SURVEY_DELETE_QUESTION": "Tuhoa kysymykset ja vastaukset",
    "SUCCESS_SAVE_PERM": "Kohteen ${0} oikeuksien muutokset tallennettu",
    "SURVEY_ADD_ANSWER": "Lis\u00e4\u00e4 vastaus",
    "ERROR_FETCHING_STATUSES": "Statusten haku ep\u00e4onnistui",
    "ID": "ID",
    "ERROR_CALLING_METHOD_CAM": "Uuden kohteen ${0} luomismenetelm\u00e4n kutsu ep\u00e4onnistui",
    "CBHO_EDITING_NEW": "Muokkaat uutta paras-varaus -j\u00e4rjestyst\u00e4.",
    "ERROR_SAVING_MAILING": "Kohteen ${0} postiosoitetietojen tallennus ep\u00e4onnistui",
    "IS_AVAILABLE": "Is Available",
    "ERROR_CALLING_METHOD_AOUT": "Alaorganisaatiotyypin luomismenetelm\u00e4n kutsu ep\u00e4onnistui",
    "ERROR_CREATING_STATUS": "Uuden statuksen luominen ep\u00e4onnistui",
    "SUCCESS_NEW_CHILD_GROUP": "Uusi alaryhm\u00e4 luotu kohteelle ${0}"
}