{
    "INVALIDATE": "Invalidate",
    "DUPE_PATRON_IDENT": "Fand $(0) Patrone(n) mit derselben Identifikation",
    "DUPE_PATRON_PHONE": "${0} Bibliotheksnutzer mit der selben Telefonnummer gefunden.",
    "REQUESTING_USER": "Account requested by ${0} ${1}",
    "ADDRESS_HEADER": "Adresse",
    "SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    "ADDRESS_NEW": "Neue Adresse",
    "BARCODE_IN_USE": "Barcode wird bereits benutzt",
    "DELETE_ADDRESS": "L\u00f6schen Adresse ${0}?",
    "SHOW_SUGGESTED": "Vorgeschlagene Felder anzeigen",
    "HOLD_NOTIFY_PHONE": "Phone: ",
    "INVALID_FORM": "Form ist ung\u00fcltigt. Bitte bearbeiten und neu versuchen.",
    "UPDATE_EXPIRE_DATE": "Update Expire Date",
    "VERIFY_PASSWORD": "Passwort best\u00e4tigen",
    "DUPE_PATRON_EMAIL": "${0} Bibliotheksnutzer mit der selben E-Mail Adresse gefunden",
    "PARENT_OR_GUARDIAN": "Eltern/Vormund",
    "USER_SETTINGS": "Benutzereinstellungen",
    "ALL_CARDS_PRIMARY": "Primary",
    "REPLACE_BARCODE": "Barcode ersetzen",
    "HOLD_NOTIFY_SMS": "SMS: ",
    "DUPE_PATRON_ADDR": "${0} Bibliotheksnutzer mit der selben Adresse gefunden",
    "SAVE_CLONE": "Speichere &amp; Klon",
    "SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    "ADDRESS_OWNED": "Diese Adresse geh\u00f6rt einem anderen Benutzer: ",
    "ALL_CARDS_BARCODE": "Barcode",
    "DEFAULT_ADDRESS_TYPE": "MITTEILEN",
    "SHOW_REQUIRED": "Nur ben\u00f6tigte Felder anzeigen",
    "REPLACED_ADDRESS": "<div>Ersetzt Adresse <b>${0}</b><br/> ${1} ${2}<br/> ${3}, ${4} ${5}</div>",
    "SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    "SHOW_ALL": "Alle Felder anzeigen",
    "RESET_PASSWORD": "Generate Password",
    "ALL_CARDS_APPLY": "\u00c4nderungen anwenden",
    "ADD": "Add",
    "ADDRESS_BILLING": "Abrechnung",
    "HOLD_NOTIFY_EMAIL": "Email: ",
    "ADDRESS_APPROVE": "Gepr\u00fcfte Adresse",
    "DUPE_USERNAME": "Benutzername wird bereits benutzt",
    "EXAMPLE": "Beispiel: ",
    "SEE_ALL": "Alles anzeigen",
    "STAT_CATS": "Statistische Kategorien",
    "ALL_CARDS_ACTIVE": "Active",
    "ALL_CARDS_CLOSE": "Close",
    "ADDRESS_MAILING": "Mailversand",
    "ADDRESS_PENDING": "Dies ist eine unbest\u00e4tigte Adresse: ",
    "SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    "DUPE_PATRON_NAME": "${0} Bibliotheksnutzer mit dem selben Namen gefunden",
    "NEED_ADDRESS": "Eine Adresse ist w\u00e4hrend der Registrierung erforderlich.",
    "SAVE": "Speichern",
    "DELETE": "Delete"
}