{
    "ENTER_BARCODE": "Sy\u00f6t\u00e4 niteen viivakoodi",
    "WORKSTATION_EXISTS": "Ty\u00f6asema on jo rekister\u00f6ity. Haluatko k\u00e4ytt\u00e4\u00e4 sit\u00e4 itsetarkistuksen asemana?",
    "FAIL_PART_no_item": "J\u00e4rjestelm\u00e4 ei l\u00f6yt\u00e4nyt nidett\u00e4",
    "HOLD_STATUS_WAITING": "#${0} jonossa, ${1} kappaletta",
    "OPEN_CIRCULATION_EXISTS": "Nide ${0} on jo lainattu toiselle k\u00e4ytt\u00e4j\u00e4lle",
    "RENEW_SUCCESS": "Niteen ${0} uusiminen onnistui",
    "FAIL_PART_no_matchpoint": "J\u00e4rjestelm\u00e4s\u00e4\u00e4nn\u00f6iss\u00e4 ei m\u00e4\u00e4ritet\u00e4, kuinka nidett\u00e4 tulee k\u00e4sitell\u00e4",
    "FAIL_PART_item.holdable": "Nidett\u00e4 ei voi varata",
    "FAIL_PART_asset_copy_circulate": "Nidett\u00e4 ei lainata",
    "FAIL_PART_config_hold_matrix_test_max_holds": "Asiakkaan varausten m\u00e4\u00e4r\u00e4 on saavuttanut enimm\u00e4israjan",
    "CHECKOUT_SUCCESS": "Niteen ${0} lainaus onnistui",
    "ALREADY_OUT": "Nide ${0} on jo lainattu",
    "TOTAL_FINES_ACCOUNT": "Maksuja tilill\u00e4 yhteens\u00e4: $${0}.",
    "PLEASE_LOGIN": "Kirjaudu k\u00e4ytt\u00e4j\u00e4nimell\u00e4si tai kirjastokortin viivakoodilla.",
    "FAIL_PART_transit_range": "Nidett\u00e4 ei voida kuljettaa n\u00e4in kauas",
    "FAIL_PART_config_circ_matrix_test_available_copy_hold_ratio": "Lainattavissa olevien niteiden ja varausten suhde on liian alhainen",
    "TOTAL_ITEMS_SESSION": "Niteit\u00e4 yhteens\u00e4 t\u00e4ss\u00e4 istunnossa: ${0}.",
    "FAIL_PART_config_hold_matrix_test_holdable": "Varauss\u00e4\u00e4nn\u00f6iss\u00e4 t\u00e4m\u00e4 nide on m\u00e4\u00e4ritetty ei-varattavaksi",
    "FAIL_PART_circ_holds_target_skip_me": "Kyseisen sijaintipaikan nidett\u00e4 ei voi varata",
    "TOTAL_FINES_SELECTED": "Valittu yhteens\u00e4: $${0}",
    "MISCELLANEOUS": "Muut maksut",
    "ITEM_NOT_CATALOGED": "Nidett\u00e4 ${0} ei l\u00f6ytynyt j\u00e4rjestelm\u00e4st\u00e4.  Sy\u00f6t\u00e4 nidetunnus uudelleen.",
    "FAIL_PART_config_rule_age_hold_protect_prox": "Nide on liian uusi kuljetettavaksi n\u00e4in kauas",
    "FAIL_PART_location.holdable": "Niteen sijainti ei ole varattavissa",
    "TOTAL_HOLDS": "Sinulla on yhteens\u00e4 ${0} varausta.",
    "FAIL_PART_asset_copy_location_circulate": "T\u00e4h\u00e4n hyllysijaintiin kuuluvia niteit\u00e4 ei lainata",
    "FAIL_PART_no_ultimate_items": "J\u00e4rjestelm\u00e4 ei l\u00f6yt\u00e4nyt varauspyynt\u00f6\u00e4 vastaavia niteit\u00e4",
    "FAIL_PART_asset_copy_status": "Nidett\u00e4 ei voida lainata t\u00e4ll\u00e4 hetkell\u00e4",
    "UNKNOWN_ERROR": "K\u00e4sittelem\u00e4t\u00f6n poikkeus ilmeni virhekoodilla ${0}",
    "CC_PAYABLE_BALANCE": "Maksettava yhteens\u00e4: $${0}",
    "WELCOME_BANNER": "Tervetuloa, ${0}",
    "LOGIN_FAILED": "K\u00e4ytt\u00e4j\u00e4n ${0} kirjautuminen ep\u00e4onnistui",
    "GENERIC_CIRC_FAILURE": "Niteen ${0} lainaus ei onnistu.  Ota yhteytt\u00e4 henkil\u00f6kuntaan.",
    "MAX_RENEWALS": "Nidett\u00e4 ${0} ei voi uusia.",
    "FAIL_PART_config_circ_matrix_test_total_copy_hold_ratio": "Niteet/varaukset-kokonaissuhde on liian alhainen",
    "HOLDS_READY_FOR_PICKUP": "${0} noudettavissa olevaa nidett\u00e4.",
    "FAIL_PART_actor_usr_barred": "Asiakas on lainauskiellossa",
    "ENTER_PASSWORD": "Sy\u00f6t\u00e4 salasanasi",
    "WORKSTATION_REQUIRED": "M\u00e4\u00e4rit\u00e4 ty\u00f6asema itselainausta varten.  Voit m\u00e4\u00e4ritt\u00e4\u00e4 ty\u00f6aseman nimen URL-parametrilla 'ws'.  \n\nHaluatko rekister\u00f6id\u00e4 uuden ty\u00f6aseman itselainauksen k\u00e4ytt\u00f6liittym\u00e4ksi?",
    "TOTAL_ITEMS_ACCOUNT": "Lainoja yhteens\u00e4: ${0}.",
    "FAIL_PART_no_user": "J\u00e4rjestelm\u00e4 ei l\u00f6yt\u00e4nyt asiakasta",
    "FAIL_PART_status.holdable": "Niteen tila on ei-varattava",
    "HOLD_STATUS_READY": "Noudettavissa",
    "FAIL_PART_config_circ_matrix_circ_mod_test": "Asiakkaalla on liikaa t\u00e4m\u00e4n aineistolajin lainoja",
    "PAYMENT_INVALID_USER_XACT_ID": "Emme voi suorittaa maksua loppuun, koska tili\u00e4si p\u00e4ivitettiin toisesta sijainnista. Lataa sivu uudelleen tai kirjaudu ulos ja j\u00e4lleen takaisin, niin uusimmat tilitiedot p\u00e4ivittyv\u00e4t",
    "FAIL_PART_config_circ_matrix_test_circulate": "Lainauss\u00e4\u00e4nn\u00f6iss\u00e4 t\u00e4m\u00e4 nide on m\u00e4\u00e4ritetty ei-lainattavaksi"
}