{
    "INVALIDATE": "Invalidar",
    "DUPE_PATRON_IDENT": "Encontrados ${0} patron(es) con la misma identificaci\u00f3n",
    "DUPE_PATRON_PHONE": "Encontrados ${0} patron(es) con el mismo n\u00famero de tel\u00e9fono",
    "REQUESTING_USER": "Cuenta solicitada por ${0} ${1}",
    "ADDRESS_HEADER": "Direcci\u00f3n",
    "SECONDARY_GROUP_EXISTS": "Este grupo ya esta en la lista.",
    "ADDRESS_NEW": "Direcci\u00f3n nueva",
    "BARCODE_IN_USE": "El c\u00f3digo de barras est\u00e1 en uso",
    "DELETE_ADDRESS": "Eliminar direcci\u00f3n ${0}?",
    "SHOW_SUGGESTED": "Mostrar campos sugeridos",
    "HOLD_NOTIFY_PHONE": "Tel\u00e9fono: ",
    "INVALID_FORM": "El formulario es inv\u00e1lido. Por favor, ed\u00edtelo e int\u00e9ntelo de nuevo.",
    "UPDATE_EXPIRE_DATE": "Actualizar Fecha de Vencimiento",
    "VERIFY_PASSWORD": "Verificar contrase\u00f1a",
    "DUPE_PATRON_EMAIL": "Encontrados ${0} patron(es) con la misma direcci\u00f3n de correo electr\u00f3nico",
    "PARENT_OR_GUARDIAN": "Padre / Tutor",
    "USER_SETTINGS": "Configuraci\u00f3n del usuario",
    "ALL_CARDS_PRIMARY": "Primario",
    "REPLACE_BARCODE": "Reemplazar c\u00f3digo de barras",
    "HOLD_NOTIFY_SMS": "SMS: ",
    "DUPE_PATRON_ADDR": "Encontrados ${0} patron(es) con la misma direcci\u00f3n",
    "SAVE_CLONE": "Guardar y clonar",
    "SECONDARY_GROUP_ERROR": "Error salvando grupos secundarios.",
    "ADDRESS_OWNED": "Esta direcci\u00f3n pertenece a otro usuario: ",
    "ALL_CARDS_BARCODE": "C\u00f3digo de barras",
    "DEFAULT_ADDRESS_TYPE": "Direcci\u00f3n",
    "SHOW_REQUIRED": "Solo mostrar los campos requeridos",
    "REPLACED_ADDRESS": "Reemplaza la direcci\u00f3n ${0}<br/> ${1} ${2}<br/> ${3}, ${4} ${5}",
    "SECONDARY_GROUP_NOT_ALLOWED": "Usted no tiene permiso para agregar este grupo.",
    "SHOW_ALL": "Mostrar todos los campos",
    "RESET_PASSWORD": "Generar contrase\u00f1a",
    "ALL_CARDS_APPLY": "Aplicar los cambios",
    "ADD": "A\u00f1adir",
    "ADDRESS_BILLING": "Facturaci\u00f3n",
    "HOLD_NOTIFY_EMAIL": "Correo electr\u00f3nico: ",
    "ADDRESS_APPROVE": "Aprobar direcci\u00f3n",
    "DUPE_USERNAME": "El nombre de usuario ya est\u00e1 en uso",
    "EXAMPLE": "Ejemplo: ",
    "SEE_ALL": "Ver todos",
    "STAT_CATS": "Categor\u00edas Estad\u00edsticas",
    "ALL_CARDS_ACTIVE": "Activo",
    "ALL_CARDS_CLOSE": "Cerrar",
    "ADDRESS_MAILING": "Env\u00edo de correo",
    "ADDRESS_PENDING": "Esta es una direcci\u00f3n pendiente: ",
    "SECONDARY_GROUP_IS_PROFILE": "Esto ya es el grupo de perfil principal de este patr\u00f3n.",
    "DUPE_PATRON_NAME": "Encontrados ${0} patron(es) con el mismo nombre",
    "NEED_ADDRESS": "Se requiere una direcci\u00f3n durante el registro.",
    "SAVE": "Guardar",
    "DELETE": "Eliminar"
}