{
    "NO_PAYLOAD": "Nous n'avons pas re\u00e7u de plus amples informations depuis le serveur a propos de cette tentative de saisie.",
    "TITLE": "Titre",
    "PRINT": "<u>I</u>mprimer",
    "AUTO_resource_barcode": "Entrez le Code \u00e0 Barres :",
    "DURATION": "R\u00e9serv\u00e9s \u00e0 partir de",
    "NEEDS_ROUTED_TO": "Cet article doit \u00eatre achemin\u00e9 vers",
    "PRINTED_BY": "Imprim\u00e9 par",
    "CAPTURE_TRANSIT_SOURCE": "De:",
    "CAPTURE_INFO": "Information de Capture",
    "AUTO_ATTR_VALUE_capture": "Saisie",
    "AUTHOR": "Auteur",
    "CAPTURE_BRESV_BRSRC": "Code barre des ressources:",
    "SLIP_DATE": "Glissement de date",
    "RESERVATION_SHELF": "TABLETTE DE R\u00c9SERVATION",
    "UNKNOWN_PROBLEM": "Un probl\u00e8me inconnu s'est produit lors de la tentative de capture.",
    "FAILURE": "Saisie \u00e9chou\u00e9e",
    "CAPTURE_CAUSES_TRANSIT": "Cet article est actuellement en transport!",
    "RESERVED": "R\u00e9serv\u00e9 pour client",
    "SUCCESS": "Saisie r\u00e9ussie",
    "REQUEST": "Temps n\u00e9cessaire",
    "AT": "\u00e0",
    "CAPTURE_BRESV_PICKUP_LIB": "Biblioth\u00e8que de collecte:",
    "CAPTURED_NOTHING": "N'a pas pu capturer quoique ce soit.",
    "TRANSIT": "*** TRANSPORT ***",
    "BARCODE": "Code \u00e0 barres",
    "AUTO_pickup_lib_selector": "Biblioth\u00e8que de collecte:",
    "CAPTURE_TRANSIT_DEST": "Pour:",
    "PRINT_ACCESSKEY": "I",
    "CAPTURE_BRESV_DATES": "Temp de r\u00e9servation:",
    "HERES_WHAT_WE_KNOW": "L'information suivante est accessible au sujet de la capture \u00e9chou\u00e9e:",
    "AUTO_capture_heading": "Saisie des ressources r\u00e9serv\u00e9es"
}