{
    "VIEW_MARC": "Ver MARC",
    "CONFIRM_DELETE_RESULT": "Eliminar registro de autoridad # ${0}.",
    "TARGET_RECORD": "Objetivo",
    "MENU_MERGE": "Marcar para mezclar",
    "HIDE_MARC": "Ocultar MARC",
    "AUTHORITY_FIELDS": "Campos de Autoridad (${0})",
    "MENU_EDIT": "Editar",
    "CONFIRM_DELETE_TITLE": "\u00bfDesea eliminar el registro de autoridad: \"${0}\"?",
    "CONFIRM_DELETE_PROMPT": "Confirmar eliminaci\u00f3n del registro # ${0}",
    "MASTER_RECORD": "Principal",
    "CANCEL": "Cancelar",
    "NONE_LINK": "[Ninguno]",
    "SAVE_RESULT_SUCCESS": "El registro se ha guardado",
    "MENU_DELETE": "Eliminar",
    "LINKED_BIBS": "Numero de registros bibliogr\u00e1ficos ligados: ${0}",
    "ACTIONS": "Acciones",
    "MERGE_RESULT_SUCCESS": "Uni\u00f3n de registros completa",
    "CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    "THESAURI": "Tesauro (${0})",
    "SAVE": "Guardar",
    "AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    "DELETE": "Eliminar"
}