{
    "VIEW_MARC": "Ver MARC",
    "CONFIRM_DELETE_RESULT": "Registro de autoridade exclu\u00eddo # ${0}.",
    "TARGET_RECORD": "Destino",
    "MENU_MERGE": "Marcar para mesclagem",
    "HIDE_MARC": "Esconder MARC",
    "AUTHORITY_FIELDS": "Campos de Autoridade (${0})",
    "MENU_EDIT": "Editar",
    "CONFIRM_DELETE_TITLE": "Excluir o registro de autoridade: \"${0}\"?",
    "CONFIRM_DELETE_PROMPT": "Confirmar a exclus\u00e3o de registro # ${0}",
    "MASTER_RECORD": "Mestre",
    "CANCEL": "Cancelar",
    "NONE_LINK": "[Nenhum]",
    "SAVE_RESULT_SUCCESS": "O registo foi gravado.",
    "MENU_DELETE": "Excluir",
    "LINKED_BIBS": "N\u00famero de registros bibliogr\u00e1ficos relacionados: ${0}",
    "ACTIONS": "A\u00e7\u00f5es",
    "MERGE_RESULT_SUCCESS": "Mesclagem de registro esta conclu\u00edda.",
    "CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    "THESAURI": "Tesauro  (${0})",
    "SAVE": "Salvar",
    "AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    "DELETE": "Excluir"
}