{
    "VIEW_MARC": "MARC anzeigen",
    "CONFIRM_DELETE_RESULT": "Deleted authority record # ${0}.",
    "TARGET_RECORD": "Ziel",
    "MENU_MERGE": "Mark for Merge",
    "HIDE_MARC": "MARC ausblenden",
    "AUTHORITY_FIELDS": "Authority Fields (${0})",
    "MENU_EDIT": "Bearbeiten",
    "CONFIRM_DELETE_TITLE": "Delete the authority record: \"${0}\"?",
    "CONFIRM_DELETE_PROMPT": "Confirm deletion of record # ${0}",
    "MASTER_RECORD": "Master",
    "CANCEL": "Abbrechen",
    "NONE_LINK": "[None]",
    "SAVE_RESULT_SUCCESS": "Record was saved.",
    "MENU_DELETE": "L\u00f6schen",
    "LINKED_BIBS": "Number of linked bibliographic records: ${0}",
    "ACTIONS": "Aktionen",
    "MERGE_RESULT_SUCCESS": "Record merge is complete.",
    "CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    "THESAURI": "Thesauri (${0})",
    "SAVE": "Speichern",
    "AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    "DELETE": "L\u00f6schen"
}