{
    "INVALIDATE": "Ge\u00e7ersiz",
    "DUPE_PATRON_IDENT": "Found ${0} patron(s) with the same identification",
    "DUPE_PATRON_PHONE": "Found ${0} patron(s) with the same phone number",
    "REQUESTING_USER": "Account requested by ${0} ${1}",
    "ADDRESS_HEADER": "Adres",
    "SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    "ADDRESS_NEW": "Yeni Adres",
    "BARCODE_IN_USE": "Barkod zaten kullan\u0131mda",
    "DELETE_ADDRESS": "${0} adresinii siliyorsun?",
    "SHOW_SUGGESTED": "Show Suggested Fields",
    "HOLD_NOTIFY_PHONE": "Telefon: ",
    "INVALID_FORM": "Form hatal\u0131. L\u00fctfen d\u00fczenleyip tekrar deneyin.",
    "UPDATE_EXPIRE_DATE": "Update Expire Date",
    "VERIFY_PASSWORD": "Parolay\u0131 Do\u011frula",
    "DUPE_PATRON_EMAIL": "Found ${0} patron(s) with the same email address",
    "PARENT_OR_GUARDIAN": "Parent/Guardian",
    "USER_SETTINGS": "Kullan\u0131c\u0131 Ayarlar\u0131",
    "ALL_CARDS_PRIMARY": "Birincil",
    "REPLACE_BARCODE": "Barkodu Yenile",
    "HOLD_NOTIFY_SMS": "SMS: ",
    "DUPE_PATRON_ADDR": "Found ${0} patron(s) with the same address",
    "SAVE_CLONE": "Save &amp; Clone",
    "SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    "ADDRESS_OWNED": "Bu adres ba\u015fka bir kullan\u0131c\u0131ya ait: ",
    "ALL_CARDS_BARCODE": "Barkod",
    "DEFAULT_ADDRESS_TYPE": "MAILING",
    "SHOW_REQUIRED": "Sadece Gerekli Alanlar\u0131 G\u00f6ster",
    "REPLACED_ADDRESS": "Replaces address ${0}<br/> ${1} ${2}<br/> ${3}, ${4} ${5}",
    "SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    "SHOW_ALL": "T\u00fcm Alanlar\u0131 G\u00f6ster",
    "RESET_PASSWORD": "Generate Password",
    "ALL_CARDS_APPLY": "De\u011fi\u015fiklikleri Uygula",
    "ADD": "Add",
    "ADDRESS_BILLING": "\u00dccretlendirme",
    "HOLD_NOTIFY_EMAIL": "Eposta: ",
    "ADDRESS_APPROVE": "Approve Address",
    "DUPE_USERNAME": "Kullan\u0131c\u0131 ad\u0131 zaten kullan\u0131mda",
    "EXAMPLE": "\u00d6rnek: ",
    "SEE_ALL": "Hepsini G\u00f6ster",
    "STAT_CATS": "\u0130statistiksel Kategoriler",
    "ALL_CARDS_ACTIVE": "Etkin",
    "ALL_CARDS_CLOSE": "Kapat",
    "ADDRESS_MAILING": "Mailing",
    "ADDRESS_PENDING": "bu beklemedeki bir adres: ",
    "SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    "DUPE_PATRON_NAME": "Found ${0} patron(s) with the same name",
    "NEED_ADDRESS": "An address is required during registration.",
    "SAVE": "Kaydet",
    "DELETE": "Delete"
}