{
    "VIEW_MARC": "N\u00e4yt\u00e4 MARC",
    "CONFIRM_DELETE_RESULT": "Auktoriteettitietue # ${0} tuhottu.",
    "TARGET_RECORD": "Kohde",
    "MENU_MERGE": "Merkitse yhdistett\u00e4v\u00e4ksi",
    "HIDE_MARC": "Piilota MARC",
    "AUTHORITY_FIELDS": "Auktoriteettikent\u00e4t (${0})",
    "MENU_EDIT": "Muokkaa",
    "CONFIRM_DELETE_TITLE": "Tuhotaanko auktoriteettitietue: \"${0}\"?",
    "CONFIRM_DELETE_PROMPT": "Vahvista tietueen # ${0} poisto",
    "MASTER_RECORD": "Master",
    "CANCEL": "Peruuta",
    "NONE_LINK": "[Ei mit\u00e4\u00e4n]",
    "SAVE_RESULT_SUCCESS": "Tietue tallennettiin.",
    "MENU_DELETE": "Tuhoa",
    "LINKED_BIBS": "Linkitettyjen bibliografisten tietueiden lukum\u00e4\u00e4r\u00e4: ${0}",
    "ACTIONS": "Toiminnot",
    "MERGE_RESULT_SUCCESS": "Tietueet yhdistetty.",
    "CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    "THESAURI": "Synonyymisanakirjat (${0})",
    "SAVE": "Tallenna",
    "AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    "DELETE": "Tuhoa"
}