{
    "INVALIDATE": "Invalidar",
    "DUPE_PATRON_IDENT": "Encontrados ${0} padr(\u00e3o/\u00f5es) com a mesma identifica\u00e7\u00e3o",
    "DUPE_PATRON_PHONE": "Encontrados ${0} padr(\u00e3o/\u00f5es) com o mesmo n\u00famero de telefone",
    "REQUESTING_USER": "Account requested by ${0} ${1}",
    "ADDRESS_HEADER": "Endere\u00e7o",
    "SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    "ADDRESS_NEW": "Novo Endere\u00e7o",
    "BARCODE_IN_USE": "C\u00f3digo de Barras j\u00e1 est\u00e1 em uso",
    "DELETE_ADDRESS": "Apagar endere\u00e7o ${0}?",
    "SHOW_SUGGESTED": "Mostrar Campos Sugeridos",
    "HOLD_NOTIFY_PHONE": "Telefone: ",
    "INVALID_FORM": "Formul\u00e1rio est\u00e1 inv\u00e1lido. Por favor, edite e tente novamente.",
    "UPDATE_EXPIRE_DATE": "Update Expire Date",
    "VERIFY_PASSWORD": "Verificar Senha",
    "DUPE_PATRON_EMAIL": "Encontrados ${0} padr(\u00e3o/\u00f5es) com a mesma dire\u00e7\u00e3o de email",
    "PARENT_OR_GUARDIAN": "Pai/Guardi\u00e3o",
    "USER_SETTINGS": "Configura\u00e7\u00f5es do Usu\u00e1rio",
    "ALL_CARDS_PRIMARY": "Prim\u00e1rio",
    "REPLACE_BARCODE": "Substituir C\u00f3digo-de-barras",
    "HOLD_NOTIFY_SMS": "SMS: ",
    "DUPE_PATRON_ADDR": "Encontrados ${0} padr(\u00e3o/\u00f5es) com o mesmo endere\u00e7o",
    "SAVE_CLONE": "Salvar &amp; Clonar",
    "SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    "ADDRESS_OWNED": "Este endere\u00e7o \u00e9 utilizado por outro usu\u00e1rio: ",
    "ALL_CARDS_BARCODE": "C\u00f3digo de barras",
    "DEFAULT_ADDRESS_TYPE": "Mensagens",
    "SHOW_REQUIRED": "Mostrar somente Campos Obrigat\u00f3rios",
    "REPLACED_ADDRESS": "<div>Substituir endere\u00e7o <b>${0}</b><br/> ${1} ${2}<br/> ${3}, ${4} ${5}</div>",
    "SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    "SHOW_ALL": "Mostar todos os campos",
    "RESET_PASSWORD": "Generate Password",
    "ALL_CARDS_APPLY": "Aplicar Altera\u00e7\u00f5es",
    "ADD": "Add",
    "ADDRESS_BILLING": "Cobran\u00e7a",
    "HOLD_NOTIFY_EMAIL": "E-mail: ",
    "ADDRESS_APPROVE": "Aprovar Endere\u00e7o",
    "DUPE_USERNAME": "Nome de Usu\u00e1rio j\u00e1 est\u00e1 em uso",
    "EXAMPLE": "Examplo: ",
    "SEE_ALL": "Ver Todos",
    "STAT_CATS": "Categorias Estat\u00edsticas",
    "ALL_CARDS_ACTIVE": "Ativo",
    "ALL_CARDS_CLOSE": "Fechar",
    "ADDRESS_MAILING": "Correio",
    "ADDRESS_PENDING": "Este \u00e9 um endere\u00e7o pendente: ",
    "SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    "DUPE_PATRON_NAME": "Encontrados ${0} padr(\u00e3o/\u00f5es) com o mesmo nome",
    "NEED_ADDRESS": "Um endere\u00e7o \u00e9 exigido durante o registro.",
    "SAVE": "Salvar",
    "DELETE": "Delete"
}