{
    "ENTER_BARCODE": "Veuillez entrer le code-barre d\u2019un article",
    "WORKSTATION_EXISTS": "Ce poste de travail a d\u00e9j\u00e0 \u00e9t\u00e9 enregistr\u00e9. Voulez-vous l\u2019utiliser pour cette station libre-service ?",
    "FAIL_PART_no_item": "Document introuvable",
    "HOLD_STATUS_WAITING": "#${0} en ligne avec ${1} copies",
    "OPEN_CIRCULATION_EXISTS": "Le document ${0} est d\u00e9j\u00e0 enregistr\u00e9 sur le compte d\u2019un autre utilisateur",
    "RENEW_SUCCESS": "Le renouvellement du document ${0} a \u00e9t\u00e9 effectu\u00e9.",
    "FAIL_PART_no_matchpoint": "Les modalit\u00e9s du syst\u00e8me ne d\u00e9finissent pas comment traiter ce document.",
    "FAIL_PART_item.holdable": "Impossible de r\u00e9server cet article",
    "FAIL_PART_asset_copy_circulate": "Le document n\u2019est pas en circulation.",
    "FAIL_PART_config_hold_matrix_test_max_holds": "Le client a atteint le nombre maximal de r\u00e9servations.",
    "CHECKOUT_SUCCESS": "L\u2019enregistrement du document ${0} a \u00e9t\u00e9 effectu\u00e9.",
    "ALREADY_OUT": "Le document ${0} est d\u00e9j\u00e0 enregistr\u00e9",
    "TOTAL_FINES_ACCOUNT": "Montant total des amendes du compte\u00a0: $${0}.",
    "PLEASE_LOGIN": "Veuillez ouvrir une session en utilisant votre nom d'utilisateur ou le code-barre de la biblioth\u00e8que.",
    "FAIL_PART_transit_range": "Ce document ne peut pas \u00eatre transf\u00e9r\u00e9 aussi loin.",
    "FAIL_PART_config_circ_matrix_test_available_copy_hold_ratio": "Le ratio disponible de documents \u00e0 r\u00e9server est trop bas.",
    "TOTAL_ITEMS_SESSION": "Nombre d\u2019articles dans cette session\u00a0: ${0}.",
    "FAIL_PART_config_hold_matrix_test_holdable": "Ce document ne peut \u00eatre r\u00e9serv\u00e9, conform\u00e9ment aux modalit\u00e9s de r\u00e9servation.",
    "FAIL_PART_circ_holds_target_skip_me": "La biblioth\u00e8que qui poss\u00e8de le document ne fait pas de r\u00e9servations.",
    "TOTAL_FINES_SELECTED": "Total d\u2019\u00e9l\u00e9ments s\u00e9lectionn\u00e9s : $${0}",
    "MISCELLANEOUS": "Divers",
    "ITEM_NOT_CATALOGED": "Impossible de trouver le document ${0} dans le syst\u00e8me. Essayez \u00e0 nouveau.",
    "FAIL_PART_config_rule_age_hold_protect_prox": "Le document est trop r\u00e9cent pour \u00eatre transf\u00e9r\u00e9 aussi loin.",
    "FAIL_PART_location.holdable": "Impossible de r\u00e9server l\u2019article \u00e0 cet emplacement",
    "TOTAL_HOLDS": "Vous avez un total de ${0} r\u00e9servations.",
    "FAIL_PART_asset_copy_location_circulate": "Les documents de ce rayon ne peuvent \u00eatre pr\u00eat\u00e9s.",
    "FAIL_PART_no_ultimate_items": "Aucun document correspondant \u00e0 la demande de r\u00e9servation.",
    "FAIL_PART_asset_copy_status": "Ce document ne peut \u00eatre pr\u00eat\u00e9 pour l\u2019instant.",
    "UNKNOWN_ERROR": "Une exception non g\u00e9r\u00e9e s\u2019est produite. Code d\u2019erreur ${0}",
    "CC_PAYABLE_BALANCE": "Montant total \u00e0 payer : $${0}",
    "WELCOME_BANNER": "Bienvenue, ${0}",
    "LOGIN_FAILED": "\u00c9chec de l\u2019ouverture de session pour ${0}",
    "GENERIC_CIRC_FAILURE": "Impossible d\u2019enregistrer le document ${0}. Veuillez vous renseigner aupr\u00e8s du personnel.",
    "MAX_RENEWALS": "Aucun renouvellement accept\u00e9 pour le document ${0}",
    "FAIL_PART_config_circ_matrix_test_total_copy_hold_ratio": "Le ratio total de documents \u00e0 r\u00e9server est trop bas.",
    "HOLDS_READY_FOR_PICKUP": "Vous avez ${0} articles pr\u00eats pour cueillette.",
    "FAIL_PART_actor_usr_barred": "Le client est banni.",
    "ENTER_PASSWORD": "Veuillez entrer votre mot de passe",
    "WORKSTATION_REQUIRED": "Un poste de travail est requis pour se connecter au libre-service. Vous pouvez enregistrer le poste de travail avec le param\u00e8tre URL \u00ab ws \u00bb.\n\nVoulez-vous enregistrer un nouveau poste de travail pour la station libre-service?",
    "TOTAL_ITEMS_ACCOUNT": "Nombre total d\u2019articles dans le compte\u00a0: ${0}.",
    "FAIL_PART_no_user": "Client introuvable",
    "FAIL_PART_status.holdable": "Impossible de r\u00e9server cet article",
    "HOLD_STATUS_READY": "Document(s) pr\u00eat(s) pour la collecte",
    "FAIL_PART_config_circ_matrix_circ_mod_test": "Trop de documents du m\u00eame type sont enregistr\u00e9s au compte du client.",
    "PAYMENT_INVALID_USER_XACT_ID": "Nous ne pouvons pas effectuer le paiement puisque votre compte a \u00e9t\u00e9 mis \u00e0 jour \u00e0 partir d\u2019un autre endroit. Veuillez actualiser l\u2019interface ou vous d\u00e9connecter et vous connecter \u00e0 nouveau pour obtenir les informations les plus r\u00e9centes li\u00e9es \u00e0 votre compte.",
    "FAIL_PART_config_circ_matrix_test_circulate": "Ce document ne peut \u00eatre mis en circulation, conform\u00e9ment aux modalit\u00e9s de circulation."
}