{
    "SOURCE_SETUP_ALL_AVAIL_SOURCES": "V\u0161echny dostupn\u00e9 zdroje",
    "TEMPLATE_CONF_SELECT_CANCEL": "Vyberte hodnotu nebo zru\u0161te:",
    "OPERATORS_ILIKE": "Obsahuje shoduj\u00edc\u00ed se pod\u0159et\u011bzec (bez ohledu na velikost p\u00edsma)",
    "FILTERS_LABEL_NULL_BLANK": "Je NULL nebo pr\u00e1zdn\u00fd",
    "OPERATORS_LIKE": "Obsahuje odpov\u00eddaj\u00edc\u00ed pod\u0159et\u011bzec",
    "WIDGET_MONTHS": "M\u011bs\u00edc(e)",
    "LINK_NULLABLE_RIGHT": "Nad\u0159azen\u00fd typ",
    "TFORMS_LABEL_AVERAGE": "Pr\u016fm\u011br",
    "TEMPLATE_CONF_CONFIRM_STATE": "Klikn\u011bte na OK pro hodnotu  PRAVDA nebo Storno pro hodnotu NEPRAVDA.",
    "OPERATORS_EQUALS": "Je roven",
    "FILTERS_LABEL_BETWEEN": "Mezi",
    "OPERATORS_IN_LIST": "V seznamu",
    "TEMPLATE_CONF_NOT_IN": "Pole se neshoduje s jedn\u00edm ze seznamu (odd\u011blen\u00fd \u010d\u00e1rkami):",
    "OPERATORS_NOT_IN_LIST": "Nen\u00ed v seznamu",
    "FILTERS_LABEL_NOT_IN": "Nen\u00ed v seznamu",
    "FOLDERS_OUTPUT": "V\u00fdstup",
    "FILTERS_LABEL_GT_TIME": "Po (datum / \u010das)",
    "OPERATORS_IS_NULL": "Je NULL",
    "TEMPLATE_CONF_CONFIRM_SAVE": "Jm\u00e9no : ${0}\nPopis : ${1}\nUlo\u017eit \u0161ablonu?",
    "OPERATORS_IS_NOT_NULL": "Nen\u00ed NULL",
    "TEMPLATE_CONF_CONFIRM_RESET": "Pole [${0}]  ze zdroje  [${1}] jste ji\u017e \np\u0159idal(a).  Klikn\u011bte na OK, pokud\nchcete toto pole znovu nastavit.",
    "OPERATORS_GT_EQUAL": "V\u011bt\u0161\u00ed nebo rovno",
    "TRANSFORMS_MONTH_TRUNC": "Rok + M\u011bs\u00edc",
    "FILTERS_LABEL_NULL": "Je NULL",
    "REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Vyberte pros\u00edm slo\u017eku zpr\u00e1v",
    "OPERATORS_GT_TIME": "Po (datum / \u010das)",
    "TRANSFORMS_YEAR_TRUNC": "Rok",
    "TRANSFORMS_UPPER": "Velk\u00e1 p\u00edsmena",
    "FOLDERS_REPORTS": "Zpr\u00e1vy a statistiky",
    "LINK_NULLABLE_LEFT": "Pod\u0159\u00edzen\u00fd",
    "TRANSFORMS_COUNT_DISTINCT": "Po\u010d\u00edtadlo rozd\u00edl\u016f",
    "FOLDER_WINDOW_COLNAME_SELECT": "Vybrat",
    "TRANSFORMS_FIRST": "Prvn\u00ed hodnota",
    "TFORMS_LABEL_LOWER": "Mal\u00e1 p\u00edsmena",
    "TFORMS_LABEL_COUNT": "Po\u010det",
    "TRANSFORMS_HOD": "Hodina",
    "WIDGET_RELATIVE_DATE": "Relativn\u00ed datum",
    "FILTERS_LABEL_LESS_THAN": "Men\u0161\u00ed ne\u017e",
    "TEMPLATE_CONF_SUCCESS_SAVE": "\u0160ablona ${0} byla \u00fasp\u011b\u0161n\u011b ulo\u017eena.",
    "TFORMS_LABEL_MOY": "M\u011bs\u00edc",
    "FILTERS_LABEL_EQ_ANY": "Je rovno kter\u00e9mukoliv",
    "TRANSFORMS_MAX": "Max",
    "TRANSFORMS_MIN": "Min",
    "TRANSFORMS_SUM": "Suma",
    "TRANSFORMS_FIRST_WORD": "Prvn\u00ed n\u00e1sleduj\u00edc\u00ed \u0159et\u011bzec bez mezer",
    "TRANSFORMS_MONTHS_AGO": "P\u0159ed m\u011bs\u00edci",
    "SOURCE_BROWSE_AGGREGATE": "Sdru\u017een\u00e9",
    "TFORMS_LABEL_DATE": "Datum",
    "WIDGET_YEARS": "Rok(y)",
    "FILTERS_LABEL_LT_TIME": "P\u0159ed (datum / \u010das)",
    "TRANSFORMS_COUNT": "Po\u010det",
    "WIDGET_REAL_DATE": "Re\u00e1ln\u00e9 datum",
    "OPERATORS_LT_TIME": "P\u0159ed (datum / \u010das)",
    "TFORMS_LABEL_MAX": "Max",
    "REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Pros\u00edm, zm\u011b\u0148te n\u00e1zev zpr\u00e1vy",
    "TEMPLATE_CONF_FALSE": "Nepravda",
    "TEMPLATE_CONF_BARE": "Pr\u00e1zdn\u00fd",
    "TRANSFORMS_LAST": "Posledn\u00ed hodnota",
    "TFORMS_LABEL_MIN": "Min",
    "REPORT_EDITOR_REPORT_FOLDERS": "Slo\u017eky zpr\u00e1v",
    "TEMPLATE_CONF_EQUALS": "Je roven",
    "REPORT_EDITOR_OUTPUT_FOLDERS": "V\u00fdstupn\u00ed slo\u017eky",
    "FILTERS_LABEL_NOT_BETWEEN": "Nen\u00ed mezi",
    "TRANSFORMS_QOY": "\u010ctvrtlet\u00ed",
    "REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Vyberte pros\u00edm v\u00fdstupn\u00ed slo\u017eku",
    "FILTERS_LABEL_GREATER_THAN": "V\u011bt\u0161\u00ed ne\u017e",
    "FILTERS_LABEL_NE_ANY": "Nen\u00ed roven \u017e\u00e1dn\u00e9mu",
    "SOURCE_BROWSE_NON_AGGREGATE": "Ne-sdru\u017een\u00e9",
    "OPERATORS_NE_ANY": "Nen\u00ed roven \u017e\u00e1dn\u00e9mu",
    "TRANSFORMS_AVERAGE": "Pr\u016fm\u011br",
    "FOLDERS_TEMPLATES": "\u0160ablony",
    "TFORMS_LABEL_DAY_NAME": "N\u00e1zev dne",
    "WIDGET_DAYS": "Den (dny)",
    "TRANSFORMS_ROUND": "Zaokrouhlit",
    "FOLDERS_TEMPLATE": "\u0160ablona",
    "TRANSFORMS_HOUR_TRUNC": "Hodina",
    "TFORMS_LABEL_HOUR_TRUNC": "Hodina",
    "TRANSFORMS_MOY": "M\u011bs\u00edc",
    "LINK_NULLABLE_NONE": "Hodnota nezad\u00e1na",
    "RPT_BUILDER_CONFIRM_SAVE": "Jm\u00e9no : ${0}\nPopis : ${1}\nUlo\u017eit \u0161ablonu?",
    "TFORMS_LABEL_DOY": "Den v roce",
    "TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Zm\u011bnit n\u00e1pov\u011bdu k poli na:",
    "TRANSFORMS_DATE": "Datum",
    "FOLDERS_REPORT": "Zpr\u00e1va",
    "TFORMS_LABEL_DOW": "Den v t\u00fddnu",
    "FILTERS_LABEL_LT_EQUAL": "Men\u0161\u00ed nebo rovno",
    "TFORMS_LABEL_INT": "O\u0159\u00edznout desetinn\u00e1 m\u00edsta",
    "OPERATORS_GTE_TIME": "V nebo po datu ( datum / \u010das)",
    "TFORMS_LABEL_DOM": "Den v m\u011bs\u00edci",
    "FOLDER_WINDOW_COLNAME_NONE": "Hodnota nezad\u00e1na",
    "REPORT_EDITOR_ENTER_NAME_ALERT": "Zadejte pros\u00edm n\u00e1zev zpr\u00e1vy",
    "OPERATORS_LT_EQUAL": "Men\u0161\u00ed nebo rovno",
    "TFORMS_LABEL_MONTHS_AGO": "P\u0159ed m\u011bs\u00edci",
    "TFORMS_LABEL_FIRST_WORD": "Prvn\u00ed n\u00e1sleduj\u00edc\u00ed \u0159et\u011bzec bez mezer",
    "FOLDER_WINDOW_REPORT_OUTPUT": "V\u00fdstup zpr\u00e1vy: ${0}",
    "FILTERS_LABEL_GTE_TIME": "V nebo po datu ( datum / \u010das)",
    "TFORMS_LABEL_FIRST": "Prvn\u00ed hodnota",
    "TRANSFORMS_AGE": "St\u00e1\u0159\u00ed",
    "FILTERS_LABEL_LIKE": "Obsahuje odpov\u00eddaj\u00edc\u00ed pod\u0159et\u011bzec",
    "TEMPLATE_CONF_TRUE": "Pravda",
    "SOURCE_SETUP_CONFIRM_EXIT": "Za\u010dali jste sestavovat \u0161ablonu!\n Vybr\u00e1n\u00edm nov\u00e9ho zdroje z datab\u00e1ze zru\u0161\u00edte sou\u010dasnou \u0161ablonu a za\u010dnete znovu s pr\u00e1zdnou \u0161ablonou. Je to v po\u0159\u00e1dku?",
    "TRANSFORMS_QUARTERS_AGO": "P\u0159ed \u010dtvrtlet\u00edmi",
    "TFORMS_LABEL_MONTH_TRUNC": "Rok + M\u011bs\u00edc",
    "TEMPLATE_CONF_IN": "Pole se shoduje s jedn\u00edm ze seznamu (odd\u011blen\u00fd \u010d\u00e1rkami):",
    "FILTERS_LABEL_ILIKE": "Obsahuje shoduj\u00edc\u00ed se pod\u0159et\u011bzec (bez ohledu na velikost p\u00edsma)",
    "FILTERS_LABEL_NOT_NULL": "Nen\u00ed NULL",
    "TEMPLATE_CONF_NO_MATCH": "Pole se neshoduje s jedn\u00edm ze seznamu (odd\u011blen\u00fd \u010d\u00e1rkami):",
    "TFORMS_LABEL_UPPER": "Velk\u00e1 p\u00edsmena",
    "TRANSFORMS_SUBSTRING": "Pod\u0159et\u011bzec",
    "FILTERS_LABEL_GT_EQUAL": "V\u011bt\u0161\u00ed nebo rovno",
    "TEMPLATE_CONF_RAW_DATA": "Nezpracovan\u00e1 data",
    "TFORMS_LABEL_HOD": "Hodina",
    "FILTERS_LABEL_NOT_NULL_BLANK": "Nen\u00ed NULL nebo pr\u00e1zdn\u00fd",
    "TFORMS_LABEL_SUM": "Suma",
    "LINK_NULLABLE_DEFAULT": "V\u00fdchoz\u00ed",
    "FILTERS_LABEL_IN": "V seznamu",
    "TFORMS_LABEL_AGE": "St\u00e1\u0159\u00ed",
    "FOLDER_WINDOW_CHANGE_FOLDERS": "Zm\u011bnit slo\u017eky",
    "TRANSFORMS_LOWER": "Mal\u00e1 p\u00edsmena",
    "TRANSFORMS_MONTH_NAME": "N\u00e1zev m\u011bs\u00edce",
    "TRANSFORMS_DOW": "Den v t\u00fddnu",
    "TEMPLATE_CONF_PROMPT_CHANGE": "Zm\u011bnit z\u00e1hlav\u00ed sloupce na: ${0}",
    "OPERATORS_NOT_BETWEEN": "Nen\u00ed mezi",
    "TRANSFORMS_DOY": "Den v roce",
    "REPORT_EDITOR_INVALID_DATE_ALERT": "neplatn\u00e9 datum zah\u00e1jen\u00ed - RRRR-MM-DD",
    "TRANSFORMS_BARE": "Nezpracovan\u00e1 data",
    "TRANSFORMS_DOM": "Den v m\u011bs\u00edci",
    "TFORMS_LABEL_MONTH_NAME": "N\u00e1zev m\u011bs\u00edce",
    "OPERATORS_EQ_ANY": "Je rovno kter\u00e9mukoliv",
    "TFORMS_LABEL_ROUND": "Zaokrouhlit",
    "OPERATORS_GREATER_THAN": "V\u011bt\u0161\u00ed ne\u017e",
    "SOURCE_SETUP_CORE_SOURCES": "Z\u00e1kladn\u00ed zdroje",
    "TFORMS_LABEL_LAST": "Posledn\u00ed hodnota",
    "FILTERS_LABEL_EQUALS": "Je roven",
    "FOLDER_WINDOW_COLNAME_ALL": "V\u0161e",
    "TFORMS_LABEL_RAW_DATA": "Nezpracovan\u00e1 data",
    "TFORMS_LABEL_COUNT_DISTINCT": "Po\u010d\u00edtadlo rozd\u00edl\u016f",
    "TFORMS_LABEL_FIRST5": "Prvn\u00edch 5 znak\u016f (Pro US PS\u010c)",
    "TEMPLATE_CONF_NOT_BETWEEN": "Hodnota pole nen\u00ed mezi (odd\u011bleno \u010d\u00e1rkou):",
    "TRANSFORMS_INT": "O\u0159\u00edznout desetinn\u00e1 m\u00edsta",
    "FILTERS_LABEL_LSE_TIME": "V nebo p\u0159ed (datum / \u010das)",
    "TRANSFORMS_DAY_NAME": "N\u00e1zev dne",
    "FOLDER_WINDOW_SELECT_ITEM": "Vyberte pros\u00edm polo\u017eku ze seznamu",
    "TRANSFORMS_FIRST5": "Prvn\u00edch 5 znak\u016f (Pro US PS\u010c)",
    "OPERATORS_LTE_TIME": "V nebo p\u0159ed (datum / \u010das)",
    "TEMPLATE_CONF_DEFAULT": "Hodnota ${0}:",
    "TFORMS_LABEL_YEAR_TRUNC": "Rok",
    "TRANSFORMS_WOY": "T\u00fdden v roce",
    "TFORMS_LABEL_WOY": "T\u00fdden v roce",
    "TFORMS_LABEL_QUARTERS_AGO": "P\u0159ed \u010dtvrtlet\u00edmi",
    "TEMPLATE_CONF_BOOLEAN_VALUE": "Booleovsk\u00e1 hodnota",
    "OPERATORS_NOT_NULL_BLANK": "Nen\u00ed NULL nebo pr\u00e1zdn\u00fd",
    "OPERATORS_NULL_BLANK": "Je NULL nebo pr\u00e1zdn\u00fd",
    "TEMPLATE_CONF_BETWEEN": "Hodnota pole je mezi (odd\u011bleno \u010d\u00e1rkou):",
    "TFORMS_LABEL_QOY": "\u010ctvrtlet\u00ed",
    "WIDGET_QUARTERS": "\u010ctvrtlet\u00ed",
    "OPERATORS_LESS_THAN": "Men\u0161\u00ed ne\u017e",
    "OPERATORS_BETWEEN": "Mezi"
}