{
    "and": "E",
    "sort": "Ordenar Axis",
    "bib_level": "N\u00edvel Catalogr\u00e1fico",
    "less": "...Menos",
    "item_form": "Forma",
    "site": "P\u00e1gina",
    "filters": "Filtros",
    "notcontains": "N\u00e3o Cont\u00e9m",
    "statuses": "Estados",
    "before": "Publicado antes",
    "new_facet": "Nova Faceta",
    "lit_form": "Forma Liter\u00e1ria",
    "faceted_searches": "Facetas",
    "contains": "Cont\u00e9m",
    "audience": "P\u00fablico",
    "filter_default": "-- Selecionar um filtro --",
    "metabib": "Pesquisa por Metaregistro",
    "basic": "B\u00e1sico",
    "new_modifier": "Novo Modificador",
    "staff": "Pesquisa de Funcion\u00e1rio",
    "classed_searches": "Pesquisas Classificadas",
    "more": "Mais ...",
    "available": "Dispon\u00edvel",
    "new_filter": "Novo Filtro",
    "format": "Tipo e Forma",
    "after": "Publicado depois",
    "ascending": "Ordenar em Ordem Crescente",
    "descending": "Ordenar em Ordem Decrescente",
    "modifier_default": "-- Selecione um Modificador --",
    "during": "Em Publica\u00e7\u00e3o",
    "exact": "Corresponde Exatamente",
    "between": "Publicador Entre",
    "advanced": "Avan\u00e7ado",
    "modifiers": "Modificadores",
    "perform_search": "Ir!",
    "remove": "Remover",
    "item_type": "Tipo",
    "depth": "Profundidade da Busca",
    "vr_format": "Formato da Grava\u00e7\u00e3o em V\u00eddeo",
    "or": "OU"
}