{
    "MARC_EDITOR_TITLE": "Record ID #${0}",
    "SELECT_MORE": "Click here to review all session URLs and/or select other URLs to verify",
    "CLONE_SESSION_NAME": "Copy of ${0}",
    "SESSION_NAME": "Session '${0}'",
    "CREATING": "Creating session ...",
    "MARC_EDITOR_LINK": "Click to open MARC Editor for this record",
    "EXTRACTING_URLS": "Extracting URLs ...",
    "INTERFACE_SETUP": "Setting up interface ...",
    "NOTHING_SELECTED": "No rows are selected, so no action will be taken.",
    "REREVIEW": "Open",
    "MARC_EDITOR_SAVE_RECORD": "Save Record",
    "REDIRECTING": "Loading next interface ...",
    "XPATH": "XPath",
    "SAVING_TAGS": "Saving tag/subfield selectors ...",
    "VERIFICATION_ATTEMPT_ID": "Verification attempt ID: ${0}",
    "VERIFICATION_DIALOG": "Verifying URLs ...",
    "EDIT": "Edit",
    "VERIFY_ALL": "Click 'OK' to verify ALL the URLs that belong to this session and match all your search terms.  Click 'Cancel' if the selected, visible URLs are the only ones you want verified.",
    "REVIEW_ATTEMPT": "Review this verification attempt",
    "CLONE_SESSION": "Clone",
    "CLONING": "Cloning existing session ...",
    "PERFORMING_SEARCH": "Performing search ...",
    "NEED_UVUS": "You must add some tag and subfield combinations."
}