{
    "PWD_RESET_SUBMIT_ERROR": "J\u00e4rjestelm\u00e4 ei pystynyt k\u00e4sittelem\u00e4\u00e4n salasanan uusintapyynt\u00f6\u00e4si. Yrit\u00e4 uudelleen tai ota yhteytt\u00e4 lainaushenkil\u00f6kuntaan, jos tarvitset apua.",
    "PWD_RESET_SUBMIT_SUCCESS": "Salasanan uusintapyynt\u00f6\u00e4si k\u00e4sitell\u00e4\u00e4n. Jos tiliisi on liitetty kelvollinen s\u00e4hk\u00f6postiosoite, saat pian s\u00e4hk\u00f6postin, jossa on lis\u00e4ohjeita salasanan uusimisesta.",
    "USERNAME_PROMPT": "K\u00e4ytt\u00e4j\u00e4tunnus: ",
    "HOLD_STATUS_PLURAL": "varaus # ${0} / ${1} varauksesta yhteens\u00e4 ja ${2} mahdollisesta niteest\u00e4",
    "HOLDINGS_TABLE_CAPTION": "Varausten yhteenveto (${0})",
    "INDEX_HOLDINGS": "Hakemistot",
    "EDIT_MFHD_RECORD": "Muokkaa tietuetta",
    "MISSING_VOLUMES": "Puuttuvat vuosikerrat",
    "DELETED_MFHD_RECORD": "MFHD-tietue ${0} tuhottu",
    "SUBMIT_BUTTON_LABEL": "L\u00e4het\u00e4",
    "CREATED_MFHD_RECORD": "MFHD-tietue luotu kohteelle ${0}",
    "CURRENT_INDEXES": "Nykyiset hakemistot",
    "BARCODE_PROMPT": "Asiakastunnus: ",
    "PWD_RESET_RESPONSE_TITLE": "Salasanan uusintavastaus",
    "SOURCE_CANNOT_HAVE_COPIES": "Tietueisiin kohteesta ${0} ei voi kuulua niteit\u00e4.",
    "CURRENT_SUPPLEMENTS": "Nykyiset t\u00e4ydennykset",
    "ONLINE_VOLUMES": "Online-tilassa olevat vuosikerrat",
    "DELETE_MFHD": "Tuhoa tietue",
    "CREATE_MFHD": "Lis\u00e4\u00e4 MFHD-tietue",
    "EDIT_PROPERTIES": "Muokkaa ominaisuuksia",
    "CANCEL_BUTTON_LABEL": "Peruuta",
    "CURRENT_HOLDINGS": "Nykyinen vuosikerta",
    "MORE_COPIES_FULL_RECORD": "... lis\u00e4\u00e4 kappaleita listattu t\u00e4ydess\u00e4 tietueessa",
    "SUPPLEMENT_HOLDINGS_ADD": "Ylim\u00e4\u00e4r\u00e4iset t\u00e4ydennystiedot",
    "INCOMPLETE_VOLUMES": "Ep\u00e4t\u00e4ydelliset vuosikerrat",
    "SAVE_MFHD_LABEL": "Tallenna MFHD",
    "OK": "OK",
    "INDEX_HOLDINGS_ADD": "Ylim\u00e4\u00e4r\u00e4iset hakemistotiedot",
    "PWD_RESET_FORGOT_PROMPT": "Unohditko salasanasi?",
    "PWD_RESET_FORM_TITLE": "Pyyd\u00e4 salasanan uusintaa",
    "PWD_RESET_SUBMIT_PROMPT": "Jos haluat aloittaa salasanan uusimisen, sy\u00f6t\u00e4 joko asiakastunnus/k\u00e4ytt\u00e4j\u00e4tunnus alla olevaan lomakkeeseen ja napsauta 'L\u00e4het\u00e4'",
    "HOLD_STATUS_SINGULAR": "varaus # ${0} / ${0} varauksesta yhteens\u00e4 ja ${2} mahdollisesta niteest\u00e4",
    "PWD_RESET_SUBMIT_STATUS": "L\u00e4hetet\u00e4\u00e4n pyynt\u00f6\u00e4...",
    "DELETE_MFHD_CONFIRM": "Haluatko varmasti tuhota kausijulkaisutietueen?",
    "PLACE_HOLD": "Varaa",
    "BASIC_HOLDINGS": "Niteet",
    "EDIT_MFHD_MENU": "Muokkaa varauksia",
    "BASIC_HOLDINGS_ADD": "Ylim\u00e4\u00e4r\u00e4iset teostiedot",
    "SUPPLEMENT_HOLDINGS": "T\u00e4ydennykset",
    "MORE": "Lis\u00e4\u00e4"
}