{
    "NO_PAYLOAD": "We did not receive further information from the server about this attempt to capture.",
    "TITLE": "Titel",
    "PRINT": "<u>P</u>rint",
    "AUTO_resource_barcode": "Barcode eingeben:",
    "DURATION": "Reserviert von",
    "NEEDS_ROUTED_TO": "This item need to be routed to",
    "PRINTED_BY": "Gedruckt von",
    "CAPTURE_TRANSIT_SOURCE": "Von:",
    "CAPTURE_INFO": "Capture Information",
    "AUTO_ATTR_VALUE_capture": "Erfassen",
    "AUTHOR": "Autor",
    "CAPTURE_BRESV_BRSRC": "Quelle f\u00fcr den Barcode",
    "SLIP_DATE": "Slip date",
    "RESERVATION_SHELF": "RESERVATION SHELF",
    "UNKNOWN_PROBLEM": "An unknown problem occurred during capture attempt.",
    "FAILURE": "Aufnahme fehlgeschlagen",
    "CAPTURE_CAUSES_TRANSIT": "This item is now in transit!",
    "RESERVED": "F\u00fcr Kunde Vorgemerkt",
    "SUCCESS": "Aufnahme erfolgreich",
    "REQUEST": "Request time",
    "AT": "auf",
    "CAPTURE_BRESV_PICKUP_LIB": "Pickup library:",
    "CAPTURED_NOTHING": "Es wurde nichts erfasst.",
    "TRANSIT": "*** TRANSIT ***",
    "BARCODE": "Strichcode",
    "AUTO_pickup_lib_selector": "Pickup library:",
    "CAPTURE_TRANSIT_DEST": "An:",
    "PRINT_ACCESSKEY": "P",
    "CAPTURE_BRESV_DATES": "Datum der Vormerkung:",
    "HERES_WHAT_WE_KNOW": "The following information is available about the failed capture:",
    "AUTO_capture_heading": "Capture Reserved Resources"
}