{
    "COPY_LOOKUP_NO_RESPONSE": "Keine Antwort beim Suchen von Kopien via Barcode:",
    "AUTO_th_call_number": "Signatur",
    "FOR": "f\u00fcr",
    "AUTO_th_copy_location": "Ort kopieren",
    "AUTO_owning_lib_selector": "See pull list for library:",
    "AUTO_interval_in_days": "Erzeuge eine Liste f\u00fcr  so viele Tage da: ",
    "AUTO_th_title_or_name": "Titel oder Name",
    "AUTO_th_barcode": "Strichcode",
    "PULL_LIST_NO_RESPONSE": "Keine Antwort f\u00fcr die \"pull list\" vom Server bekommen!",
    "COPY_MISSING": "Unerwarteter Fehler: Keine Informationen f\u00fcr die Kopie: ",
    "AUTO_ATTR_VALUE_fetch": "Abrufen",
    "PULL_LIST_ERROR": "Error trying to fetch pull list: ",
    "AT": "at",
    "AUTO_ATTR_VALUE_print": "Drucken",
    "AUTO_th_pickup_lib": "Pickup library",
    "AUTO_th_resv_details": "Reservierungsdetails",
    "COPY_LOOKUP_ERROR": "Fehler beim Suchen von Kopien via Barcode: ",
    "AUTO_no_results": "Keine Ergebnisse.",
    "AUTO_pull_list_title": "Booking Pull List"
}