{
    "AUTO_ATTR_VALUE_button_cancel_existing": "Cancel selected",
    "AUTO_ATTR_VALUE_reserve_brsrc": "Ausgew\u00e4hlte vormerken",
    "AUTO_ATTR_VALUE_next": "Weiter",
    "HERE_ARE_EXISTING_BRESV": "Vorhandene Vormerkungen f\u00fcr",
    "AUTO_email_notify": "Send email notification when resource is available for pickup.",
    "ON_FLY_ERROR": "Error attempting to make item a bookable resource:",
    "AUTO_ATTR_VALUE_button_edit_existing": "Ausgew\u00e4hlte bearbeiten",
    "AUTO_ending_at": "und",
    "AUTO_arbitrary_resource": "Enter the barcode of a cataloged, bookable resource:",
    "NO_BRT_RESULTS": "There are no bookable resource types registered.",
    "AUTO_ATTR_VALUE_reserve_brt": "Reserve Any",
    "AUTO_brt_noncat_only": "Show only non-cataloged bookable resource types",
    "OUTSTANDING_BRESV": "Ausstehende Vormerkungen f\u00fcr Kunde",
    "INVALID_TS_RANGE": "Sie m\u00fcssen eine g\u00fcltige Start- und End-Zeit f\u00fcr die Vormerkung angeben.",
    "AUTO_or": "- Oder -",
    "CREATE_BRESV_OK_MISSING_TARGET_WILL_CANCEL": "Since the requested resource could not be targeted, this\nreservation will now be canceled.",
    "ERROR_FETCHING_AOUS": "Could not retrieve organizational unit settings.\nThis is a non-fatal error, but you may wish to\ncontact your system administrator.",
    "NEED_EXACTLY_ONE_BRT_PASSED_IN": "Can't book multiple resource types at once",
    "CXL_BRESV_SUCCESS": "${0} Vormerkung(en) gel\u00f6scht",
    "UNTARGETED": "None targeted",
    "CREATE_BRESV_SERVER_ERROR": "Server-Fehler beim Anlegen der Vormerkung: ",
    "ON_FLY_NO_RESPONSE": "No response from server attempting to make item a bookable resource.",
    "AUTO_patron_barcode": "Reserve to patron barcode:",
    "NO_EXISTING_BRESV": "Dieser Benutzer hat zur Zeit keine ausstehenden Vormerkungen.",
    "GET_BRESV_LIST_ERR": "Fehler beim Empfangen der Vormerkungs-Liste: ",
    "AUTO_explain_bookable": "To reserve an item that is not yet registered as a bookable resource, find it in the catalog or under <em>Display Item</em>, and select <em>Make Item Bookable</em> or <em>Book Item Now</em> there.",
    "NO_TARG_DIV": "Could not find target div",
    "CREATE_BRESV_SERVER_NO_RESPONSE": "Keine Antwort des Servers auf den Versuch eine Vormerkung zu erstellen.",
    "AUTO_bresv_grid_type": "Typ",
    "AUTO_choose_a_brt": "Choose a Bookable Resource Type",
    "NO_BRA_RESULTS": "Couldn't retrieve booking resource attributes.",
    "AUTO_i_need_this_resource": "I need this resource...",
    "AUTO_bresv_grid_end_time": "End time",
    "BRSRC_NOT_FOUND": "Could not locate that resource.",
    "AUTO_starting_at": "Zwischen",
    "CXL_BRESV_FAILURE2": "Fehler beim L\u00f6schen der Vormerkungen:\n",
    "CREATE_BRESV_OK_MISSING_TARGET": "Created ${0} reservation(s), but ${1} of these could not target any resources.\n\nThis means that it won't be possible to fulfill some of these\nreservations until a suitable resource becomes available.",
    "CREATE_BRESV_OK": "${0} Vormerkungen erstellt",
    "CREATE_BRESV_LOCAL_ERROR": "Fehler beim Anlegen der Vormerkung: ",
    "GET_BRESV_LIST_NO_RESULT": "No results from server retrieving reservation list.",
    "BRSRC_RETRIVE_ERROR": "Error retrieving resource: ",
    "AUTO_bresv_grid_resource": "Quelle",
    "WHERES_THE_BARCODE": "Barcode des Kunden eingeben, um eine Vormerkung vorzunehmen",
    "AUTO_pickup_lib_selector": "Choose the pickup library for this reservation:",
    "NO_USABLE_BRSRC": "No reservable resources.  Adjust start and end time\nuntil a resource is available for reservation.",
    "CREATE_BRESV_OK_MISSING_TARGET_BLOCKED_BY_CIRC": "The desired reservation(s) are blocked by circulation(s) with the following due date(s):\n${0}",
    "CXL_BRESV_SELECT_SOMETHING": "Sie haben keine Vormerkungen zum L\u00f6schen ausgew\u00e4hlt.",
    "COULD_NOT_RETRIEVE_BRT_PASSED_IN": "Error retrieving booking resource type",
    "CXL_BRESV_FAILURE": "Fehler beim L\u00f6schen der Vormerkungen; Server antwortet nicht.",
    "ACTOR_CARD_NOT_FOUND": "Barcode des Kunden wurde nicht gefunden. Bitte nochmal probieren.",
    "SELECT_A_BRSRC_THEN": "You have clicked 'Reserve Selected', but nothing is selected!\n\nYou must select a resource from the large box above.\n\n***  If resources that you would select are highlighted in RED, ***\nthese items are not available during the requested time; if\npossible, choose another resource or change the reservation time.",
    "GET_PATRON_NO_RESULT": "Server antwortet nicht auf den Versuch, den Kunden mit seinem Barcode zu finden.",
    "AUTO_with_these_attr": "Mit diesen Attributen:",
    "ANY": "ANY",
    "AUTO_bresv_grid_start_time": "Start time"
}