{
    "NO_PAYLOAD": "Palvelin ei antanut muita tietoja t\u00e4st\u00e4 kiinnitysyrityksest\u00e4.",
    "TITLE": "Nimeke",
    "PRINT": "Tulosta (<u>P</u>)",
    "AUTO_resource_barcode": "Sy\u00f6t\u00e4 tunnus:",
    "DURATION": "Varattu kohteesta",
    "NEEDS_ROUTED_TO": "T\u00e4m\u00e4 nide on kuljetettava kohteeseen",
    "PRINTED_BY": "Tulostanut:",
    "CAPTURE_TRANSIT_SOURCE": "L\u00e4hett\u00e4j\u00e4:",
    "CAPTURE_INFO": "Kiinnitystiedot",
    "AUTO_ATTR_VALUE_capture": "Kiinnit\u00e4",
    "AUTHOR": "Tekij\u00e4",
    "CAPTURE_BRESV_BRSRC": "Aineiston tunnus:",
    "SLIP_DATE": "Liuskan p\u00e4iv\u00e4ys",
    "RESERVATION_SHELF": "VARAUSHYLLY",
    "UNKNOWN_PROBLEM": "Kiinnitysyrityksess\u00e4 ilmeni tuntematon ongelma.",
    "FAILURE": "Kiinnitys ep\u00e4onnistui",
    "CAPTURE_CAUSES_TRANSIT": "T\u00e4m\u00e4 nide on kuljetettavana!",
    "RESERVED": "Varattu asiakkaalle",
    "SUCCESS": "Kiinnitys onnistui",
    "REQUEST": "Pyynt\u00f6aika",
    "AT": "kohteessa",
    "CAPTURE_BRESV_PICKUP_LIB": "Noutokirjasto:",
    "CAPTURED_NOTHING": "Mit\u00e4\u00e4n ei kiinnitetty.",
    "TRANSIT": "*** KULJETETTAVANA ***",
    "BARCODE": "Tunnus",
    "AUTO_pickup_lib_selector": "Noutokirjasto:",
    "CAPTURE_TRANSIT_DEST": "Vastaanottaja:",
    "PRINT_ACCESSKEY": "P",
    "CAPTURE_BRESV_DATES": "Erikoisvarauksen aika:",
    "HERES_WHAT_WE_KNOW": "Ep\u00e4onnistuneesta kiinnityksest\u00e4 on saatavilla seuraavat tiedot:",
    "AUTO_capture_heading": "Kiinnit\u00e4 varatut aineistot"
}