{
    "AUTO_ATTR_VALUE_button_cancel_existing": "Peruutus valittu",
    "AUTO_ATTR_VALUE_reserve_brsrc": "Varaa valitut",
    "AUTO_ATTR_VALUE_next": "Seuraava",
    "HERE_ARE_EXISTING_BRESV": "Olemassaolevat erikoisvaraukset asiakkaalle",
    "AUTO_email_notify": "L\u00e4het\u00e4 ilmoitus s\u00e4hk\u00f6postilla, kun aineisto on noudettavissa.",
    "ON_FLY_ERROR": "Varattavan aineiston luominen niteest\u00e4 ep\u00e4onnistui:",
    "AUTO_ATTR_VALUE_button_edit_existing": "Muokkaa valittuja",
    "AUTO_ending_at": "ja",
    "AUTO_arbitrary_resource": "Sy\u00f6t\u00e4 tietokannassa olevan, varattavissa olevan aineiston nidetunnus:",
    "NO_BRT_RESULTS": "Varattavia aineistotyyppej\u00e4 ei ole rekister\u00f6ity.",
    "AUTO_ATTR_VALUE_reserve_brt": "Varaa mik\u00e4 tahansa",
    "AUTO_brt_noncat_only": "N\u00e4yt\u00e4 vain ei-luetteloidut varattavissa olevat ainestotyypit",
    "OUTSTANDING_BRESV": "Asiakkaan voimassaolevat erikoisvaraukset",
    "INVALID_TS_RANGE": "Erikoisvaraukselle on valittava kelvollinen aloitus- ja lopetusaika",
    "AUTO_or": "- Tai -",
    "CREATE_BRESV_OK_MISSING_TARGET_WILL_CANCEL": "Koska pyydetty\u00e4 aineistoa ei voitu ottaa kohteeksi,\nerikoisvaraus perutaan.",
    "ERROR_FETCHING_AOUS": "Organisaatioyksik\u00f6n asetusten haku ep\u00e4onnistui. \nVirhe ei ole kriittinen, mutta ota halutessasi\nyhteytt\u00e4 j\u00e4rjestelm\u00e4n yll\u00e4pit\u00e4j\u00e4\u00e4n.",
    "NEED_EXACTLY_ONE_BRT_PASSED_IN": "Eri aineistotyyppien varaus ei onnistu yhdell\u00e4 kertaa",
    "CXL_BRESV_SUCCESS": "${0} erikoisvaraus(ta) peruttiin",
    "UNTARGETED": "Ei kohteita",
    "CREATE_BRESV_SERVER_ERROR": "Erikoisvarausta tehdess\u00e4 ilmeni palvelinvirhe: ",
    "ON_FLY_NO_RESPONSE": "Palvelin ei vastannut, kun niteest\u00e4 yritettiin tehd\u00e4 varattava aineisto.",
    "AUTO_patron_barcode": "Varaa asiakastunnukselle:",
    "NO_EXISTING_BRESV": "T\u00e4ll\u00e4 k\u00e4ytt\u00e4j\u00e4ll\u00e4 ei ole erikoisvarauksia t\u00e4ll\u00e4 hetkell\u00e4",
    "GET_BRESV_LIST_ERR": "Virhe varauslistan haussa: ",
    "AUTO_explain_bookable": "Jos haluat varata niteen, jota ei ole viel\u00e4 rekister\u00f6ity varattavaksi aineistoksi, etsi se tietokannasta tai <em>N\u00e4yt\u00e4 nide</em>-valinnan kautta, ja valitse sitten <em>Tee niteest\u00e4 varattava</em> tai <em>Varaa nide nyt</em>.",
    "NO_TARG_DIV": "Kohdeosastoa ei l\u00f6ytynyt",
    "CREATE_BRESV_SERVER_NO_RESPONSE": "Palvelin ei vastannut, kun erikoisvarausta yritettiin luoda.",
    "AUTO_bresv_grid_type": "Tyyppi",
    "AUTO_choose_a_brt": "Valitse varattavissa oleva aineistotyyppi",
    "NO_BRA_RESULTS": "Varausaineiston m\u00e4\u00e4ritteiden haku ei onnistunut.",
    "AUTO_i_need_this_resource": "Tarvitsen aineiston...",
    "AUTO_bresv_grid_end_time": "Lopetusaika",
    "BRSRC_NOT_FOUND": "Aineistoa ei l\u00f6ytynyt.",
    "AUTO_starting_at": "V\u00e4lill\u00e4",
    "CXL_BRESV_FAILURE2": "Virhe erikoisvarausten peruutuksessa:\n",
    "CREATE_BRESV_OK_MISSING_TARGET": "${0} erikoisvaraus(ta) luotiin, mutta $1 niist\u00e4 j\u00e4i ilman kohdeaineistoa.\n\nViimeksi mainittuja erikoisvarauksia ei voida t\u00e4ytt\u00e4\u00e4,\nennen kuin sopiva aineisto on lainattavissa.",
    "CREATE_BRESV_OK": "${0} erikoisvaraus(ta) luotiin",
    "CREATE_BRESV_LOCAL_ERROR": "Erikoisvarausta tehdess\u00e4 ilmeni poikkeus: ",
    "GET_BRESV_LIST_NO_RESULT": "Varauslistaa hakeva palvelin ei antanut tuloksia.",
    "BRSRC_RETRIVE_ERROR": "Aineiston haku ep\u00e4onnistui: ",
    "AUTO_bresv_grid_resource": "Aineisto",
    "WHERES_THE_BARCODE": "Tee erikoisvaraus sy\u00f6tt\u00e4m\u00e4ll\u00e4 asiakastunnus",
    "AUTO_pickup_lib_selector": "Valitse noutokirjasto t\u00e4lle erikoisvaraukselle:",
    "NO_USABLE_BRSRC": "Ei varattavissa olevia aineistoja. Muuta aloitus- ja lopetusaikaa, kunnes aineisto on varattavissa.",
    "CREATE_BRESV_OK_MISSING_TARGET_BLOCKED_BY_CIRC": "Pyydettyjen varausten esteen\u00e4 ovat lainat, joiden er\u00e4p\u00e4iv\u00e4t ovat seuraavat:\n${0}",
    "CXL_BRESV_SELECT_SOMETHING": "Et ole valinnut yht\u00e4\u00e4n erikoisvarausta peruttavaksi.",
    "COULD_NOT_RETRIEVE_BRT_PASSED_IN": "Varausaineiston tyypin haku ep\u00e4onnistui",
    "CXL_BRESV_FAILURE": "Virhe varausten perumisessa; palvelin on hiljaa.",
    "ACTOR_CARD_NOT_FOUND": "Asiakastunnusta ei l\u00f6ydy. Yrit\u00e4 uudelleen.",
    "SELECT_A_BRSRC_THEN": "Olet napsauttanut 'Varaa valitut', mutta mit\u00e4\u00e4n ei ole valittuna!\n\nSinun on valittava aineisto yll\u00e4 olevasta suuresta laatikosta.\n\n***  Jos haluamasi aineistot on korostettu PUNAISELLA, ***\nse tarkoittaa, etteiv\u00e4t niteet ole t\u00e4ll\u00e4 hetkell\u00e4 lainattavissa; jos\nmahdollista, valitse toinen aineisto tai muuta varausaikaa.",
    "GET_PATRON_NO_RESULT": "Palvelin ei vastannut, kun asiakasta yritettiin etsi\u00e4 asiakastunnuksen perusteella.",
    "AUTO_with_these_attr": "N\u00e4ill\u00e4 m\u00e4\u00e4ritteill\u00e4:",
    "ANY": "MIK\u00c4 TAHANSA",
    "AUTO_bresv_grid_start_time": "Aloitusaika"
}