{
    "NO_LID_TO_CLAIM": "Vous n\u2019avez s\u00e9lectionn\u00e9 aucun d\u00e9tail de l\u2019article pour lequel une demande de r\u00e9clamation est pr\u00e9sent\u00e9e.",
    "LI_BATCH_UPDATE": "Line item batch update",
    "PO_ALREADY_ACTIVATED": "Activated",
    "VENDOR_SAYS_PREPAY_NOT_NEEDED": "Selon les dossiers, le fournisseur s\u00e9lectionn\u00e9 n\u2019exige pas n\u00e9cessairement \nun paiement anticip\u00e9. Exiger quand m\u00eame un paiement anticip\u00e9 pour ce BdC\u00a0?",
    "INVOICE_COPY_COUNT_INFO": "Copies received on this invoice: ${0} out of ${1}.",
    "DELETE_LI_COPIES_CONFIRM": "Cela aura pour effet de supprimer les derniers ${0} exemplaires dans le tableau. Voulez-vous continuer?",
    "CHANGE_CLAIM_POLICY": "Modifier la politique relative aux r\u00e9clamations",
    "ALERT_UNSELECTED": "Vous devez choisir un code d\u2019alerte.",
    "NUM_CLAIMS_EXISTING": "R\u00e9clamations (${0} existantes)",
    "FINALIZE_PO": "Finalize this blanket PO?\nThis will disencumber all blanket charges and mark the PO as received",
    "DFA_TIP": "<strong>R\u00e9alis\u00e9(e) par</strong> : ${0}<br /><strong>Date :</strong>: ${1}",
    "CREATE_PO_INVALID": "A purchase order must have an ordering agency and a provider.",
    "INVOICE_NUMBER": "Invoice #${0}",
    "ACTIVATE_VQBR_PROCESSED": "Vandelay Records Processed: ${0}",
    "PO_CANCEL_CONFIRM": "\u00cates-vous CERTAIN de vouloir annuler ce bon de commande?",
    "ACQ_SEARCH_CLASS_ABBR_acqinv": "I",
    "FUND_LIST_ROLLOVER_SUMMARY": "R\u00e9partition des fonds &amp; sommaire du refinancement pour l\u2019exercice ${0}",
    "NO_LI_TO_CLAIM": "Vous n\u2019avez s\u00e9lectionn\u00e9 aucun article pour lequel une demande de r\u00e9clamation est pr\u00e9sent\u00e9e.",
    "INVOICE_CONFIRM_ENTRY_DETACH": "Supprimer les frais $${0} pour l\u2019article '${1}, ${2} [${3}] de la facture?",
    "PO_FUND_WARNING_CONFIRM": "\u00cates-vous certain? Avez-vous vu le message d\u2019avertissement concernant la suraffectation d\u2019un fonds?",
    "NOT_RECVD": "Pas re\u00e7u",
    "UNRECEIVE_LID": "\u00cates-vous certain de vouloir signaler cet exemplaire comme NON re\u00e7u?",
    "INVOICE_IDENT_COLLIDE": "There is already an invoice in the system with the given combination of 'Vendor Invoice ID' and 'Provider,' which is not allowed.",
    "INVOICE_ITEM_DETAILS": "${0} <br/> ${1} <br/> ${2}. <br/> Estimation du prix : $${3}. <br/> Identification de l\u2019article : ${4} <br/> Bon de commande : ${5} <br/> Date de la commande : ${6}",
    "PO_ACTIVATING": "Activating purchase order...",
    "PO_CHECKING": "[Un instant...]",
    "YES": "Oui",
    "INVOICE_EXTRA_COPIES": "Vous tentez de facturer <b>${0}</b> un nombre d\u2019exemplaires plus \u00e9lev\u00e9 que celui command\u00e9 au d\u00e9part. <br/><br/>Pour ajouter ces articles \u00e0 la commande initiale, s\u00e9lectionner un fonds et choisir \u00ab Ajouter un nouvel article \u00bb ci-dessous. <br/>Apr\u00e8s avoir sauvegard\u00e9 la facture, vous pouvez terminer la modification et l\u2019importation de nouveaux exemplaires \u00e0 la page des d\u00e9tails de l\u2019article.",
    "ADD_LI_TO_PO_BAD_LI_STATE": "The selected lineitem is not in a state that can be added to a purchase order",
    "CANCEL_REASON": "Annuler le motif",
    "ACTIVATE_BIBS_PROCESSED": "Bib Records Merged/Imported: ${0}",
    "RECVD": "Re\u00e7u(e)",
    "EXPORT_SHORT_LIST": "Les articles s\u00e9lectionn\u00e9s ne poss\u00e8dent pas tous l\u2019attribut '${0}'.\nAppuyer sur OK pour sauvegarder les valeurs qui n\u2019ont pas pu \u00eatre rep\u00e9r\u00e9es.",
    "LOAD_TERMS_FIRST": "Vous ne pouvez pas r\u00e9cup\u00e9rer les dossiers tant que vous n\u2019avez pas charg\u00e9 un fichier en format CSV comportant \ndes identifications bibliographiques dans la premi\u00e8re colonne.",
    "PRINT": "Imprim\u00e9",
    "ACTIVATE_LID_PROCESSED": "ACQ Copies Processed: ${0}",
    "PO_NAME_OPTIONAL": "${0} (optional)",
    "JUST_NOW": "Maintenant seulement",
    "LI_CREATING_ASSETS": "Creating bib, call number, and copy records...",
    "ACQ_SEARCH_CLASS_ABBR_acqlid": "LID",
    "ACQ_SEARCH_CLASS_ABBR_acqlia": "LIA",
    "PO_WARNING_NO_BLOCK_ACTIVATION": "Oui. Le fonds ${0} (${1}) serait consign\u00e9 au-del\u00e0 de son niveau d\u2019avertissement.",
    "CONFIRM_FUNDS_AT_STOP": "Le solde d\u2019un ou de plusieurs des fonds s\u00e9lectionn\u00e9s est inf\u00e9rieur \u00e0 son niveau d\u2019arr\u00eat. \\nVous pourriez ne pas pouvoir activer les bons de commande qui comprennent ces exemplaires.\\nVoulez-vous continuer?",
    "LID_CANCEL_CONFIRM": "\u00cates-vous CERTAIN de vouloir annuler cet exemplaire?",
    "CONFIRM_LI_ALERT": "Une alerte a \u00e9t\u00e9 activ\u00e9e pour l\u2019article intitul\u00e9 ,\\n\\\"${0}\\\":\\n\\n${1}\\n${2}\\n${3}\\n. Appuyer sur OK si vous d\u00e9sirez accuser r\u00e9ception de cette alerte.",
    "CONFIRM_FUNDS_AT_WARNING": "Le solde d\u2019un ou de plusieurs des fonds s\u00e9lectionn\u00e9s est inf\u00e9rieur \u00e0 son niveau d\u2019avertissement.\nVoulez-vous continuer?",
    "VENDOR_PUBLIC": "FOURNISSEUR : PUBLIC",
    "INVOICE_CONFIRM_ITEM_DELETE": "Supprimer ces frais $${0} '${1}' de la facture?",
    "DUPE_PO_NAME_MSG": "This name is already in use by another PO",
    "ROLLBACK_PO_RECEIVE_CONFIRM": "Cela aura pour effet d\u2019annuler la r\u00e9ception de tous les exemplaires pour ce bon de commande.\n\nVoulez-vous continuer?",
    "UR_FILTER_USER": "Enter barcode for user (or leave blank to unset the filter):",
    "FUND_LIST_ROLLOVER_SUMMARY_ROLLOVER_AMOUNT": "<b>$${1}</b> les fonds non d\u00e9pens\u00e9s sont prolong\u00e9s \u00e0 l\u2019exercice ${0} pour les emplacements s\u00e9lectionn\u00e9s.",
    "EXPORT_SAVE_DIALOG_TITLE": "Sauvegarder les valeurs de champ dans un fichier",
    "PO_STOP_BLOCKS_ACTIVATION": "Non. Les fonds ${0} (${1}) seraient consign\u00e9s au-del\u00e0 de leur niveau d\u2019arr\u00eat.",
    "UR_FILTER_LINEITEM": "Enter id for lineitem (or leave blank to unset the filter):",
    "UR_CANCEL_CONFIRM": "\u00cates-vous CERTAIN de vouloir annuler cette demande d\u2019un usager?",
    "PREPAYMENT_REQUIRED_REMINDER": "Ce bon de commande n\u00e9cessite un paiement anticip\u00e9. \u00cates-vous certain d\u2019\u00eatre pr\u00eat \u00e0 l\u2019activer?",
    "SELECT_SEARCH_FIELD": "S\u00e9lectionnez le champ de recherche",
    "LIBRARY_INITIATED": "Librairie initi\u00e9e",
    "CONFIRM_DELETE_MAPPING": "\u00cates-vous certain de vouloir supprimer cette \u00e9tiquette de ce fonds?",
    "COULD_NOT_CREATE_MAPPING": "Une erreur s\u2019est produite lors de l\u2019\u00e9tiquetage du fonds.",
    "EXPORT_EMPTY_LIST": "Aucun r\u00e9sultat pour l\u2019attribut '${0}'",
    "DFA_NOT_ALL": "Impossible d\u2019enregistrer toutes vos applications des formules de distribution.",
    "INVOICE_ITEM_PO_DETAILS": "<b>${0}</b><br/><a href='${1}/achat/bon de commande/affichage/${2}'>Num\u00e9ro du bon de commande${3} ${4}</a><br/>Estimation du co\u00fbt total : $${5}",
    "ONE_LI_ATTR_SEARCH_AT_A_TIME": "Il n\u2019est pas possible de chercher une valeur d\u2019attribut et un fichier t\u00e9l\u00e9charg\u00e9 des termes en m\u00eame temps.",
    "ITS_YOU": "Vous",
    "OUT_OF_COPIES": "Vous avez appliqu\u00e9 les formules de distribution \u00e0 tous les exemplaires.",
    "NO_PO_RESULTS": "Aucun r\u00e9sultat",
    "ACTIVATE_DEBITS_ACCRUED_PROCESSED": "Debits Encumbered: ${0}",
    "NO": "Non",
    "NEW_INVOICE": "New Invoice",
    "UNRECEIVE_LI": "\u00cates-vous certain de vouloir indiquer cet article comme NON re\u00e7u?",
    "APPLY": "Appliquer",
    "UNNAMED": "Sans nom",
    "INVOICE_ITEM_PO_LABEL": "<b>${0}</b><br/><a href='${1}/achat/bon de commande/affichage/${2}'>Num\u00e9ro du bon de commande${3} ${4}</a><br/>Estimation du co\u00fbt total : $${5}",
    "PO_ACTIVATED_ON": "Activ\u00e9(e) ${0}",
    "LI_ATTR_SEARCH_TOO_LARGE": "Ce fichier est trop volumineux pour cette op\u00e9ration.",
    "LI_ATTR_SEARCH_CHOOSE_FILE": "S\u00e9lectionner un fichier ainsi que des crit\u00e8res de recherche",
    "NO_LI_GENERAL": "You have not selected any (suitable) line items.",
    "ACTIVATE_COPIES_PROCESSED": "Real Copies Processed: ${0}",
    "ROLLBACK_LI_RECEIVE_CONFIRM": "Cela aura pour effet d\u2019annuler la r\u00e9ception de tous les exemplaires pour ce bon de commande.\n\nVoulez-vous continuer?",
    "NO_LI_TO_UPDATE": "Vous n\u2019avez s\u00e9lectionn\u00e9 aucun article pour lequel une demande de r\u00e9clamation est pr\u00e9sent\u00e9e.",
    "EXPLAIN_DFA_MGMT": "Supprimer le dossier de ce type de formule de distribution?",
    "FUND_NOT_YET_LOADED": "Les fonds ne sont pas encore charg\u00e9s. Essayer d\u2019acc\u00e9der plus tard \u00e0 cet \u00e9cran.",
    "NO_FIND_INVOICE": "Impossible de trouver cette facture.",
    "PO_COULD_ACTIVATE": "Oui",
    "DEL_LI_FROM_PO": "That item has already been ordered!  Deleting it now will not revoke or modify any order that has been placed with a vendor.  Deleting the item may put the system's idea of your purchase order in a state that is inconsistent with reality.  Are you sure you mean to do this?",
    "XUL_RECORD_DETAIL_PAGE": "D\u00e9tails sur le dossier",
    "INVOICES": "Factures",
    "PO_HEADING_ERROR": "Probl\u00e8me non pr\u00e9vu lors de la mise au point d\u2019un bon de commande virtuel combin\u00e9",
    "VENDOR_SAYS_PREPAY_NEEDED": "Selon les dossiers, le fournisseur s\u00e9lectionn\u00e9 exige un paiement anticip\u00e9.\nProc\u00e9der quand m\u00eame sans exiger un paiement anticip\u00e9 pour ce bon de commande?",
    "INVOICE_CONFIRM_PRORATE": "Frais calcul\u00e9s au prorata?\n\nToute modification subs\u00e9quente \u00e0 la facture qui affecterait les montants calcul\u00e9s au prorata devrait \u00eatre r\u00e9alis\u00e9e manuellement.",
    "CANCELED": "Annul\u00e9",
    "LINEITEM_SUMMARY": "<div class='acq-lineitem-summary'><a href='${19}'>${0}</a>, by ${1} (${2})</div>\n<div class='acq-lineitem-summary-extra'>\n${3} Commander, ${4} Re\u00e7ues, ${7} Factur\u00e9, ${8} R\u00e9clam\u00e9, ${9} Annul\u00e9</div>\n<div class='acq-lineitem-summary-extra'>Estimation $${6}, Encombr\u00e9 $${16}, Pay\u00e9  $${17}</div>\n<div class='acq-lineitem-summary-extra'>\n# ${10} <a style='padding-right: 10px;' class='hidden${20}'  href='${11}/acq/po/view/${12}'>&#x2318; ${13} ${18}</a>\n<a style='padding-right: 10px;' class='hidden${21}' href='${11}/acq/picklist/view/${14}'>&#x2756; ${15}</a></div>",
    "DUPE_PO_NAME_LINK": "View PO",
    "CONFIRM_SPLIT_PO": "\u00cates-vous certain de vouloir diviser ce bon de commande en \naucun bon de commande pour chaque article constituant?",
    "RESET_FORMULAE": "R\u00e9initialiser les formules",
    "COULD_NOT_DELETE_MAPPING": "Une erreur s\u2019est produite lors du retrait de l\u2019\u00e9tiquette du fonds.",
    "FUND_XFER_CONFIRM": "\u00cates-vous certain d\u2019\u00eatre pr\u00eat \u00e0 proc\u00e9der \u00e0 ce transfert?",
    "ACQ_SEARCH_CLASS_ABBR_jub": "LI",
    "ACTIVATE_LI_PROCESSED": "Lineitems Processed: ${0}",
    "LI_CANCEL_CONFIRM": "\u00cates-vous certain de vouloir indiquer cet article comme NON re\u00e7u?",
    "FUND_LIST_ROLLOVER_SUMMARY_FUNDS": "<b>${1}</b> fonds accumul\u00e9s pour l\u2019exercice ${0} pour les emplacements s\u00e9lectionn\u00e9s",
    "SELECT_AN_LI_ATTRIBUTE": "Vous devez s\u00e9lectionner un attribut pour l\u2019article.",
    "CREATE_PO_ASSETS_CONFIRM": "Ainsi, des fiches bibliographiques, des codes topographiques et des dossiers seront cr\u00e9\u00e9s dans le syst\u00e8me int\u00e9gr\u00e9 de gestion de biblioth\u00e8que pour ce bon de commande.\n\nVoulez-vous continuer?",
    "FUND_XFER_SAME_SOURCE_AND_DEST": "Transfert impossible. La provenance et la destination des fonds sont les m\u00eames.",
    "ADD_LI_TO_PO_BAD_PO_STATE": "The selected PO has already been activated",
    "COPIES_TO_RECEIVE": "Number of copies to receive: ",
    "NO_RESULTS": "Aucun r\u00e9sultat",
    "CANCEL": "Annuler",
    "LI_EXISTING_COPIES": "There are ${0} existing copies for this bibliographic record at this location",
    "LI_FORMAT_ERROR": "Une erreur inattendue s\u2019est produite lors de la r\u00e9cup\u00e9ration des renseignements structur\u00e9s sur l\u2019article.",
    "ACQ_SEARCH_CLASS_ABBR_acqpo": "PO",
    "ACQ_SEARCH_CLASS_ABBR_acqpl": "SL"
}