{
    "and": "E",
    "sort": "Sort Axis",
    "bib_level": "Bibliographic Level",
    "less": "...Less",
    "item_form": "Formulari",
    "site": "Site",
    "filters": "Filtratge",
    "notcontains": "Conten pas",
    "statuses": "Estatuts",
    "before": "Published Before",
    "new_facet": "New Facet",
    "lit_form": "Literary Form",
    "faceted_searches": "Facets",
    "contains": "Conten",
    "audience": "Public cibla",
    "filter_default": "-- Select a Filter --",
    "metabib": "Metarecord Search",
    "basic": "Basic",
    "new_modifier": "New Modifier",
    "staff": "Staff Search",
    "classed_searches": "Classed Searches",
    "more": "Mai encara...",
    "available": "Disponible",
    "new_filter": "Filtre nov\u00e8l",
    "format": "Type and Form",
    "after": "Published After",
    "ascending": "Triar d'un biais ascendent",
    "descending": "Triar d'un biais descendent",
    "modifier_default": "-- Select a Modifier --",
    "during": "In Publication",
    "exact": "Exactly Matches",
    "between": "Published Between",
    "advanced": "Detalhs avan\u00e7ats",
    "modifiers": "Modificadors",
    "perform_search": "Anem !",
    "remove": "Suprimir",
    "item_type": "Tipe",
    "depth": "Search Depth",
    "vr_format": "Videorecording Format",
    "or": "O"
}