{
    "MARC_EDITOR_TITLE": "Aufnahme-ID #${0}",
    "SELECT_MORE": "Click here to review all session URLs and/or select other URLs to verify",
    "CLONE_SESSION_NAME": "Kopie von ${0}",
    "SESSION_NAME": "Sitzung '${0}'",
    "CREATING": "Sitzung wird erstellt",
    "MARC_EDITOR_LINK": "Click to open MARC Editor for this record",
    "EXTRACTING_URLS": "Extracting URLs ...",
    "INTERFACE_SETUP": "Interface wird eingestellt ...",
    "NOTHING_SELECTED": "Es wurden keine Zeilen ausgew\u00e4hlt, also wird auch keine Aktion ausgef\u00fchrt.",
    "REREVIEW": "\u00d6ffnen",
    "MARC_EDITOR_SAVE_RECORD": "Aufnahme speichern",
    "REDIRECTING": "Loading next interface ...",
    "XPATH": "XPath",
    "SAVING_TAGS": "Saving tag/subfield selectors ...",
    "VERIFICATION_ATTEMPT_ID": "Verifikationsversuchs-ID: ${0}",
    "VERIFICATION_DIALOG": "\u00dcberpr\u00fcfe URLs ...",
    "EDIT": "Bearbeiten",
    "VERIFY_ALL": "Click 'OK' to verify ALL the URLs that belong to this session and match all your search terms.  Click 'Cancel' if the selected, visible URLs are the only ones you want verified.",
    "REVIEW_ATTEMPT": "Review this verification attempt",
    "CLONE_SESSION": "Klonen",
    "CLONING": "Existierende Sitzung wird geklont ...",
    "PERFORMING_SEARCH": "Suche wird aufgef\u00fchrt ...",
    "NEED_UVUS": "You must add some tag and subfield combinations."
}