{
    "CHOOSE_FILTER_TO_LOAD": "W\u00e4hlen Sie die zu ladenden Filters\u00e4tze",
    "OPERATOR_NE": "ist nicht",
    "OPERATOR_BETWEEN": "ist zwischen",
    "OPERATOR_GTE": "ist gr\u00f6\u00dfer als oder gleich",
    "OPERATOR_LT": "ist weniger als",
    "OPERATOR_IS_NULL": "ist Null",
    "LOAD_FILTERS": "Filter laden",
    "ADD_ROW": "Zeile hinzuf\u00fcgen",
    "EMPTY_LIST": "Suchfilter kann nicht erstellt werden. Leere Listen nicht erlaubt.",
    "APPLY": "Anwenden",
    "OPERATOR_GT": "ist gr\u00f6\u00dfer als",
    "OPERATOR_EQ": "ist",
    "OPERATOR_IN": "ist in der Menge",
    "OPERATOR_NOT_IN": "ist nicht in der Menge",
    "OPERATOR_LTE": "ist kleiner als oder gleich",
    "EMPTY_CASE_COMPACT": "F\u00fcgen Sie Zeilen hinzu, um Ergebnisse zu filtern.",
    "EMPTY_CASE": "F\u00fcgen Sie Zeilen hinzu um Ergebnisse zu filtern, oder klicken Sie einfach auf Anwenden um ungefilterte Ergebnisse anzuzeigen.",
    "OPERATOR_LIKE": "ist wie",
    "CANCEL": "Abbrechen",
    "NAME_SAVED_FILTER_SET": "Geben Sie einen Namen f\u00fcr den gespeicherten Filtersatz ein:",
    "OPERATOR_IS_NOT_NULL": "ist nicht null",
    "OPERATOR_NOT_BETWEEN": "ist nicht zwischen",
    "OPERATOR_NOT_LIKE": "ist nicht wie",
    "SAVE_FILTERS": "Filter speichern",
    "NEED_NAME": "Sie m\u00fcssen einen Namen f\u00fcr die gespeicherten Filter eingeben.",
    "DEFAULT_DIALOG_TITLE": "Ergebnisse filtern"
}