{
    "and": "UND",
    "sort": "Sort Axis",
    "bib_level": "Bibliographic Level",
    "less": "...Weniger",
    "item_form": "Formular",
    "site": "Seite",
    "filters": "Filter",
    "notcontains": "Enth\u00e4lt nicht",
    "statuses": "Status",
    "before": "Ver\u00f6ffentlicht bevor dem",
    "new_facet": "New Facet",
    "lit_form": "Literaturform",
    "faceted_searches": "Aspekte",
    "contains": "Beinhaltet",
    "audience": "Empf\u00e4nger",
    "filter_default": "-- W\u00e4hlen Sie einen Filter --",
    "metabib": "Metarecord Search",
    "basic": "Allgemein",
    "new_modifier": "Neuer Modifikator",
    "staff": "Staff Search",
    "classed_searches": "Classed Searches",
    "more": "Mehr...",
    "available": "Verf\u00fcgbar",
    "new_filter": "Neuer Filter",
    "format": "Type and Form",
    "after": "Ver\u00f6ffentlicht nach dem",
    "ascending": "Absteigend sortieren",
    "descending": "Absteigend sortieren",
    "modifier_default": "-- Einen Modifikator ausw\u00e4hlen --",
    "during": "In Publication",
    "exact": "Genaue \u00dcbereinstimmungen",
    "between": "Ver\u00f6ffentlicht bevor dem",
    "advanced": "Erweitert",
    "modifiers": "Modifikatoren",
    "perform_search": "Start!",
    "remove": "Entfernen",
    "item_type": "Typ",
    "depth": "Search Depth",
    "vr_format": "Videorecording Format",
    "or": "ODER"
}