{
    "SUCCESS_SAVING_PHYSICAL": "Saved changes to the Physical Address of ${0}",
    "CONFIRM_EXIT_CCS": "There are unsaved changes to one or more copy statuses. Click OK to save these changes, or Cancel to abandon them.",
    "SURVEY_SAVE_CHANGES": "Enregistrar las modificacions",
    "ERROR_CREATING_CHILD_AOU": "Problem creating child organizational unit",
    "ERROR_CALLING_METHOD_PPL": "Problem calling method to create new permission",
    "TRANSLATION": "Traduccion",
    "ERROR_FETCHING_ORGS": "Problem fetching organizational unit data",
    "SUCCESS_CREATING_STATUS": "New ${0} status created",
    "SUCCESS_SAVING_HOLDS": "Saved changes to the Holds Address of ${0}",
    "SUCCESS_SAVING_ILL": "Saved changes to the ILL Address of ${0}",
    "CBHO_NO_LOAD": "Unable to load selected item.",
    "STATUS_EDITING": "Now editing ${0}",
    "SUCCESS_SAVING_DATA": "Saved changes to ${0}",
    "SUCCESS_DELETED_PERM_MAP": "Permission mapping deleted",
    "ERROR_SAVING_PERM_DATA": "Problem saving permission data for ${0}",
    "ERROR_FETCHING_HOLDS": "Problem fetching Holds Address for ${0}",
    "HOLDABLE": "Holdable",
    "CBHO_FIELD_DISPLAY": "${0}: ${1}",
    "STATUS_DELETED": "${0} deleted",
    "ERROR_CALLING_METHOD_CCS": "Problem calling method to create new copy status",
    "SUCCESS_CREATING_CODE": "New ${0} ${1} created",
    "ACQ_DISTRIB_FORMULA_NAME_PROMPT": "Enter new formula name",
    "ERROR_SAVING_DATA": "Problem saving data for ${0}",
    "LABEL_NEW_BRANCH": "New Branch",
    "ERROR_FETCHING_HOURS": "Problem fetching hours of operation for ${0}",
    "LABEL_TRANSLATION": "Traduccion",
    "ERROR_CREATING_PERMISSION": "Problem creating new Permission",
    "LABEL_DESCRIPTION": "Descripcion",
    "ERROR_SAVING_HOO": "Problem saving Hours of Operation data for ${0}",
    "SUCCESS_NEW_PERM_MAP": "New permission map created",
    "END_SURVEY": "End Survey Now",
    "CONFIRM_UNSAVED_CHANGES": "There are unsaved changes to one or more organization types. Click OK to save these changes, or Cancel to abandon them.",
    "OPAC_VISIBLE": "OPAC visible",
    "SURVEY_FOOT_LABEL": "Questions & Answers",
    "ERROR_DELETING": "Problem deleting ${0}",
    "ERROR_FETCHING_TYPES_AOUT": "Problem fetching organizational unit types",
    "CONFIRM_DELETE": "Are you sure you want to delete ${0}?",
    "ERROR_ORPHANS": "Cannot delete ${0}, ${1} subordinates still exist.",
    "LABEL_DEPTH": "Prigondor",
    "LABEL_NEW_TYPE": "Tipe nov\u00e8l",
    "LABEL_VALUE": "Valor",
    "SUCCESS_CREATING_CHILD_AOU": "New child Organizational Unit created for ${0}",
    "LABEL_CODE": "C\u00f2de",
    "CBHO_EDITING_EXISTING": "You are editing best-hold order #${0}: ${1}.",
    "CBHO_NEEDS_NAME": "You need to enter a name for the best-hold order.",
    "ERROR_FETCHING_PHYSICAL": "Problem fetching Physical Address for ${0}",
    "CONFIRM_EXIT_PPL": "There are unsaved modified permissions. Click OK to save these changes, or Cancel to abandon them.",
    "ERROR_FETCHING_PERMS": "Problem fetching perms",
    "LABEL_NEW_GROUP": "Grop nov\u00e8l",
    "SUCCESS_SAVING_HOO": "Hours of Operation updated for ${0}",
    "ERROR_SAVING_STATUS": "Problem saving ${0}",
    "ERROR_SAVING_PHYSICAL": "Problem saving Physical Address data for ${0}",
    "CONFIRM_EXIT_AOU": "There are unsaved changes to one or more organizational units. Click OK to save these changes, or Cancel to abandon them.",
    "ERROR_DELETING_PERM_MAPPING": "Problem deleting permission mapping ${0}",
    "ERROR_SAVING_DATA_CAM": "Problem saving data for ${0} ${1}",
    "SUCCESS_SAVING_MAILING": "Saved changes to the Mailing Address of ${0}",
    "ERROR_FETCHING_MAILING": "Problem fetching Mailing Address for ${0}",
    "ACQ_DISTRIB_FORMULA_NAME_CLONE": "${0} (Clone)",
    "ERROR_CREATING_CHILD_GROUP": "Problem creating child Group",
    "ERROR_DELETING_LAST_AOU": "Cannot delete ${0}, you need at least one organization unit.",
    "ERROR_SAVING_HOLDS": "Problem saving Holds Address data for ${0}",
    "NAME": "Nom",
    "SUCCESS_CREATING_CHILD_AOUT": "New child Organization Type created for ${0}",
    "LABEL_GRANTABLE": "Grantable",
    "ERROR_SAVING_ILL": "Problem saving ILL Address data for ${0}",
    "SURVEY_WARN_TEXT": "No questions can be modified or added at this time. The survey Start Date must be set for the future to add new questions or modify existing questions.",
    "ERROR_FETCHING_GROUPS": "Problem fetching groups",
    "SUCCESS_CREATING_PERMISSION": "New ${0} permission created",
    "SURVEY_ID": "Survey ID # ${0}",
    "COPY_ACTIVE": "Sets copy active",
    "ERROR_CREATING_PERM_MAP": "Problem creating new Permission Map",
    "SURVEY_DELETE_ANSWER": "Delete Answer",
    "SURVEY_QUESTION": "Question\u00a0:",
    "CONFIRM_EXIT_CAM": "There are unsaved changes to one or more ${0} codes. Click OK to save these changes, or Cancel to abandon them.",
    "ERROR_DELETING_LAST_AOUT": "Cannot delete ${0}. You need at least one organization type.",
    "ERROR_FETCHING_ILL": "Problem fetching ILL Address for ${0}",
    "ERROR_CREATING_CHILD_AOUT": "Problem creating child organization type",
    "ERROR_CALLING_METHOD_PGT": "Problem calling method to create child Group",
    "CONFIRM_EXIT_PGT": "There are unsaved modified permission maps. Click OK to save these changes, or Cancel to abandon them.",
    "SURVEY_ANSWER": "Responsa\u00a0:",
    "ERROR_FETCHING_PERM_MAPS": "Problem fetching perm maps",
    "SURVEY_SAVE_ADD": "Save Question & Add Answer",
    "SUCCESS_SAVE": "Saved changes to ${0}",
    "ERROR_CALLING_METHOD_PERM_MAP": "Problem calling method to create new permission map",
    "EVENT_DEF_LABEL": "${0}: ${1}",
    "SURVEY_DELETE_QUESTION": "Delete Question & Answers",
    "SUCCESS_SAVE_PERM": "Saved permission changes to ${0}",
    "SURVEY_ADD_ANSWER": "Add Answer",
    "ERROR_FETCHING_STATUSES": "Problem fetching statuses",
    "ID": "Identificant (ID)",
    "ERROR_CALLING_METHOD_CAM": "Problem calling method to create new ${0}",
    "CBHO_EDITING_NEW": "You are editing a new best-hold order.",
    "ERROR_SAVING_MAILING": "Problem saving Mailing Address data for ${0}",
    "IS_AVAILABLE": "Is Available",
    "ERROR_CALLING_METHOD_AOUT": "Problem calling method to create child organization type",
    "ERROR_CREATING_STATUS": "Problem creating new Status",
    "SUCCESS_NEW_CHILD_GROUP": "New child Group created for ${0}"
}