{
    "SOURCE_SETUP_ALL_AVAIL_SOURCES": "All Available Sources",
    "TEMPLATE_CONF_SELECT_CANCEL": "Select the value, or cancel:",
    "OPERATORS_ILIKE": "Contains Matching substring (ignore case)",
    "FILTERS_LABEL_NULL_BLANK": "Is NULL or Blank",
    "OPERATORS_LIKE": "Contains Matching substring",
    "WIDGET_MONTHS": "Monat(e)",
    "LINK_NULLABLE_RIGHT": "Oberbegriff",
    "TFORMS_LABEL_AVERAGE": "Durchschnitt",
    "TEMPLATE_CONF_CONFIRM_STATE": "Click OK for TRUE and Cancel for FALSE.",
    "OPERATORS_EQUALS": "Equals",
    "FILTERS_LABEL_BETWEEN": "zwischen",
    "OPERATORS_IN_LIST": "in Liste",
    "TEMPLATE_CONF_NOT_IN": "Field does not match one of list (comma separated):",
    "OPERATORS_NOT_IN_LIST": "Not in list",
    "FILTERS_LABEL_NOT_IN": "Not in list",
    "FOLDERS_OUTPUT": "Ausgabe",
    "FILTERS_LABEL_GT_TIME": "Nach dem (Datum/Zeit)",
    "OPERATORS_IS_NULL": "Ist NULL",
    "TEMPLATE_CONF_CONFIRM_SAVE": "Name: $ {0}\nBeschreibung: $ {1}\nVorlage speichern?",
    "OPERATORS_IS_NOT_NULL": "Ist nicht NULL",
    "TEMPLATE_CONF_CONFIRM_RESET": "You have already added the [${0}] field\nfrom the [${1}] source. Click OK if you\nwould like to reset this field.",
    "OPERATORS_GT_EQUAL": "Gr\u00f6\u00dfer als oder gleich",
    "TRANSFORMS_MONTH_TRUNC": "Jahr + Monat",
    "FILTERS_LABEL_NULL": "Ist NULL",
    "REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Please provide a report folder",
    "OPERATORS_GT_TIME": "Nach dem (Datum/Zeit)",
    "TRANSFORMS_YEAR_TRUNC": "Jahr",
    "TRANSFORMS_UPPER": "Upper case",
    "FOLDERS_REPORTS": "Berichte",
    "LINK_NULLABLE_LEFT": "Child",
    "TRANSFORMS_COUNT_DISTINCT": "Count Distinct",
    "FOLDER_WINDOW_COLNAME_SELECT": "Ausw\u00e4hlen",
    "TRANSFORMS_FIRST": "Erster Wert",
    "TFORMS_LABEL_LOWER": "Lower case",
    "TFORMS_LABEL_COUNT": "Anzahl",
    "TRANSFORMS_HOD": "Hour of day",
    "WIDGET_RELATIVE_DATE": "Relative Date",
    "FILTERS_LABEL_LESS_THAN": "kleiner als",
    "TEMPLATE_CONF_SUCCESS_SAVE": "Vorlage ${0} wurde erfolgreich gespeichert.",
    "TFORMS_LABEL_MOY": "Month of Year",
    "FILTERS_LABEL_EQ_ANY": "Equals Any",
    "TRANSFORMS_MAX": "Max",
    "TRANSFORMS_MIN": "Min",
    "TRANSFORMS_SUM": "Summe",
    "TRANSFORMS_FIRST_WORD": "First contiguous non-space string",
    "TRANSFORMS_MONTHS_AGO": "Months ago",
    "SOURCE_BROWSE_AGGREGATE": "Zusammenf\u00fchren",
    "TFORMS_LABEL_DATE": "Datum",
    "WIDGET_YEARS": "Jahr(e)",
    "FILTERS_LABEL_LT_TIME": "Vor dem (Datum/Zeit)",
    "TRANSFORMS_COUNT": "Anzahl",
    "WIDGET_REAL_DATE": "echte Date",
    "OPERATORS_LT_TIME": "Vor dem (Datum/Zeit)",
    "TFORMS_LABEL_MAX": "Max",
    "REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Please change the report name",
    "TEMPLATE_CONF_FALSE": "Falsch",
    "TEMPLATE_CONF_BARE": "Bare",
    "TRANSFORMS_LAST": "Letzter Wert",
    "TFORMS_LABEL_MIN": "Min",
    "REPORT_EDITOR_REPORT_FOLDERS": "Report Folders",
    "TEMPLATE_CONF_EQUALS": "Equals",
    "REPORT_EDITOR_OUTPUT_FOLDERS": "Ausgabeordner",
    "FILTERS_LABEL_NOT_BETWEEN": "Nicht zwischen",
    "TRANSFORMS_QOY": "Quartal",
    "REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Please provide an output folder",
    "FILTERS_LABEL_GREATER_THAN": "Gr\u00f6\u00dfer als",
    "FILTERS_LABEL_NE_ANY": "Does Not Equal Any",
    "SOURCE_BROWSE_NON_AGGREGATE": "Non-Aggregate",
    "OPERATORS_NE_ANY": "Does Not Equal Any",
    "TRANSFORMS_AVERAGE": "Durchschnitt",
    "FOLDERS_TEMPLATES": "Vorlagen",
    "TFORMS_LABEL_DAY_NAME": "\u0414\u0435\u043d\u044c \u043d\u0435\u0434\u0435\u043b\u0438",
    "WIDGET_DAYS": "Tag(e)",
    "TRANSFORMS_ROUND": "Round",
    "FOLDERS_TEMPLATE": "Vorlage",
    "TRANSFORMS_HOUR_TRUNC": "Stunde",
    "TFORMS_LABEL_HOUR_TRUNC": "Stunde",
    "TRANSFORMS_MOY": "Month of Year",
    "LINK_NULLABLE_NONE": "Kein",
    "RPT_BUILDER_CONFIRM_SAVE": "Name: $ {0}\nBeschreibung: $ {1}\nVorlage speichern?",
    "TFORMS_LABEL_DOY": "Tag des Jahres",
    "TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Change the field hint to:",
    "TRANSFORMS_DATE": "Datum",
    "FOLDERS_REPORT": "Bericht",
    "TFORMS_LABEL_DOW": "Wochentag",
    "FILTERS_LABEL_LT_EQUAL": "kleiner oder gleich",
    "TFORMS_LABEL_INT": "Drop trailing decimals",
    "OPERATORS_GTE_TIME": "Am oder nach dem (Datum/Zeit)",
    "TFORMS_LABEL_DOM": "Tag des Monats",
    "FOLDER_WINDOW_COLNAME_NONE": "Kein",
    "REPORT_EDITOR_ENTER_NAME_ALERT": "Geben Sie einen Berichtnamen ein",
    "OPERATORS_LT_EQUAL": "kleiner oder gleich",
    "TFORMS_LABEL_MONTHS_AGO": "Months ago",
    "TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string",
    "FOLDER_WINDOW_REPORT_OUTPUT": "Report Output: ${0}",
    "FILTERS_LABEL_GTE_TIME": "Am oder nach dem (Datum/Zeit)",
    "TFORMS_LABEL_FIRST": "Erster Wert",
    "TRANSFORMS_AGE": "Alter",
    "FILTERS_LABEL_LIKE": "Contains Matching substring",
    "TEMPLATE_CONF_TRUE": "Wahr",
    "SOURCE_SETUP_CONFIRM_EXIT": "Sie haben angefangen eine Vorlage zu erstellen!",
    "TRANSFORMS_QUARTERS_AGO": "Quarters ago",
    "TFORMS_LABEL_MONTH_TRUNC": "Jahr + Monat",
    "TEMPLATE_CONF_IN": "Field matches one of list (comma separated):",
    "FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)",
    "FILTERS_LABEL_NOT_NULL": "Ist nicht NULL",
    "TEMPLATE_CONF_NO_MATCH": "Field does not match one of list (comma separated):",
    "TFORMS_LABEL_UPPER": "Upper case",
    "TRANSFORMS_SUBSTRING": "Substring",
    "FILTERS_LABEL_GT_EQUAL": "Gr\u00f6\u00dfer als oder gleich",
    "TEMPLATE_CONF_RAW_DATA": "Raw Data",
    "TFORMS_LABEL_HOD": "Hour of day",
    "FILTERS_LABEL_NOT_NULL_BLANK": "Is not NULL or Blank",
    "TFORMS_LABEL_SUM": "Summe",
    "LINK_NULLABLE_DEFAULT": "Voreinstellung",
    "FILTERS_LABEL_IN": "in Liste",
    "TFORMS_LABEL_AGE": "Alter",
    "FOLDER_WINDOW_CHANGE_FOLDERS": "Ordner \u00e4ndern",
    "TRANSFORMS_LOWER": "Lower case",
    "TRANSFORMS_MONTH_NAME": "Monatsname",
    "TRANSFORMS_DOW": "Wochentag",
    "TEMPLATE_CONF_PROMPT_CHANGE": "Spaltenkopf \u00e4ndern auf: ${0}",
    "OPERATORS_NOT_BETWEEN": "Nicht zwischen",
    "TRANSFORMS_DOY": "Tag des Jahres",
    "REPORT_EDITOR_INVALID_DATE_ALERT": "Ung\u00fcltiges Startdatum - YYYY-MM-DD",
    "TRANSFORMS_BARE": "Raw Data",
    "TRANSFORMS_DOM": "Tag des Monats",
    "TFORMS_LABEL_MONTH_NAME": "Monatsname'",
    "OPERATORS_EQ_ANY": "Equals Any",
    "TFORMS_LABEL_ROUND": "Round",
    "OPERATORS_GREATER_THAN": "Gr\u00f6\u00dfer als",
    "SOURCE_SETUP_CORE_SOURCES": "Core Sources",
    "TFORMS_LABEL_LAST": "Letzter Wert",
    "FILTERS_LABEL_EQUALS": "Equals",
    "FOLDER_WINDOW_COLNAME_ALL": "Alle",
    "TFORMS_LABEL_RAW_DATA": "Raw Data",
    "TFORMS_LABEL_COUNT_DISTINCT": "Count Distinct",
    "TFORMS_LABEL_FIRST5": "Erste 5 Ziffern (f\u00fcr US Postleitzahl)",
    "TEMPLATE_CONF_NOT_BETWEEN": "Feldwert ist zwischen (durch Komma getrennt):",
    "TRANSFORMS_INT": "Drop trailing decimals",
    "FILTERS_LABEL_LSE_TIME": "Am oder vor dem (Datum/Zeit)",
    "TRANSFORMS_DAY_NAME": "\u0414\u0435\u043d\u044c \u043d\u0435\u0434\u0435\u043b\u0438",
    "FOLDER_WINDOW_SELECT_ITEM": "Bitte einen Eintrag aus der Liste ausw\u00e4hlen",
    "TRANSFORMS_FIRST5": "Erste 5 Ziffern (f\u00fcr US Postleitzahl)",
    "OPERATORS_LTE_TIME": "Am oder vor dem (Datum/Zeit)",
    "TEMPLATE_CONF_DEFAULT": "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435  ${0}:",
    "TFORMS_LABEL_YEAR_TRUNC": "Jahr",
    "TRANSFORMS_WOY": "Woche eines Jahres",
    "TFORMS_LABEL_WOY": "Woche eines Jahres",
    "TFORMS_LABEL_QUARTERS_AGO": "Quarters ago",
    "TEMPLATE_CONF_BOOLEAN_VALUE": "Boolescher Wert",
    "OPERATORS_NOT_NULL_BLANK": "Is not NULL or Blank",
    "OPERATORS_NULL_BLANK": "Is NULL or Blank",
    "TEMPLATE_CONF_BETWEEN": "Feldwert ist zwischen (durch Komma getrennt):",
    "TFORMS_LABEL_QOY": "Quartal",
    "WIDGET_QUARTERS": "Quartal(e)",
    "OPERATORS_LESS_THAN": "kleiner als",
    "OPERATORS_BETWEEN": "zwischen"
}