{
    "SUCCESS_SAVING_PHYSICAL": "Saved changes to the Physical Address of ${0}",
    "CONFIRM_EXIT_CCS": "There are unsaved changes to one or more copy statuses. Click OK to save these changes, or Cancel to abandon them.",
    "SURVEY_SAVE_CHANGES": "\u00c4nderungen speichern",
    "ERROR_CREATING_CHILD_AOU": "Problem creating child organizational unit",
    "ERROR_CALLING_METHOD_PPL": "Problem calling method to create new permission",
    "TRANSLATION": "\u00dcbersetzung",
    "ERROR_FETCHING_ORGS": "Problem fetching organizational unit data",
    "SUCCESS_CREATING_STATUS": "Neuer ${0} Status erstellt",
    "SUCCESS_SAVING_HOLDS": "Saved changes to the Holds Address of ${0}",
    "SUCCESS_SAVING_ILL": "Saved changes to the ILL Address of ${0}",
    "CBHO_NO_LOAD": "Unable to load selected item.",
    "STATUS_EDITING": "Bearbeite gerade ${0}",
    "SUCCESS_SAVING_DATA": "\u00c4nderungen an ${0} gespeichert",
    "SUCCESS_DELETED_PERM_MAP": "Permission mapping deleted",
    "ERROR_SAVING_PERM_DATA": "Problem beim speichern der Zugangsdaten f\u00fcr ${0}",
    "ERROR_FETCHING_HOLDS": "Problem Mailingadresse f\u00fcr {0} abzurufen",
    "HOLDABLE": "Holdable",
    "CBHO_FIELD_DISPLAY": "Copy text   \t ${0}: ${1}",
    "STATUS_DELETED": "${0} gel\u00f6scht",
    "ERROR_CALLING_METHOD_CCS": "Problem calling method to create new copy status",
    "SUCCESS_CREATING_CODE": "Neues ${0} ${1} erstellt",
    "ACQ_DISTRIB_FORMULA_NAME_PROMPT": "Enter new formula name",
    "ERROR_SAVING_DATA": "Problem beim Speichern der Daten f\u00fcr ${0}",
    "LABEL_NEW_BRANCH": "New Branch",
    "ERROR_FETCHING_HOURS": "Problem fetching hours of operation for ${0}",
    "LABEL_TRANSLATION": "\u00dcbersetzung",
    "ERROR_CREATING_PERMISSION": "Problem creating new Permission",
    "LABEL_DESCRIPTION": "Beschreibung",
    "ERROR_SAVING_HOO": "Problem saving Hours of Operation data for ${0}",
    "SUCCESS_NEW_PERM_MAP": "Neue Erlaubniskarte kreiert",
    "END_SURVEY": "Aufnahme jetzt beenden",
    "CONFIRM_UNSAVED_CHANGES": "There are unsaved changes to one or more organization types. Click OK to save these changes, or Cancel to abandon them.",
    "OPAC_VISIBLE": "OPAC sichtbar",
    "SURVEY_FOOT_LABEL": "Fragen und Antworten",
    "ERROR_DELETING": "Problem beim L\u00f6schen von ${0}",
    "ERROR_FETCHING_TYPES_AOUT": "Problem fetching organizational unit types",
    "CONFIRM_DELETE": "Sind Sie sicher, dass sie ${0} l\u00f6schen m\u00f6chten?",
    "ERROR_ORPHANS": "Cannot delete ${0}, ${1} subordinates still exist.",
    "LABEL_DEPTH": "Depth",
    "LABEL_NEW_TYPE": "Neuer Typ",
    "LABEL_VALUE": "Wert",
    "SUCCESS_CREATING_CHILD_AOU": "New child Organizational Unit created for ${0}",
    "LABEL_CODE": "Code",
    "CBHO_EDITING_EXISTING": "You are editing best-hold order #${0}: ${1}.",
    "CBHO_NEEDS_NAME": "You need to enter a name for the best-hold order.",
    "ERROR_FETCHING_PHYSICAL": "Problem beim Abrufende der physikalische Adresse f\u00fcr ${0}",
    "CONFIRM_EXIT_PPL": "There are unsaved modified permissions. Click OK to save these changes, or Cancel to abandon them.",
    "ERROR_FETCHING_PERMS": "Problem Gruppen abzurufen",
    "LABEL_NEW_GROUP": "Neue Gruppe",
    "SUCCESS_SAVING_HOO": "Arbeitsstunden f\u00fcr ${0} aktualisiert",
    "ERROR_SAVING_STATUS": "Problem beim Speichern von ${0}",
    "ERROR_SAVING_PHYSICAL": "Problem beim Abrufende der physikalische Adresse f\u00fcr ${0}",
    "CONFIRM_EXIT_AOU": "There are unsaved changes to one or more organizational units. Click OK to save these changes, or Cancel to abandon them.",
    "ERROR_DELETING_PERM_MAPPING": "Problem deleting permission mapping ${0}",
    "ERROR_SAVING_DATA_CAM": "Problem beim Speichern der Daten f\u00fcr ${0} ${1}",
    "SUCCESS_SAVING_MAILING": "Saved changes to the Mailing Address of ${0}",
    "ERROR_FETCHING_MAILING": "Problem Mailingadresse f\u00fcr {0} abzurufen",
    "ACQ_DISTRIB_FORMULA_NAME_CLONE": "${0} (Klon}",
    "ERROR_CREATING_CHILD_GROUP": "Problem Erstellen einer Kindergruppe",
    "ERROR_DELETING_LAST_AOU": "Kann ${0} nicht l\u00f6schen, Sie brauchen mindestens eine Aubaueinheit.",
    "ERROR_SAVING_HOLDS": "Problem saving Holds Address data for ${0}",
    "NAME": "Name",
    "SUCCESS_CREATING_CHILD_AOUT": "New child Organization Type created for ${0}",
    "LABEL_GRANTABLE": "Grantable",
    "ERROR_SAVING_ILL": "Problem saving ILL Address data for ${0}",
    "SURVEY_WARN_TEXT": "No questions can be modified or added at this time. The survey Start Date must be set for the future to add new questions or modify existing questions.",
    "ERROR_FETCHING_GROUPS": "Problem Gruppen abzurufen",
    "SUCCESS_CREATING_PERMISSION": "New ${0} permission created",
    "SURVEY_ID": "ID aufnehmen # ${0}",
    "COPY_ACTIVE": "Sets copy active",
    "ERROR_CREATING_PERM_MAP": "Problem creating new Permission Map",
    "SURVEY_DELETE_ANSWER": "Antwort l\u00f6schen",
    "SURVEY_QUESTION": "Frage:",
    "CONFIRM_EXIT_CAM": "There are unsaved changes to one or more ${0} codes. Click OK to save these changes, or Cancel to abandon them.",
    "ERROR_DELETING_LAST_AOUT": "Kann ${0} nicht l\u00f6schen, Sie brauchen mindestens eine Aubaueinheit.",
    "ERROR_FETCHING_ILL": "Problem Mailingadresse f\u00fcr {0} abzurufen",
    "ERROR_CREATING_CHILD_AOUT": "Problem creating child organization type",
    "ERROR_CALLING_METHOD_PGT": "Problem calling method to create child Group",
    "CONFIRM_EXIT_PGT": "There are unsaved modified permission maps. Click OK to save these changes, or Cancel to abandon them.",
    "SURVEY_ANSWER": "Antwort:",
    "ERROR_FETCHING_PERM_MAPS": "Problem Gruppen abzurufen",
    "SURVEY_SAVE_ADD": "Frage speichern und Antwort hinzuf\u00fcgen",
    "SUCCESS_SAVE": "\u00c4nderungen an ${0} gespeichert",
    "ERROR_CALLING_METHOD_PERM_MAP": "Problem calling method to create new permission map",
    "EVENT_DEF_LABEL": "Copy text   \t ${0}: ${1}",
    "SURVEY_DELETE_QUESTION": "Fragen und Antworten l\u00f6schen",
    "SUCCESS_SAVE_PERM": "Erlaubnis\u00e4nderungen zu ${0} gespeichert",
    "SURVEY_ADD_ANSWER": "Antwort hinzuf\u00fcgen",
    "ERROR_FETCHING_STATUSES": "Problem Statuses abzurufen",
    "ID": "ID",
    "ERROR_CALLING_METHOD_CAM": "Problem calling method to create new ${0}",
    "CBHO_EDITING_NEW": "You are editing a new best-hold order.",
    "ERROR_SAVING_MAILING": "Problem Mailingadresse f\u00fcr {0} abzurufen",
    "IS_AVAILABLE": "Is Available",
    "ERROR_CALLING_METHOD_AOUT": "Problem calling method to create child organization type",
    "ERROR_CREATING_STATUS": "Problem creating new Status",
    "SUCCESS_NEW_CHILD_GROUP": "New child Group created for ${0}"
}