{
    "SOURCE_SETUP_ALL_AVAIL_SOURCES": "Totas las fonts disponiblas",
    "TEMPLATE_CONF_SELECT_CANCEL": "Select the value, or cancel:",
    "OPERATORS_ILIKE": "Contains Matching substring (ignore case)",
    "FILTERS_LABEL_NULL_BLANK": "Es NULL o void",
    "OPERATORS_LIKE": "Contains Matching substring",
    "WIDGET_MONTHS": "Mes(es)",
    "LINK_NULLABLE_RIGHT": "Parent",
    "TFORMS_LABEL_AVERAGE": "Mejan",
    "TEMPLATE_CONF_CONFIRM_STATE": "Click OK for TRUE and Cancel for FALSE.",
    "OPERATORS_EQUALS": "Egal",
    "FILTERS_LABEL_BETWEEN": "Entre",
    "OPERATORS_IN_LIST": "Dins la lista",
    "TEMPLATE_CONF_NOT_IN": "Field does not match one of list (comma separated):",
    "OPERATORS_NOT_IN_LIST": "Pas dins la lista",
    "FILTERS_LABEL_NOT_IN": "Pas dins la lista",
    "FOLDERS_OUTPUT": "Fichi\u00e8r de destinacion",
    "FILTERS_LABEL_GT_TIME": "Apr\u00e8p (Data/Ora)",
    "OPERATORS_IS_NULL": "Es NULL",
    "TEMPLATE_CONF_CONFIRM_SAVE": "Nom : ${0}\nDescripcion: ${1}\nEnregistrar lo mod\u00e8l ?",
    "OPERATORS_IS_NOT_NULL": "Es pas NULL",
    "TEMPLATE_CONF_CONFIRM_RESET": "You have already added the [${0}] field\nfrom the [${1}] source. Click OK if you\nwould like to reset this field.",
    "OPERATORS_GT_EQUAL": "Superior o egal a",
    "TRANSFORMS_MONTH_TRUNC": "Annada + Mes",
    "FILTERS_LABEL_NULL": "Es NULL",
    "REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Please provide a report folder",
    "OPERATORS_GT_TIME": "Apr\u00e8p (Data/Ora)",
    "TRANSFORMS_YEAR_TRUNC": "Annada",
    "TRANSFORMS_UPPER": "Majusculas",
    "FOLDERS_REPORTS": "Rap\u00f2rts",
    "LINK_NULLABLE_LEFT": "Enfant",
    "TRANSFORMS_COUNT_DISTINCT": "Calcul distincte",
    "FOLDER_WINDOW_COLNAME_SELECT": "Seleccionar",
    "TRANSFORMS_FIRST": "Primi\u00e8ra valor",
    "TFORMS_LABEL_LOWER": "Minusculas",
    "TFORMS_LABEL_COUNT": "Compte",
    "TRANSFORMS_HOD": "Ora",
    "WIDGET_RELATIVE_DATE": "Data relativa",
    "FILTERS_LABEL_LESS_THAN": "Inferior a",
    "TEMPLATE_CONF_SUCCESS_SAVE": "Template ${0} was successfully saved.",
    "TFORMS_LABEL_MOY": "Mes de l'annada",
    "FILTERS_LABEL_EQ_ANY": "Egala",
    "TRANSFORMS_MAX": "Max.",
    "TRANSFORMS_MIN": "Min.",
    "TRANSFORMS_SUM": "Soma",
    "TRANSFORMS_FIRST_WORD": "First contiguous non-space string",
    "TRANSFORMS_MONTHS_AGO": "Months ago",
    "SOURCE_BROWSE_AGGREGATE": "Aggregate",
    "TFORMS_LABEL_DATE": "Data",
    "WIDGET_YEARS": "Annada(s)",
    "FILTERS_LABEL_LT_TIME": "Abans (Data/Ora)",
    "TRANSFORMS_COUNT": "Compte",
    "WIDGET_REAL_DATE": "Data vertadi\u00e8ra",
    "OPERATORS_LT_TIME": "Abans (Data/Ora)",
    "TFORMS_LABEL_MAX": "Max.",
    "REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Please change the report name",
    "TEMPLATE_CONF_FALSE": "Fals",
    "TEMPLATE_CONF_BARE": "Void",
    "TRANSFORMS_LAST": "Darri\u00e8ra valor",
    "TFORMS_LABEL_MIN": "Min.",
    "REPORT_EDITOR_REPORT_FOLDERS": "Report Folders",
    "TEMPLATE_CONF_EQUALS": "Egal",
    "REPORT_EDITOR_OUTPUT_FOLDERS": "Output Folders",
    "FILTERS_LABEL_NOT_BETWEEN": "Pas entre",
    "TRANSFORMS_QOY": "Trim\u00e8stre",
    "REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Please provide an output folder",
    "FILTERS_LABEL_GREATER_THAN": "Superior a",
    "FILTERS_LABEL_NE_ANY": "Correspond a cap",
    "SOURCE_BROWSE_NON_AGGREGATE": "Non-Aggregate",
    "OPERATORS_NE_ANY": "Correspond a cap",
    "TRANSFORMS_AVERAGE": "Mejan",
    "FOLDERS_TEMPLATES": "Mod\u00e8ls",
    "TFORMS_LABEL_DAY_NAME": "Nom del jorn",
    "WIDGET_DAYS": "Jorn(s)",
    "TRANSFORMS_ROUND": "Arredondir",
    "FOLDERS_TEMPLATE": "Mod\u00e8l",
    "TRANSFORMS_HOUR_TRUNC": "Ora",
    "TFORMS_LABEL_HOUR_TRUNC": "Ora",
    "TRANSFORMS_MOY": "Mes de l'annada",
    "LINK_NULLABLE_NONE": "Pas cap",
    "RPT_BUILDER_CONFIRM_SAVE": "Nom : ${0}\nDescripcion: ${1}\nEnregistrar lo mod\u00e8l ?",
    "TFORMS_LABEL_DOY": "Jorn de l'annada",
    "TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Change the field hint to:",
    "TRANSFORMS_DATE": "Data",
    "FOLDERS_REPORT": "Rap\u00f2rt",
    "TFORMS_LABEL_DOW": "Jorn de la setmana",
    "FILTERS_LABEL_LT_EQUAL": "Inferior o egal a",
    "TFORMS_LABEL_INT": "Drop trailing decimals",
    "OPERATORS_GTE_TIME": "Fins al (Data / ora)",
    "TFORMS_LABEL_DOM": "Jorn del mes",
    "FOLDER_WINDOW_COLNAME_NONE": "Pas cap",
    "REPORT_EDITOR_ENTER_NAME_ALERT": "Please enter a report name",
    "OPERATORS_LT_EQUAL": "Inferior o egal a",
    "TFORMS_LABEL_MONTHS_AGO": "Months ago",
    "TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string",
    "FOLDER_WINDOW_REPORT_OUTPUT": "Sortida del rap\u00f2rt : ${0}",
    "FILTERS_LABEL_GTE_TIME": "Fins al (Data / ora)",
    "TFORMS_LABEL_FIRST": "Primi\u00e8ra valor",
    "TRANSFORMS_AGE": "Edat",
    "FILTERS_LABEL_LIKE": "Contains Matching substring",
    "TEMPLATE_CONF_TRUE": "Verai",
    "SOURCE_SETUP_CONFIRM_EXIT": "You have started building a template!\n Selecting a new starting source will destroy the current template and start over.  Is this OK?",
    "TRANSFORMS_QUARTERS_AGO": "Quarters ago",
    "TFORMS_LABEL_MONTH_TRUNC": "Annada + Mes",
    "TEMPLATE_CONF_IN": "Field matches one of list (comma separated):",
    "FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)",
    "FILTERS_LABEL_NOT_NULL": "Es pas NULL",
    "TEMPLATE_CONF_NO_MATCH": "Field does not match one of list (comma separated):",
    "TFORMS_LABEL_UPPER": "Majusculas",
    "TRANSFORMS_SUBSTRING": "Soscadena",
    "FILTERS_LABEL_GT_EQUAL": "Superior o egal a",
    "TEMPLATE_CONF_RAW_DATA": "Donadas originalas",
    "TFORMS_LABEL_HOD": "Ora",
    "FILTERS_LABEL_NOT_NULL_BLANK": "Es pas NULL o void",
    "TFORMS_LABEL_SUM": "Soma",
    "LINK_NULLABLE_DEFAULT": "Valor per defaut",
    "FILTERS_LABEL_IN": "Dins la lista",
    "TFORMS_LABEL_AGE": "Edat",
    "FOLDER_WINDOW_CHANGE_FOLDERS": "Change Folders",
    "TRANSFORMS_LOWER": "Minusculas",
    "TRANSFORMS_MONTH_NAME": "Nom del mes",
    "TRANSFORMS_DOW": "Jorn de la setmana",
    "TEMPLATE_CONF_PROMPT_CHANGE": "Change the column header to: ${0}",
    "OPERATORS_NOT_BETWEEN": "Pas entre",
    "TRANSFORMS_DOY": "Jorn de l'annada",
    "REPORT_EDITOR_INVALID_DATE_ALERT": "Data iniciala invalida - AAAA-MM-JJ",
    "TRANSFORMS_BARE": "Donadas originalas",
    "TRANSFORMS_DOM": "Jorn del mes",
    "TFORMS_LABEL_MONTH_NAME": "Nom del mes",
    "OPERATORS_EQ_ANY": "Egala",
    "TFORMS_LABEL_ROUND": "Arredondir",
    "OPERATORS_GREATER_THAN": "Superior a",
    "SOURCE_SETUP_CORE_SOURCES": "Fonts principalas",
    "TFORMS_LABEL_LAST": "Darri\u00e8ra valor",
    "FILTERS_LABEL_EQUALS": "Egal",
    "FOLDER_WINDOW_COLNAME_ALL": "Totes",
    "TFORMS_LABEL_RAW_DATA": "Donadas originalas",
    "TFORMS_LABEL_COUNT_DISTINCT": "Calcul distincte",
    "TFORMS_LABEL_FIRST5": "First 5 characters (for US ZIP code)",
    "TEMPLATE_CONF_NOT_BETWEEN": "Field value is not between (comma separated):",
    "TRANSFORMS_INT": "Drop trailing decimals",
    "FILTERS_LABEL_LSE_TIME": "Fins al (Data / ora)",
    "TRANSFORMS_DAY_NAME": "Nom del jorn",
    "FOLDER_WINDOW_SELECT_ITEM": "Please select an item from the list",
    "TRANSFORMS_FIRST5": "First 5 characters (for US ZIP code)",
    "OPERATORS_LTE_TIME": "Fins al (Data / ora)",
    "TEMPLATE_CONF_DEFAULT": "Valor ${0} :",
    "TFORMS_LABEL_YEAR_TRUNC": "Annada",
    "TRANSFORMS_WOY": "Setmana de l'annada",
    "TFORMS_LABEL_WOY": "Setmana de l'annada",
    "TFORMS_LABEL_QUARTERS_AGO": "Quarters ago",
    "TEMPLATE_CONF_BOOLEAN_VALUE": "Valor booleana",
    "OPERATORS_NOT_NULL_BLANK": "Es pas NULL o void",
    "OPERATORS_NULL_BLANK": "Es NULL o void",
    "TEMPLATE_CONF_BETWEEN": "Field value is between (comma separated):",
    "TFORMS_LABEL_QOY": "Trim\u00e8stre",
    "WIDGET_QUARTERS": "Trim\u00e8stre(s)",
    "OPERATORS_LESS_THAN": "Inferior a",
    "OPERATORS_BETWEEN": "Entre"
}