{
    "PWD_RESET_SUBMIT_ERROR": "Das System konnte Ihre Anfrage nach Passwortr\u00fccksetzung nicht verarbeiten. Bitte versuchen Sie es erneut oder wenden sich an das Aufsichtspersonal mit der Bitte um Unterst\u00fctzung.",
    "PWD_RESET_SUBMIT_SUCCESS": "Ihre Anfrage, den Passwortr\u00fccksetzungsprozess zu starten, wurde durchgef\u00fchrt. Wenn Ihr Zugang eine g\u00fcltige E-Mail-Adresse besitzt, sollten Sie eine E-Mail mit witerf\u00fchrenden Informationen zum R\u00fccksetzen Ihres Passworts erhalten.",
    "USERNAME_PROMPT": "Nutzername: ",
    "HOLD_STATUS_PLURAL": "Reservierung # ${0} von insgesamt ${1} Reservierungen und ${2} m\u00f6glichen Gegenst\u00e4nden",
    "HOLDINGS_TABLE_CAPTION": "Bestandszusammenfassung (${0})",
    "INDEX_HOLDINGS": "Indizes",
    "EDIT_MFHD_RECORD": "Eintrag bearbeiten",
    "MISSING_VOLUMES": "Fehlende Inhalte",
    "DELETED_MFHD_RECORD": "MFHD-Eintrag ${0} wurde gel\u00f6scht",
    "SUBMIT_BUTTON_LABEL": "Absenden",
    "CREATED_MFHD_RECORD": "MFHD-Eintrag f\u00fcr ${0} wurde erstellt",
    "CURRENT_INDEXES": "Aktuelle Indizes",
    "BARCODE_PROMPT": "Barcode: ",
    "PWD_RESET_RESPONSE_TITLE": "Antwort vom Passwortzur\u00fccksetzen",
    "SOURCE_CANNOT_HAVE_COPIES": "Eintr\u00e4ge von ${0} k\u00f6nnen keine Kopien haben.",
    "CURRENT_SUPPLEMENTS": "Aktuelle Anh\u00e4nge",
    "ONLINE_VOLUMES": "Online Inhalte",
    "DELETE_MFHD": "Eintrag l\u00f6schen",
    "CREATE_MFHD": "MFHD-Eintrag hinzuf\u00fcgen",
    "EDIT_PROPERTIES": "Eigenschaften \u00e4ndern",
    "CANCEL_BUTTON_LABEL": "Abbrechen",
    "CURRENT_HOLDINGS": "Aktueller Inhalt",
    "MORE_COPIES_FULL_RECORD": "\u2026 f\u00fcr weitere Ausgaben siehe vollst\u00e4ndiger Eintrag",
    "SUPPLEMENT_HOLDINGS_ADD": "Zus\u00e4tzliche erg\u00e4nzende Informationen",
    "INCOMPLETE_VOLUMES": "Unvollst\u00e4ndige Inhalte",
    "SAVE_MFHD_LABEL": "MFHD speichern",
    "OK": "OK",
    "INDEX_HOLDINGS_ADD": "Zus\u00e4tzliche Indexinformation",
    "PWD_RESET_FORGOT_PROMPT": "Passwort vergessen?",
    "PWD_RESET_FORM_TITLE": "R\u00fccksetzen des Passwortes anfordern",
    "PWD_RESET_SUBMIT_PROMPT": "Um den Prozess des Passwortzur\u00fccksetzens zu starten, geben Sie entweder Ihren Barcode oder Ihren Nutzernamen in das Feld unten ein und klicken Sie \"Absenden\"",
    "HOLD_STATUS_SINGULAR": "Reservierung # ${0} von insgesamt ${1} Reservierungen und ${2} m\u00f6glicher Gegenst\u00e4nd",
    "PWD_RESET_SUBMIT_STATUS": "Anfrage wird gesendet \u2026",
    "DELETE_MFHD_CONFIRM": "Sind Sie sicher, dass Sie diesen fortlaufenden Eintrag l\u00f6schen m\u00f6chten?",
    "PLACE_HOLD": "Reservierung durchf\u00fchren",
    "BASIC_HOLDINGS": "Inhalte",
    "EDIT_MFHD_MENU": "Best\u00e4nde bearbeiten",
    "BASIC_HOLDINGS_ADD": "Zus\u00e4tzliche Inhaltsinformationen",
    "SUPPLEMENT_HOLDINGS": "Anh\u00e4nge",
    "MORE": "Mehr"
}