{
    "NO_PAYLOAD": "Nosotros no recebimos m\u00e1s informaci\u00f3n de el servidor sobre este intento de toma.",
    "TITLE": "T\u00edtulo",
    "PRINT": "<u>I</u>mprimir",
    "AUTO_resource_barcode": "Ingrese el c\u00f3digo de barras:",
    "DURATION": "Reservado de",
    "NEEDS_ROUTED_TO": "Este art\u00edculo necesita ser enviado a",
    "PRINTED_BY": "Imprimido por",
    "CAPTURE_TRANSIT_SOURCE": "De:",
    "CAPTURE_INFO": "Informaci\u00f3n de toma",
    "AUTO_ATTR_VALUE_capture": "Tomar",
    "AUTHOR": "Autor",
    "CAPTURE_BRESV_BRSRC": "C\u00f3digo de barras del recurso:",
    "SLIP_DATE": "Fecha de noticia",
    "RESERVATION_SHELF": "ESTANTE DE RESERVA",
    "UNKNOWN_PROBLEM": "Un problema desconocido se produjo durante el intento de toma",
    "FAILURE": "Toma fracasada",
    "CAPTURE_CAUSES_TRANSIT": "Este art\u00edculo esta ahora en camino",
    "RESERVED": "Reservado para el cliente",
    "SUCCESS": "Toma \u00e9xitosa",
    "REQUEST": "Solicitar tiempo",
    "AT": "a",
    "CAPTURE_BRESV_PICKUP_LIB": "Biblioteca de recolecci\u00f3n:",
    "CAPTURED_NOTHING": "No capturo nada.",
    "TRANSIT": "*** Tr\u00e1nsito ***",
    "BARCODE": "C\u00f3digo de barras",
    "AUTO_pickup_lib_selector": "Biblioteca de recolecci\u00f3n:",
    "CAPTURE_TRANSIT_DEST": "Para:",
    "PRINT_ACCESSKEY": "P",
    "CAPTURE_BRESV_DATES": "Tiempo de reservaci\u00f3n:",
    "HERES_WHAT_WE_KNOW": "La siguiente informaci\u00f3n es disponible de la toma fracasada:",
    "AUTO_capture_heading": "Recursos Reservados de Toma"
}