{
    "AUTO_no_out_bresv": "Patr\u00f3n no tiene m\u00e1s reservas a cabo en este momento.",
    "PICKUP_ERROR": "Error comunicando con el servidor (intentando contestar):",
    "AUTO_no_in_bresv": "EL usuario no ha entregado ning\u00fan recurso el d\u00eda de hoy",
    "NO_SUCH_RETURNABLE_RESOURCE": "No existe el recurso puede ser devuelta.",
    "AUTO_ATTR_VALUE_return": "Enter",
    "RETURNABLE_RESOURCE_ERROR": "Error al buscar recursos retornables:",
    "RETURN_NO_RESPONSE": "No hay respuesta del servidor al intentar retorno.",
    "AUTO_ATTR_VALUE_pickup": "Contestar",
    "AUTO_barcode_type": "Regresar por c\u00f3digo de barras de",
    "AUTO_in_bresv": "El usuario ha devuelto estos recursos el d\u00eda de hoy:",
    "RESERVATIONS_ERROR": "Error comunicando con el servidor (pidiendo reservaciones):",
    "AUTO_patron": "Usuario",
    "COPY_ALERT": "${0}:\n${1}\n\n\u00bfQuiere proceder de todos modos?",
    "AUTO_resource": "Recurso",
    "RETURN_ERROR": "Error al comunicarse con el servidor (retorno de intentar):",
    "AUTO_patron_barcode": "Introducir c\u00f3digo de barras del usuario:",
    "AUTO_h1": "Reservas de recogida",
    "AUTO_ATTR_VALUE_go": "Ir",
    "AUTO_out_bresv": "Actualmente el usuario tiene estas reservaciones en su custodia:",
    "AUTO_ready_bresv": "El usuario tiene estas reservaciones listas para ser recogidas:",
    "RESERVATIONS_NO_RESPONSE": "No hay respuesta del servidor cuando se le pide para hacer reservas.",
    "AUTO_ATTR_VALUE_reset": "Limpiar / Nuevo usuario",
    "RETURN_SUCCESS": "Devoluci\u00f3n exitosa.",
    "PICKUP_NO_RESPONSE": "No hay respuesta del servidor al intentar recogida.",
    "NOTICE_CHANGE_OF_PATRON": "Tenga en cuenta que el recurso escaneada estaba en reserva a un diferente\npatr\u00f3n de \u00faltimo recurso ha sido escaneada. Si esto no es\nera de esperar, dejar de examinar las reservas pendientes para su patr\u00f3n\no en el recurso.",
    "NO_PATRON_BARCODE": "Introduzca el c\u00f3digo de barras del usuario",
    "ADDRESS": "${0}\n${1}\n${2}, ${3} ${4}",
    "SELECT_SOMETHING": "No ha seleccionado ninguna reservaci\u00f3n",
    "AUTO_no_ready_bresv": "En este momento el usuario no tiene reservaciones listas para recolecci\u00f3n.",
    "AUTO_return_h1": "Devoluci\u00f3n de reservaciones"
}