{
    "AUTO_ATTR_VALUE_button_cancel_existing": "Cancelar seleccionados",
    "AUTO_ATTR_VALUE_reserve_brsrc": "Reserva seleccionada",
    "AUTO_ATTR_VALUE_next": "Siguiente",
    "HERE_ARE_EXISTING_BRESV": "Reservas existentes para",
    "AUTO_email_notify": "Enviar notificaci\u00f3n por correo electr\u00f3nico cuando recurso est\u00e1 disponible para su recogida.",
    "ON_FLY_ERROR": "Error al intentar hacer punto pueden reservar un recurso:",
    "AUTO_ATTR_VALUE_button_edit_existing": "Editar seleccionados",
    "AUTO_ending_at": "y",
    "AUTO_arbitrary_resource": "Introducir el c\u00f3digo de barras de un recurso catalogado, se pueden reservar:",
    "NO_BRT_RESULTS": "No hay tipos de recursos se pueden reservar registrados.",
    "AUTO_ATTR_VALUE_reserve_brt": "Reservar Cualquiera",
    "AUTO_brt_noncat_only": "Mostrar s\u00f3lo los tipos de recursos se pueden reservar no catalogadas",
    "OUTSTANDING_BRESV": "Reservas pendientes para el patr\u00f3n",
    "INVALID_TS_RANGE": "Debe elegir un tiempo de inicio y final v\u00e1lido para la reserva.",
    "AUTO_or": "- o -",
    "CREATE_BRESV_OK_MISSING_TARGET_WILL_CANCEL": "Dado que el recurso solicitado no podr\u00eda ser objetivo, esta\nreserva ahora se cancelar\u00e1.",
    "ERROR_FETCHING_AOUS": "No se pudo recuperar ajustes de la unidad de organizaci\u00f3n.\nEste es un error no-fatal, pero puede que desee\nponerse en contacto con el administrador del sistema.",
    "NEED_EXACTLY_ONE_BRT_PASSED_IN": "No se puede reservar varios tipos de recursos a la vez.",
    "CXL_BRESV_SUCCESS": "Canceladas ${0} reserva(s)",
    "UNTARGETED": "Ninguno objetivo",
    "CREATE_BRESV_SERVER_ERROR": "Error del servidor al crear una reserva ",
    "ON_FLY_NO_RESPONSE": "No hay respuesta del servidor que quiere hacer art\u00edculo reservable en un recurso.",
    "AUTO_patron_barcode": "Reservar a Patr\u00f3n de c\u00f3digo de barras:",
    "NO_EXISTING_BRESV": "Este usuario no tiene reservas existentes.",
    "GET_BRESV_LIST_ERR": "Error al obtener la lista de reservas: ",
    "AUTO_explain_bookable": "Para reservar un art\u00edculo que todav\u00eda no se ha registrado como un recurso pueden reservar, encontrarlo en el cat\u00e1logo o en <em> Art\u00edculos de la plantilla</ em>, y seleccione <em>Haga reservable art\u00edculo </em> o <em> Art\u00edculo de Reserva Ahora</em> alli.",
    "NO_TARG_DIV": "No pudo encontrar div objectivo",
    "CREATE_BRESV_SERVER_NO_RESPONSE": "No hay respuesta del servidor despu\u00e9s de tratar de crear la reserva.",
    "AUTO_bresv_grid_type": "Tipo",
    "AUTO_choose_a_brt": "Elija un tipo de recurso se puede reservar",
    "NO_BRA_RESULTS": "No se ha podido recuperar los atributos de recursos de reserva.",
    "AUTO_i_need_this_resource": "Necesito este recurso...",
    "AUTO_bresv_grid_end_time": "Hora de finalizaci\u00f3n",
    "BRSRC_NOT_FOUND": "No se pudo localizar ese recurso.",
    "AUTO_starting_at": "Entre",
    "CXL_BRESV_FAILURE2": "Error al cancelar las reservas:\n",
    "CREATE_BRESV_OK_MISSING_TARGET": "Creadas $ {0} reserva (s), pero $ {1} de \u00e9stos no podr\u00edan dirigirse a cualquier recurso.\n\nEsto significa que no ser\u00e1 posible para cumplir algunos de estos\nreservas hasta que un recurso adecuada est\u00e9 disponible.",
    "CREATE_BRESV_OK": "Creadas ${0} reserva(s)",
    "CREATE_BRESV_LOCAL_ERROR": "Excepci\u00f3n tratando de crear reservas: ",
    "GET_BRESV_LIST_NO_RESULT": "No hay resultados desde un servidor recuperaci\u00f3n de lista de reserva.",
    "BRSRC_RETRIVE_ERROR": "Error obteniendo el recurso: ",
    "AUTO_bresv_grid_resource": "Recurso",
    "WHERES_THE_BARCODE": "Ingrese un patr\u00f3n de c\u00f3digo de barras para hacer una reserva.",
    "AUTO_pickup_lib_selector": "Elegir la biblioteca de recogida para esta reservacion:",
    "NO_USABLE_BRSRC": "No hay recursos que se pueden reservar. Ajustar el tiempo de inicio y fin\nhasta que un recurso est\u00e1 disponible para su reserva.",
    "CREATE_BRESV_OK_MISSING_TARGET_BLOCKED_BY_CIRC": "La reserva deseada(s) est\u00e1n bloqueados por la circulaci\u00f3n(s) con la fecha de vencimiento siguiente (s):\n$ {0}",
    "CXL_BRESV_SELECT_SOMETHING": "No ha seleccionado ninguna reserva para cancelar.",
    "COULD_NOT_RETRIEVE_BRT_PASSED_IN": "Error al recuperar la reserva tipo de recurso",
    "CXL_BRESV_FAILURE": "Error de cancelar las reservas; servidor de silencio.",
    "ACTOR_CARD_NOT_FOUND": "C\u00f3digo de barras patr\u00f3n no se encuentra. Porfavor Int\u00e9ntelo de nuevo.",
    "SELECT_A_BRSRC_THEN": "Ha hecho clic en 'Reserva Seleccionada', pero no hay nada seleccionado!\n\nDebe seleccionar un recurso de la caja grande por encima.\n\n*** Si los recursos que seleccionar\u00eda est\u00e1n resaltados en ROJO,***\nestos articulos no est\u00e1n disponibles duarnte el tiempo solicutado; si\nes possible, elija otro recurso o cambiar el tiempo de reserva.",
    "GET_PATRON_NO_RESULT": "No hay respuesta del servidor despu\u00e9s de intentar buscar el patr\u00f3n de c\u00f3digo de barras.",
    "AUTO_with_these_attr": "Con estos atributos:",
    "ANY": "CUALQUIERA",
    "AUTO_bresv_grid_start_time": "Fecha de Inicio"
}