{
    "INVALIDATE": "Invalider",
    "DUPE_PATRON_IDENT": "Trouv\u00e9 ${0} client(s) avec la m\u00eame identification",
    "DUPE_PATRON_PHONE": "Trouv\u00e9 ${0} client(s) avec la m\u00eame num\u00e9ro de t\u00e9l\u00e9phone",
    "REQUESTING_USER": "Account requested by ${0} ${1}",
    "ADDRESS_HEADER": "Adresse",
    "SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    "ADDRESS_NEW": "Nouvelle adresse",
    "BARCODE_IN_USE": "Le code \u00e0 barres est d\u00e9j\u00e0 utilis\u00e9",
    "DELETE_ADDRESS": "Supprimer l'adresse ${0}?",
    "SHOW_SUGGESTED": "Montrer les champs sugg\u00e9r\u00e9s",
    "HOLD_NOTIFY_PHONE": "T\u00e9l\u00e9phone\u00a0: ",
    "INVALID_FORM": "Formulaire n'est pas valide. S'il vous pla\u00eet modifier et essayez \u00e0 nouveau.",
    "UPDATE_EXPIRE_DATE": "Update Expire Date",
    "VERIFY_PASSWORD": "V\u00e9rifier le mot de passe",
    "DUPE_PATRON_EMAIL": "Trouv\u00e9 ${0} client(s) avec la m\u00eame courriel",
    "PARENT_OR_GUARDIAN": "Parent/tuteur",
    "USER_SETTINGS": "Param\u00e8tres utilisateur",
    "ALL_CARDS_PRIMARY": "Principal",
    "REPLACE_BARCODE": "Remplacer le code \u00e0 barres",
    "HOLD_NOTIFY_SMS": "SMS\u00a0: ",
    "DUPE_PATRON_ADDR": "Trouv\u00e9 ${0} client(s) avec la m\u00eame adresse",
    "SAVE_CLONE": "Sauvegarder &amp; Cloner",
    "SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    "ADDRESS_OWNED": "Cette adresse appartient \u00e0 un autre utilisateur : ",
    "ALL_CARDS_BARCODE": "Code-barres",
    "DEFAULT_ADDRESS_TYPE": "DIFFUSION",
    "SHOW_REQUIRED": "Montrer seulement les champs obligatoires",
    "REPLACED_ADDRESS": "<div>Remplace l'adresse <b>${0}</b><br/> ${1} ${2}<br/> ${3}, ${4} ${5}</div>",
    "SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    "SHOW_ALL": "Montrer tous les champs",
    "RESET_PASSWORD": "Generate Password",
    "ALL_CARDS_APPLY": "Appliquer les modifications",
    "ADD": "Add",
    "ADDRESS_BILLING": "Facturation",
    "HOLD_NOTIFY_EMAIL": "Adresse \u00e9lectronique\u00a0: ",
    "ADDRESS_APPROVE": "Adresse approuv\u00e9e",
    "DUPE_USERNAME": "Nom d\u2019utilisateur d\u00e9j\u00e0 utilis\u00e9",
    "EXAMPLE": "Exemple: ",
    "SEE_ALL": "Voir tout",
    "STAT_CATS": "Cat\u00e9gories statistiques",
    "ALL_CARDS_ACTIVE": "Actif",
    "ALL_CARDS_CLOSE": "Fermer",
    "ADDRESS_MAILING": "Envoi",
    "ADDRESS_PENDING": "Il s\u2019agit d\u2019une adresse en suspens : ",
    "SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    "DUPE_PATRON_NAME": "Trouv\u00e9 ${0} client(s) avec la m\u00eame nom",
    "NEED_ADDRESS": "Une adresse est requise lors de l'inscription.",
    "SAVE": "Enregistrer",
    "DELETE": "Delete"
}