{
    "ENTER_BARCODE": "Introduzca el c\u00f3digo de barras de un ejemplar",
    "WORKSTATION_EXISTS": "Esta estaci\u00f3n de trabajo ya ha sido registrada. \u00bfLe gustar\u00eda utilizarla para esta estaci\u00f3n de auto-pr\u00e9stamo?",
    "FAIL_PART_no_item": "El sistema no pudo encontrar este elemento.",
    "HOLD_STATUS_WAITING": "#${0} en l\u00ednea con ${1} copias",
    "OPEN_CIRCULATION_EXISTS": "El ejemplar ${0} ha sido prestado a otro usuario",
    "RENEW_SUCCESS": "La renovaci\u00f3n del item ${0} ha sido exitosa",
    "FAIL_PART_no_matchpoint": "Las reglas del sistema no definen como manejar este ejemplar",
    "FAIL_PART_item.holdable": "El ejemplar no se aparta",
    "FAIL_PART_asset_copy_circulate": "El ejemplar no circula",
    "FAIL_PART_config_hold_matrix_test_max_holds": "El usuario ha superado el numero m\u00e1ximo de solicitudes.",
    "CHECKOUT_SUCCESS": "Pago del item ${0} realizado",
    "ALREADY_OUT": "El ejemplar ${0} ya est\u00e1 prestado",
    "TOTAL_FINES_ACCOUNT": "Total de multas en la cuenta: $${0}.",
    "PLEASE_LOGIN": "Inicie sesi\u00f3n con su nombre de usuario o c\u00f3digo de barras de la bibilioteca.",
    "FAIL_PART_transit_range": "El item no puede transitar hasta aqui.",
    "FAIL_PART_config_circ_matrix_test_available_copy_hold_ratio": "La relacion del elemento disponible a tener es demasiado baja.",
    "TOTAL_ITEMS_SESSION": "Total de ejemplares esta sesi\u00f3n: ${0}.",
    "FAIL_PART_config_hold_matrix_test_holdable": "Las reglas de solicitud rechazaron este item como no-solicitable.",
    "FAIL_PART_circ_holds_target_skip_me": "La biblioteca due\u00f1a del titulo no permite apartados",
    "TOTAL_FINES_SELECTED": "Total seleccionado: $${0}",
    "MISCELLANEOUS": "Miscelaneo",
    "ITEM_NOT_CATALOGED": "El elemento ${0} no se encontr\u00f3 en el sistema. Intente reescanear el elemento.",
    "FAIL_PART_config_rule_age_hold_protect_prox": "El tema es demasiado nuevo para transitar este momento.",
    "FAIL_PART_location.holdable": "La ubicaci\u00f3n del elemento no se puede retener",
    "TOTAL_HOLDS": "Usted tiene un total de ${0} apartados.",
    "FAIL_PART_asset_copy_location_circulate": "Ejemplares en esta estanter\u00eda no est\u00e1n disponibles para circulaci\u00f3n",
    "FAIL_PART_no_ultimate_items": "El sistema no ha encontrado items que coincidan con esta solicitud requerida.",
    "FAIL_PART_asset_copy_status": "El item no puede circular en este momento.",
    "UNKNOWN_ERROR": "Excepci\u00f3n no controlada con el c\u00f3digo de error ${0}",
    "CC_PAYABLE_BALANCE": "Monto total a pagar: $${0}",
    "WELCOME_BANNER": "Bienvenido, ${0}",
    "LOGIN_FAILED": "Error en inicio de sesi\u00f3n de ${0}",
    "GENERIC_CIRC_FAILURE": "No se puede desproteger art\u00edculo ${0}. Por favor, vea el personal.",
    "MAX_RENEWALS": "No hay m\u00e1s renovaciones permitidas para el ejemplar ${0}",
    "FAIL_PART_config_circ_matrix_test_total_copy_hold_ratio": "La proporci\u00f3n total de la pieza a tener es demasiada baja",
    "HOLDS_READY_FOR_PICKUP": "Tiene ${0} ejemplar(es) listos para recolecci\u00f3n.",
    "FAIL_PART_actor_usr_barred": "El patr\u00f3n es prohibido.",
    "ENTER_PASSWORD": "Escriba su contrase\u00f1a",
    "WORKSTATION_REQUIRED": "Se requiere una estaci\u00f3n de trabajo para iniciar sesi\u00f3n en autocheckin. Puede establecer el nombre de estaci\u00f3n de trabajo con el URL param 'ws'.  \n\n\u00bfLe gustar\u00eda registrar una nueva estaci\u00f3n de trabajo para esta interfaz de auto-comprobaci\u00f3n?",
    "TOTAL_ITEMS_ACCOUNT": "Total de ejemplares en la cuenta:  ${0}.",
    "FAIL_PART_no_user": "El sistema no pudo encontrar este usuario.",
    "FAIL_PART_status.holdable": "El ejemplar no est\u00e1 en un estado que permita ser apartado",
    "HOLD_STATUS_READY": "Listo para ser recogido",
    "FAIL_PART_config_circ_matrix_circ_mod_test": "El usuario tiene demasiados pr\u00e9stamos de este tipo de material",
    "PAYMENT_INVALID_USER_XACT_ID": "No podemos proceder con el pago, porque su cuenta se actualiza desde otra ubicaci\u00f3n. Por favor, actualice la interfaz o la sesi\u00f3n y volver a recuperar la \u00faltima informaci\u00f3n de la cuenta",
    "FAIL_PART_config_circ_matrix_test_circulate": "Las normas de circulacion rechazan este articulo como no circulable."
}