{
    "INVALIDATE": "Invalidate",
    "DUPE_PATRON_IDENT": "Found ${0} patron(s) with the same identification",
    "DUPE_PATRON_PHONE": "Found ${0} patron(s) with the same phone number",
    "REQUESTING_USER": "Account requested by ${0} ${1}",
    "ADDRESS_HEADER": "Address",
    "SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    "ADDRESS_NEW": "New Address",
    "BARCODE_IN_USE": "Barcode is already in use",
    "DELETE_ADDRESS": "Delete address ${0}?",
    "SHOW_SUGGESTED": "Show Suggested Fields",
    "HOLD_NOTIFY_PHONE": "Phone: ",
    "INVALID_FORM": "Form is invalid.  Please edit and try again.",
    "UPDATE_EXPIRE_DATE": "Update Expire Date",
    "VERIFY_PASSWORD": "Verify Password",
    "DUPE_PATRON_EMAIL": "Found ${0} patron(s) with the same email address",
    "PARENT_OR_GUARDIAN": "Parent/Guardian",
    "USER_SETTINGS": "User Settings",
    "ALL_CARDS_PRIMARY": "Primary",
    "REPLACE_BARCODE": "Replace Barcode",
    "HOLD_NOTIFY_SMS": "SMS: ",
    "DUPE_PATRON_ADDR": "Found ${0} patron(s) with the same address",
    "SAVE_CLONE": "Save &amp; Clone",
    "SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    "ADDRESS_OWNED": "This address is owned by another user: ",
    "ALL_CARDS_BARCODE": "Barcode",
    "DEFAULT_ADDRESS_TYPE": "MAILING",
    "SHOW_REQUIRED": "Show Only Required Fields",
    "REPLACED_ADDRESS": "<div>Replaces address <b>${0}</b><br/> ${1} ${2}<br/> ${3}, ${4} ${5}</div>",
    "SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    "SHOW_ALL": "Show All Fields",
    "RESET_PASSWORD": "Generate Password",
    "ALL_CARDS_APPLY": "Apply Changes",
    "ADD": "Add",
    "ADDRESS_BILLING": "Billing",
    "HOLD_NOTIFY_EMAIL": "Email: ",
    "ADDRESS_APPROVE": "Approve Address",
    "DUPE_USERNAME": "Username is already in use",
    "EXAMPLE": "Example: ",
    "SEE_ALL": "See All",
    "STAT_CATS": "Statistical Categories",
    "ALL_CARDS_ACTIVE": "Active",
    "ALL_CARDS_CLOSE": "Close",
    "ADDRESS_MAILING": "Mailing",
    "ADDRESS_PENDING": "This is a pending address: ",
    "SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    "DUPE_PATRON_NAME": "Found ${0} patron(s) with the same name",
    "NEED_ADDRESS": "An address is required during registration.",
    "SAVE": "Save",
    "DELETE": "Delete"
}