{
    "INVALIDATE": "Mit\u00e4t\u00f6i",
    "DUPE_PATRON_IDENT": "${0} asiakkaalla on sama tunnistautuminen",
    "DUPE_PATRON_PHONE": "${0} asiakkaalla on sama puhelinnumero",
    "REQUESTING_USER": "Tilin pyyt\u00e4j\u00e4: ${0} ${1}",
    "ADDRESS_HEADER": "Osoite",
    "SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    "ADDRESS_NEW": "Uusi osoite",
    "BARCODE_IN_USE": "Asiakastunnus on jo k\u00e4yt\u00f6ss\u00e4",
    "DELETE_ADDRESS": "Poistetaanko osoite ${0}?",
    "SHOW_SUGGESTED": "N\u00e4yt\u00e4 ehdotetut kent\u00e4t",
    "HOLD_NOTIFY_PHONE": "Puhelin: ",
    "INVALID_FORM": "Muoto ei kelpaa. Muokkaa ja yrit\u00e4 uudelleen.",
    "UPDATE_EXPIRE_DATE": "Update Expire Date",
    "VERIFY_PASSWORD": "Vahvista salasana",
    "DUPE_PATRON_EMAIL": "${0} asiakkaalla on sama s\u00e4hk\u00f6postiosoite",
    "PARENT_OR_GUARDIAN": "Vanhempi/huoltaja",
    "USER_SETTINGS": "K\u00e4ytt\u00e4j\u00e4n asetukset",
    "ALL_CARDS_PRIMARY": "Ensisijainen",
    "REPLACE_BARCODE": "Korvaa asiakastunnus",
    "HOLD_NOTIFY_SMS": "SMS: ",
    "DUPE_PATRON_ADDR": "${0} asiakkaalla on sama osoite",
    "SAVE_CLONE": "Tallenna ja kloonaa",
    "SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    "ADDRESS_OWNED": "Osoitteen omistaa toinen k\u00e4ytt\u00e4j\u00e4: ",
    "ALL_CARDS_BARCODE": "Asiakastunnus",
    "DEFAULT_ADDRESS_TYPE": "POSTITUS",
    "SHOW_REQUIRED": "N\u00e4yt\u00e4 vain vaaditut kent\u00e4t",
    "REPLACED_ADDRESS": "Korvaa osoitteen ${0}<br/> ${1} ${2}<br/> ${3}, ${4} ${5}",
    "SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    "SHOW_ALL": "N\u00e4yt\u00e4 kaikki kent\u00e4t",
    "RESET_PASSWORD": "Luo salasana",
    "ALL_CARDS_APPLY": "Ota muutokset k\u00e4ytt\u00f6\u00f6n",
    "ADD": "Add",
    "ADDRESS_BILLING": "Laskutus",
    "HOLD_NOTIFY_EMAIL": "S\u00e4hk\u00f6posti: ",
    "ADDRESS_APPROVE": "Hyv\u00e4ksy osoite",
    "DUPE_USERNAME": "K\u00e4ytt\u00e4j\u00e4tunnus on jo k\u00e4yt\u00f6ss\u00e4",
    "EXAMPLE": "Esimerkki: ",
    "SEE_ALL": "N\u00e4yt\u00e4 kaikki",
    "STAT_CATS": "Tilastolliset kategoriat",
    "ALL_CARDS_ACTIVE": "Aktiivinen",
    "ALL_CARDS_CLOSE": "Sulje",
    "ADDRESS_MAILING": "Postitus",
    "ADDRESS_PENDING": "T\u00e4m\u00e4 on vireill\u00e4 oleva osoite: ",
    "SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    "DUPE_PATRON_NAME": "${0} asiakkaalla on sama nimi",
    "NEED_ADDRESS": "Osoite vaaditaan rekister\u00f6ityess\u00e4.",
    "SAVE": "Tallenna",
    "DELETE": "Delete"
}