{
    "ENTER_BARCODE": "Please enter an item barcode",
    "WORKSTATION_EXISTS": "This workstation has already been registered.  Would you like to use it for this self-check station?",
    "FAIL_PART_no_item": "Das Medium konnte nicht gefunden werden",
    "HOLD_STATUS_WAITING": "#${0} in line with ${1} copies",
    "OPEN_CIRCULATION_EXISTS": "Item ${0} is already checked out to another user",
    "RENEW_SUCCESS": "Renewal of item ${0} succeeded",
    "FAIL_PART_no_matchpoint": "Die Systemregeln legen nicht fest, wie mit diesem Gegenstand umgegangen werden soll",
    "FAIL_PART_item.holdable": "The item is not holdable",
    "FAIL_PART_asset_copy_circulate": "Dieser Gegenstand kann nicht verliehen werden",
    "FAIL_PART_config_hold_matrix_test_max_holds": "Der Kunde hat die maximale Anzahl zul\u00e4ssiger Reservierungen erreicht",
    "CHECKOUT_SUCCESS": "Checkout of item ${0} succeeded",
    "ALREADY_OUT": "Item ${0} is already checked out",
    "TOTAL_FINES_ACCOUNT": "Total fines on account: $${0}.",
    "PLEASE_LOGIN": "Please log in with your username or library barcode.",
    "FAIL_PART_transit_range": "Dieser Gegenstand kann nicht so weit reisen",
    "FAIL_PART_config_circ_matrix_test_available_copy_hold_ratio": "Das Verh\u00e4ltnis ausgeliehene zu reservierten Gegenst\u00e4nden ist zu gering",
    "TOTAL_ITEMS_SESSION": "Total items this session: ${0}.",
    "FAIL_PART_config_hold_matrix_test_holdable": "Die Reservierungsregeln legen fest, dass dieser Gegenstand nicht reserviert werden darf",
    "FAIL_PART_circ_holds_target_skip_me": "Die Umlaufbibliothek dieses Gegenstands leistet keine Ablagen",
    "TOTAL_FINES_SELECTED": "Selected total: $${0}",
    "MISCELLANEOUS": "Miscellaneous",
    "ITEM_NOT_CATALOGED": "Item ${0} was not found in the system.  Try re-scanning the item.",
    "FAIL_PART_config_rule_age_hold_protect_prox": "The item is too new to transit this far",
    "FAIL_PART_location.holdable": "The item's location is not holdable",
    "TOTAL_HOLDS": "You have ${0} total holds.",
    "FAIL_PART_asset_copy_location_circulate": "Items from this shelving location do not circulate",
    "FAIL_PART_no_ultimate_items": "Das System konnte keine Gegenst\u00e4nde finden, die dieser Reservierungsanfrage entsprechen",
    "FAIL_PART_asset_copy_status": "Der Gegenstand kann aktuell nicht verliehen werden",
    "UNKNOWN_ERROR": "An unhandled exception occurred with error code ${0}",
    "CC_PAYABLE_BALANCE": "Total amount to pay: $${0}",
    "WELCOME_BANNER": "Willkommen, ${0}",
    "LOGIN_FAILED": "Login for ${0} failed",
    "GENERIC_CIRC_FAILURE": "Unable to check out item ${0}.  Please see staff.",
    "MAX_RENEWALS": "No more renewals allowed for item ${0}",
    "FAIL_PART_config_circ_matrix_test_total_copy_hold_ratio": "Das Gesamtverh\u00e4ltnis ausgeliehene zu reservierten Gegenst\u00e4nden ist zu gering",
    "HOLDS_READY_FOR_PICKUP": "You have ${0} item(s) ready for pickup.",
    "FAIL_PART_actor_usr_barred": "Das Kundenkonto ist gesperrt",
    "ENTER_PASSWORD": "Please enter your password",
    "WORKSTATION_REQUIRED": "A workstation is required to log in to selfcheck.  You can set the  workstation name with URL param 'ws'.  \n\nWould you like to register a new workstation for this self-check interface?",
    "TOTAL_ITEMS_ACCOUNT": "Total items on account:  ${0}.",
    "FAIL_PART_no_user": "Das Kundenkonto konnte nicht gefunden werden",
    "FAIL_PART_status.holdable": "The item is not in a holdable status",
    "HOLD_STATUS_READY": "Bereit zur Abholung",
    "FAIL_PART_config_circ_matrix_circ_mod_test": "Der Kunde hat zu viele Medien dieses Typs ausgeliehen",
    "PAYMENT_INVALID_USER_XACT_ID": "We cannot proceed with the payment, because your account was updated from another location.  Please refresh the interface or log out and back in to retrieve the latest account information",
    "FAIL_PART_config_circ_matrix_test_circulate": "Die Umlaufregeln kennzeichnen diesen Gegenstand als nicht zirkulierbar"
}